
THE ARROW OF TIME FROM MOTION AND CURVATURE EXCHANGE
A Physical Resolution Without Statistical Assumptions
=====================================================================

Author:
Martin Ollett
Independent Researcher
2025


---------------------------------------------------------------------
ABSTRACT
---------------------------------------------------------------------

The arrow of time remains unresolved in fundamental physics despite
time-reversal symmetric microscopic laws. Conventional explanations
appeal to statistical entropy increase, coarse-graining, or special
initial conditions, all of which implicitly assume a pre-existing time
parameter and external ensembles.

We present a physically closed resolution of the arrow of time within
the Motion–TimeSpace (MTS) framework. Time is shown to emerge as the rate
of irreversible exchange between motion and curvature memory. Once
motion exists, Newtonian inertia, exact momentum conservation, and
monotonic curvature-memory accumulation together forbid time reversal
without external intervention.

This result is established without probabilistic assumptions,
coarse-graining, imposed dissipation, or modified fundamental
symmetries. Numerical evidence from a derived electromagnetic sector
demonstrates irreversible energy transfer into curvature memory while
conserving total momentum to machine precision. Gravitational and
kinematic time dilation are recovered as manifestations of
curvature-exchange resistance.

The arrow of time is thus identified as an inertial–geometric property
of motion in a universe that remembers curvature. Entropy does not
generate time’s direction; it measures the accumulation of irreversible
geometric memory.


---------------------------------------------------------------------
1. THE ARROW OF TIME PROBLEM
---------------------------------------------------------------------

Fundamental equations of classical mechanics, electromagnetism, quantum
mechanics, and general relativity are invariant under time reversal.
Nevertheless, physical processes exhibit strong temporal asymmetry:
radiation disperses, heat flows from hot to cold, structures form and
decay, and clocks advance monotonically.

Standard explanations invoke:
- statistical typicality,
- coarse-grained entropy increase,
- environmental decoherence,
- or special low-entropy initial conditions.

All such explanations implicitly assume:
1. a pre-existing time parameter,
2. an external ensemble or bath,
3. reversible microstates distinguished probabilistically.

A physically closed universe cannot rely on these assumptions. A valid
explanation of time’s direction must not presuppose time itself.


---------------------------------------------------------------------
2. MOTION AS THE ORIGIN OF TIME
---------------------------------------------------------------------

In Motion–TimeSpace, time is not a coordinate. It is an ordering
parameter generated by motion.

Before motion exists:
- no momentum exists,
- no ordering exists,
- no conservation laws apply,
- no time parameter is defined.

When directed motion appears, it simultaneously defines:
- an inertial frame,
- an ordering of events,
- a conserved momentum.

Time begins when motion begins.


---------------------------------------------------------------------
3. NEWTONIAN INERTIA AS A GLOBAL CONSTRAINT
---------------------------------------------------------------------

Newton’s first law is usually treated as a kinematic statement. In a
physically closed universe, it becomes a global constraint.

Once finite momentum exists:

    p_total != 0

then:

    d(p_total)/dt = 0

Total momentum conservation implies that reversing motion requires an
equal and opposite impulse. In a closed universe, no external agent
exists to provide such an impulse.

Therefore, global time reversal is dynamically forbidden. The arrow of
time is not improbable; it is inaccessible.

This establishes a preferred temporal direction immediately upon the
existence of motion.


---------------------------------------------------------------------
4. CURVATURE MEMORY AND IRREVERSIBILITY
---------------------------------------------------------------------

Motion in MTS generates a curvature-memory field, Gamma(x,t), which
records geometric deformation caused by motion.

Gamma has three essential properties:

1. Monotonicity:
       dGamma/dt >= 0 during interactions

2. Non-conservativity:
       Gamma is not an energy carrier

3. Back-reaction:
       Gamma resists further motion

Once curvature memory accumulates, the accessible phase space is
permanently altered. Exact recurrence is forbidden even in principle.

Irreversibility is therefore geometric, not statistical.


---------------------------------------------------------------------
5. ENTROPY AS A DIAGNOSTIC, NOT A CAUSE
---------------------------------------------------------------------

Entropy traditionally defines the arrow of time. In MTS, entropy instead
measures curvature-exchange inefficiency.

Define the curvature-tension parameter:

    Gamma_kappa = dS / dE

Time flow is governed by:

    d(tau)/dt = sqrt( 1 - Gamma_kappa )

Interpretation:
- Small dS/dE  -> efficient exchange -> normal time flow
- Large dS/dE  -> inefficient exchange -> time slows
- dS/dE -> 1   -> exchange halts -> evolution freezes

Entropy does not cause time’s direction. It quantifies the rate of
irreversible curvature accumulation once motion exists.


---------------------------------------------------------------------
6. RECOVERY OF RELATIVISTIC TIME DILATION
---------------------------------------------------------------------

In the weak-field limit of general relativity:

    d(tau)/dt = sqrt( 1 + 2*Phi / c^2 )

Define:

    Gamma_kappa = -2*Phi / c^2

Then:

    d(tau)/dt = sqrt( 1 - Gamma_kappa )

Thus:
- gravitational time dilation,
- kinematic time dilation,
- thermodynamic slowing

all arise from resistance to curvature exchange.

Time dilation is not a distortion of time; it is suppression of motion
exchange through curvature.


---------------------------------------------------------------------
7. NUMERICAL EXISTENCE PROOF: ELECTROMAGNETIC SECTOR
---------------------------------------------------------------------

A derived electromagnetic sector within MTS provides a direct numerical
demonstration of irreversibility without imposed asymmetry.

Key results from simulation:
- Governing equations are time-reversal symmetric
- Electromagnetic energy decreases during interaction
- Curvature memory Gamma increases monotonically
- Total momentum conserved to approximately 1e-17 precision
- No external bath, gauge fields, or imposed dissipation

This establishes that irreversible time ordering emerges purely from
geometric dynamics while preserving exact translational symmetry.

The arrow of time arises dynamically.


---------------------------------------------------------------------
8. COSMOLOGICAL CONSISTENCY
---------------------------------------------------------------------

On cosmic scales, curvature exchange integrates into a global curvature
gradient, Gamma_G(z).

Observational fits to:
- Type Ia supernovae
- BAO
- H(z) measurements

require Gamma_G(z) to evolve dynamically. A static curvature term is
statistically rejected.

Cosmic acceleration and the Hubble tension emerge as consequences of
curvature-exchange dynamics rather than exotic matter or modified
gravity.


---------------------------------------------------------------------
9. MAIN THEOREM
---------------------------------------------------------------------

Theorem (Inertial–Geometric Arrow of Time):

In a physically closed universe that admits motion with conserved total
momentum and generates monotonic curvature memory, time evolution is
necessarily irreversible.

Proof (sketch):
- Motion defines temporal ordering
- Momentum conservation forbids global reversal
- Curvature memory permanently alters phase space
- No internal operator can erase Gamma and restore prior states
QED


---------------------------------------------------------------------
10. CONCLUSION
---------------------------------------------------------------------

The arrow of time does not arise from probability, statistics, or special
initial conditions. It arises because motion exists, inertia preserves
it, and curvature remembers it.

Entropy measures irreversibility; it does not generate it.

Time is the rate at which motion irreversibly exchanges curvature
information.

This resolves the arrow of time as a physical, inertial, and geometric
property of the universe.


=====================================================================
END OF PAPER
=====================================================================
