TITLE  
The Motion–Timespace (MTS) Galaxy Law: A Transport–Response Framework for Disk Galaxies  

---

ABSTRACT  

We present a transport-based derivation of galaxy rotation curves within the Motion–Timespace (MTS) framework. A curvature–exchange field, emerging from a coarse-grained microscopic motion field ψ, drives a support field whose radial transport produces a closed-form rotation law. The resulting background law is cosmologically normalised and contains no free parameters on a clean subset of disk galaxies.  

First-order corrections arise from structural deviations, specifically gas depletion and bulge concentration. We show that previously identified threshold behaviour and lag-based corrections are artifacts of fitting and unstable scale definitions. The correct governing variable is an integrated transport memory, producing a zero-parameter saturating modification of the effective transport scale.  

Residuals are not eliminated but reorganise into distinct response families characterised by different radial kernels. Late-type galaxies follow a unified transport law with memory-driven corrections and emergent branching in response shape, while early-type galaxies do not belong to this response family.  

---

1. INTRODUCTION  

Galaxy rotation curves exhibit systematic deviations from baryonic expectations. Existing approaches either introduce additional matter components or modify gravitational dynamics. In contrast, the Motion–Timespace (MTS) framework treats galaxy dynamics as a macroscopic transport response to a cosmological curvature–motion background.  

The aim of this work is to derive the galaxy law within this framework, test it directly against raw rotation curve data, and identify the minimal correction structure required by observations.  

---

2. THE MTS FRAMEWORK  

2.1 Emergent geometry  

A scalar field ψ defines an emergent metric via coarse-grained gradient covariance:

g_μν = η_μν + ⟨∂_μ ψ, ∂_ν ψ⟩  

2.2 Curvature–exchange field  

A scalar Γ = F[ψ, g] encodes curvature–motion exchange.  

2.3 Action  

The system includes gravitational, scalar, constraint, matter, and transport sectors. The transport sector introduces a support field χ governing deviations from baryonic rotation.  

2.4 Interpretation of ψ and Γ  

Within the broader Motion–TimeSpace framework, ψ is interpreted as a fundamental motion field whose linear propagating modes correspond to radiation-like behaviour and whose nonlinear localized configurations form stable matter-like structures.  

A secondary scalar Γ emerges dynamically as a curvature–memory field, accumulating irreversible geometric information generated by ψ.  

The present work operates at the coarse-grained level, requiring only:  

(i) the emergent metric from gradient covariance of ψ  
(ii) a curvature–exchange field Γ that couples to macroscopic transport  

---

3. TRANSPORT EQUATION AND BACKGROUND LAW  

The transport equation is:

u^μ ∇_μ χ + χ/τ_Γ = Γ/4  

In the stationary disk limit:

v_Γ dχ/dr + χ/τ_Γ = Γ₀/4  

Defining:

L = v_Γ τ_Γ  

gives:

χ(r) = (Γ₀/4) L (1 − e^(−r/L))  

Mapping to observables:

V²(r) = V_bar²(r) + (Γ₀/4) L (1 − e^(−r/L))  

Using:

L = k (j_bar / V_bar,char),   k ≈ 0.9  

and:

Γ_drive = cH₀ / (8π)  

gives the zero-parameter background galaxy law.  

---

4. PHOTOMETRIC CLOSURE AND SCALE STABILITY  

Using exponential disks:

j_bar = 2h V_flat  

gives:

L_pred = 2k h  

This stabilises the scale law and removes spurious variability in j/V formulations.  

Under this closure:

L_pred ≈ 1.8h  

and ln(h/L) loses independent physical meaning.  

---

5. SHAPE CORRECTION  

Replacing the exponential kernel with:

1 − exp[−(r/L)^q]  

improves disk fits, with:

q ≈ 1.3 (LTGs)  

---

6. LINEARISED CORRECTION SECTOR  

Perturbations satisfy:

(∇² − ℓ_Γ⁻²) δΓ = −δS_Γ / Z_Γ  

Dominant source channels:

- bulge concentration  
- gas-driven evolution  

---

7. BULGE CORRECTION  

Screened compactness gives:

α_b ∝ (r_disk / r_bul)²  

Observed normalisations:

A_b ≈ 0.46 (peak)  
A_b ≈ 3.2 (integral)  

Bulge effects are sub-dominant in LTGs.  

---

8. GAS CORRECTION (ORIGINAL FORMULATION)  

Transport memory:

dχ/dt + χ/τ_Γ = Γ_drive(t)/4  

Proxy variable:

z = (1 − f_gas) |ln(h/L)|  

Saturation:

1 − exp(−λ z),   λ ≈ 0.4  

---

9. DERIVED GAS-SECTOR BENCHMARK  

From transport theory:

A_g ~ (L_past − L_now)/L_now × (1 − e^(−n))  

Using L ~ j/V:

A_g ~ (j_past − j_now)/j_now × (1 − e^(−n))  

Observable closure:

A_g^(0) = 1 − exp[−(1 − f_gas)|ln(h/L)|]  

This captures a substantial fraction of the gas correction signal.  

---

10. FAILURE OF THRESHOLD AND LAG INTERPRETATIONS  

- threshold g₀ ≈ 0.89 is a fitting artifact  
- lag variable collapses under photometric closure  

The system follows a continuous saturating response.  

---

11. TRANSPORT MEMORY LAW (UPDATED RESULT)  

Define:

memory_load = (1 − f_gas)(R_outer / h)  

Saturation scale:

S = (k/π)(R_outer / h)  

Effective scale:

L_eff = L_pred [1 + S (1 − exp(−memory_load / S))]  

This form is zero-parameter and replaces proxy-based gas corrections.  

---

12. UPDATED LTG LAW  

V²(r) = V_bar²(r)  
+ (cH₀ / 8π) × L_eff × [1 − exp(−(r / L_eff)^q)]  

with:

q ≈ 1.3  

---

13. EMERGENT RESPONSE FAMILIES  

Residuals split into:

- main LTG branch: q ≈ 1.3  
- off-family LTGs: q ≈ 2.2  

Predictive rule:

(1 − f_gas)(R_outer / h) ≳ 12  

Branching occurs in response shape, not scale.  

---

14. RESULTS  

Clean LTGs: RMSE ≈ 8–10 km/s  
Full LTGs: ≈19 → ≈12–13 km/s  
Ceiling: ≈10 km/s  

---

15. EARLY-TYPE GALAXIES  

ETGs:

- not described by LTG law  
- q ≈ 2.4 preferred  
- RMSE ≳ 50 km/s  

---

16. INTERPRETATION  

Hierarchy:

Level 1 — background transport  
Level 2 — photometric closure  
Level 3 — memory saturation  
Level 4 — response branching  

---

17. DERIVED VS EMPIRICAL  

Derived:
- transport law  
- photometric closure  
- memory-load structure  

Partially derived:
- bulge scaling  
- gas benchmark  

Empirical:
- q parameter  
- proxy mappings  

---

18. CONCLUSION  

The MTS framework yields a transport-response law for disk galaxies with:

- cosmological normalisation  
- photometric scale closure  
- zero-parameter memory correction  
- emergent response branching  

ETGs require a distinct response family.  

---

19. METHODS AND DATA RECONSTRUCTION  

Data: SPARC ROTMOD files  

Columns used:

r, V_obs, e_V, V_gas, V_disk, V_bulge  

Baryonic reconstruction:

V_bar² = V_gas² + V_disk² + V_bulge²  

Cleaning:

- finite values only  
- r > 0, V_obs > 0  
- sorted, duplicates removed  

Photometry:

h from SBdisk fits  

Derived quantities:

V_bar,char = max(V_bar)  
j_bar = ∫ r V_bar² dr / ∫ V_bar dr  
R_outer = max(r)  

Gas fraction:

f_gas = M_gas / (M_gas + M_star)  

Evaluation:

RMSE = sqrt(mean[(V_model − V_obs)²])  

Branch classification:

memory_load = (1 − f_gas)(R_outer/h)  

No galaxy-specific fitting is used in the zero-parameter or memory-law models.  

---

FINAL STATEMENT  

Disk galaxy rotation curves are consistent with a transport response to a cosmological curvature background, with corrections governed by accumulated transport memory and expressed through distinct response families.  

---

END
