from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]

STATUS = "Y5_measured_GM_source_current_closure_attempt_written_first_epsilon_charge_input_template_no_Newton_or_local_GR_promotion"
CLAIM_CEILING = "measured_GM_source_current_closure_or_first_input_fill_only_no_measured_GM_Newton_beta_PPN_or_local_GR_pass"
NEXT_TARGET = "533-Y5-epsilon-charge-first-row-runner-or-source-current-theorem.md"

DOC_PATH = Path("532-Y5-measured-GM-source-current-closure-or-first-input-fill.md")
SOURCE_REGISTER_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_CLOSURE_SOURCE_REGISTER.csv")
CLOSURE_ATTEMPT_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_CLOSURE_THEOREM_ATTEMPT.csv")
EPSILON_CHARGE_TEMPLATE_PATH = Path("source-intake/mts_residuals/P8_Y5_EPSILON_CHARGE_INPUT_TEMPLATE.csv")
FIRST_FILL_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_FIRST_INPUT_FILL.csv")
RESIDUAL_DECOMPOSITION_PATH = Path("source-intake/mts_residuals/P8_Y5_EPSILON_CHARGE_RESIDUAL_DECOMPOSITION.csv")
DECISION_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_CLOSURE_DECISION.csv")
VALIDATION_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_CLOSURE_VALIDATION.csv")
ROUTE_UPDATE_PATH = Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_CLOSURE_ROUTE_UPDATE.csv")


SOURCE_REGISTER = [
    {
        "source_file": "531-Y5-source-normalized-Newton-and-beta-residual-envelope.md",
        "role": "selects source-normalized Newton as the first-order precondition for beta/PPN",
    },
    {
        "source_file": "523-Y5-Gauss-orbital-calibration-or-source-normalization-residual-score.md",
        "role": "source-normalization residual scorecard, especially SRC523_0",
    },
    {
        "source_file": "522-Y5-extra-mass-projection-silence-or-channelwise-bound.md",
        "role": "extra projected mass channels that obstruct source-current closure",
    },
    {
        "source_file": "521-Y5-PiM-projector-owner-or-radial-bound-runner.md",
        "role": "Pi_M owner fork and commutator/radial inputs",
    },
    {
        "source_file": "520-Y5-source-current-Ward-closure-or-bound-row.md",
        "role": "Ward-to-mass-flux bridge and product-rule obstruction",
    },
    {
        "source_file": "458-Hamiltonian-charge-to-Poisson-Gauss-calibration-gate.md",
        "role": "Hamiltonian charge to measured-GM calibration contract",
    },
    {
        "source_file": "460-source-normalized-Newton-branch-theorem-stack.md",
        "role": "SN0-SN11 source-normalized Newton theorem stack",
    },
    {
        "source_file": "505-parent-Noether-mass-charge-closure-theorem-or-closure-demotion.md",
        "role": "parent Noether mass-charge closure theorem attempt",
    },
    {
        "source_file": "499-parent-source-identity-for-closed-PiM-flux-or-radial-template.md",
        "role": "source identity decomposition for d(Pi_M J_H)",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_WARD_BRIDGE.csv",
        "role": "520 Ward bridge rows",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_WARD_TO_MASS_FLUX_OBSTRUCTION.csv",
        "role": "520 obstruction ledger",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_MEFF_FLUX_BOUND_UPDATE.csv",
        "role": "520 bound rows for M_eff/radial/q_loc projection",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_PIM_RADIAL_BOUND_INPUT.csv",
        "role": "521 Pi_M commutator/projector/radial input rows",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_EXTRA_MASS_CHANNELWISE_BOUND_INPUT.csv",
        "role": "522 channelwise extra-mass input rows",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_SOURCE_NORMALIZATION_RESIDUAL_SCORECARD.csv",
        "role": "523 source-normalization scorecard",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Hamiltonian_charge_Poisson_Gauss_calibration_CONTRACT.csv",
        "role": "PG0-PG10 calibration contract",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_source_normalized_Newton_branch_STACK.csv",
        "role": "SN0-SN11 Newton stack",
    },
    {
        "source_file": "scripts/Y5_measured_GM_source_current_closure_or_first_input_fill.py",
        "role": "this checkpoint generator",
    },
]


CLOSURE_ATTEMPT_ROWS = [
    {
        "rung_id": "SC532_0_observed_time_charge",
        "required_identity": "Hamiltonian/boundary charge is generated by observed time before orbital fitting",
        "math_form": "H_xi=B_xi on shell with xi normalized in the observed frame",
        "why_needed": "without a real observed-time charge, B_xi/G_eff is not a source-current mass",
        "current_status": "conditional_from_prior_Hamiltonian_rows_not_parent_derived",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_1_Hilbert_source_current",
        "required_identity": "same observed coframe defines the Hilbert/source current",
        "math_form": "J_H[tau]=T_m^{mu nu}[e_obs] tau_nu dSigma_mu",
        "why_needed": "gives a parent-side source object rather than an orbital fit",
        "current_status": "conditional_source_current_defined_but_not_mass_flux_closed",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_2_charge_current_variation_identity",
        "required_identity": "Hamiltonian charge equals the projected Hilbert mass current",
        "math_form": "B_xi/G_eff = M_H[Pi_M J_H] and delta B_xi = delta int_S Pi_M J_H",
        "why_needed": "this is exactly epsilon_charge=0",
        "current_status": "not_parent_derived_PG1_open",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_3_parent_owned_PiM",
        "required_identity": "Pi_M is parent-owned charge data, not a post-readout mask",
        "math_form": "Pi_M J = ell_M(J) omega_M_top or equivalent parent charge projector",
        "why_needed": "a readout projector cannot define source mass before the measurement it is meant to explain",
        "current_status": "best_topological_route_conditional_Hilbert_equality_missing",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_4_zero_projector_commutator",
        "required_identity": "projected current has no product-rule leakage",
        "math_form": "d(Pi_M J_H)=Pi_M dJ_H + [d,Pi_M]J_H with [d,Pi_M]J_H=0",
        "why_needed": "commutator leakage becomes M_eff drift/radial source hair",
        "current_status": "not_derived_bound_input_exists",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_5_zero_extra_projection",
        "required_identity": "non-Hilbert/boundary/domain/memory/non-EH/coupling/frame/projector/anomaly channels carry no Pi_M mass projection",
        "math_form": "Pi_M dJ_extra=0 channelwise",
        "why_needed": "extra projected mass shifts measured GM and source normalization",
        "current_status": "not_derived_channelwise_inputs_unfilled",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_6_absolute_normalization",
        "required_identity": "G_eff normalization is fixed before fitting and has no source/range/time/frame/domain derivative",
        "math_form": "partial_{t,r,A,lambda,frame,domain} G_eff=0",
        "why_needed": "otherwise B_xi/G_eff can be rescaled into a hidden fitted GM",
        "current_status": "not_parent_derived",
        "valid_for_claim": "false",
    },
    {
        "rung_id": "SC532_7_measured_GM_next_gate",
        "required_identity": "after charge-current equality, Poisson/Gauss/orbital readout still calibrates the charge to mu_obs",
        "math_form": "nabla^2 Phi=4pi G_eff rho_H; surface_int grad Phi dS=4pi G_eff M_H; r^2|a_r|=G_eff M_H",
        "why_needed": "epsilon_charge=0 is necessary but not sufficient for Newton",
        "current_status": "downstream_gate_open",
        "valid_for_claim": "false",
    },
]


RESIDUAL_DECOMPOSITION_ROWS = [
    {
        "residual_id": "ECD532_0_normalization_factor",
        "symbol": "epsilon_Hamiltonian_norm",
        "definition": "wrong factor or subtraction in B_xi/G_eff relative to source units",
        "formula": "(B_xi/G_eff - Q_parent)/M_H",
        "mapped_scorecard_row": "SRC523_0_charge_current_normalization",
        "required_input": "Hamiltonian charge normalization proof or numeric mismatch",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_1_PiM_equality",
        "symbol": "epsilon_PiM_equality",
        "definition": "failure of Pi_M Hilbert source current to equal the boundary/Hamiltonian mass charge",
        "formula": "(Q_parent - M_H[Pi_M J_H])/M_H",
        "mapped_scorecard_row": "SRC523_0_charge_current_normalization;SRC523_6_Meff_flux_derivative",
        "required_input": "Pi_M parent theorem, equality residual integral, or sourced bound",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_2_projector_commutator",
        "symbol": "epsilon_commutator",
        "definition": "finite-shell product-rule leakage from d(Pi_M J_H)",
        "formula": "M_H^-1 int_A [d,Pi_M]J_H",
        "mapped_scorecard_row": "SRC523_6_Meff_flux_derivative;SRC523_8_radial_source_hair",
        "required_input": "Pi_M commutator theorem-zero or finite-shell profile",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_3_extra_projection",
        "symbol": "epsilon_extra_projection",
        "definition": "non-Hilbert extra mass channels projected into source charge",
        "formula": "sum_i |M_H^-1 int_A Pi_M dJ_extra_i|",
        "mapped_scorecard_row": "SRC523_4_extra_mass_channels_total",
        "required_input": "all 522 channelwise rows theorem-zero or individually bounded",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_4_boundary_anomaly",
        "symbol": "epsilon_boundary_anomaly",
        "definition": "boundary improvement, reference, multiplier, or parent-anomaly offset in source charge",
        "formula": "M_H^-1(int_boundary Pi_M K_owner + int_A A_parent)",
        "mapped_scorecard_row": "SRC523_2_Gauss_volume_boundary;SRC523_4_extra_mass_channels_total",
        "required_input": "boundary/no-anomaly theorem or coefficient map",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_5_Geff_drift",
        "symbol": "epsilon_Geff_abs",
        "definition": "absolute coupling/time/range/species/frame/domain drift inside B_xi/G_eff",
        "formula": "delta ln G_eff and derivatives after source normalization",
        "mapped_scorecard_row": "SRC523_5_Geff_time_or_range_drift",
        "required_input": "global coupling theorem or derivative residual row",
        "valid_for_claim": "false",
    },
    {
        "residual_id": "ECD532_6_total_no_cancellation",
        "symbol": "epsilon_charge_abs_envelope",
        "definition": "strict absolute envelope for first charge-current row",
        "formula": "sum |epsilon_Hamiltonian_norm|+|epsilon_PiM_equality|+|epsilon_commutator|+|epsilon_extra_projection|+|epsilon_boundary_anomaly|+|epsilon_Geff_abs|",
        "mapped_scorecard_row": "SRC523_0_charge_current_normalization",
        "required_input": "all preceding residuals theorem-zero or bounded; no cancellation credit",
        "valid_for_claim": "false",
    },
]


EPSILON_CHARGE_TEMPLATE_ROWS = [
    {
        "template_id": "ECI532_0_theorem_zero_certificate",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "input_mode": "derived_zero",
        "required_columns": "system_id;branch_id;theorem_id;premises_closed;source_file;equation_reference;assumptions;valid_for_claim",
        "pass_rule": "SC532_0 through SC532_6 are all source-backed and no downstream closure-only multiplier is used",
        "current_status": "not_supplied",
    },
    {
        "template_id": "ECI532_1_numeric_residual",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "input_mode": "numeric_bound",
        "required_columns": "system_id;Bxi_over_Geff;MH_PiMJH;epsilon_charge;units;normalization;source_file;assumptions;bound_used;pass_fail",
        "pass_rule": "epsilon_charge has units/normalization/source path and is below mapped source-normalization lock without cancellation",
        "current_status": "not_supplied",
    },
    {
        "template_id": "ECI532_2_component_envelope",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "input_mode": "component_envelope",
        "required_columns": "epsilon_Hamiltonian_norm;epsilon_PiM_equality;epsilon_commutator;epsilon_extra_projection;epsilon_boundary_anomaly;epsilon_Geff_abs;source_files",
        "pass_rule": "sum of absolute components is below the adopted measured-GM/source-normalization lock",
        "current_status": "not_supplied",
    },
]


FIRST_FILL_ROWS = [
    {
        "fill_id": "FF532_0_SRC523_0_current",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "symbol": "epsilon_charge",
        "formula": "(B_xi/G_eff - M_H[Pi_M J_H])/M_H",
        "current_value": "MISSING_THEOREM_OR_NUMERIC_VALUE",
        "current_status": "unfilled_after_derivation_attempt",
        "valid_for_claim": "false",
        "next_action": "533-Y5-epsilon-charge-first-row-runner-or-source-current-theorem.md",
    },
    {
        "fill_id": "FF532_1_conditional_zero_route",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "symbol": "epsilon_charge",
        "formula": "0 if SC532_0..SC532_6 all pass",
        "current_value": "CONDITIONAL_ZERO_NOT_CURRENT_MTS_DERIVED",
        "current_status": "conditional_only",
        "valid_for_claim": "false",
        "next_action": "supply theorem-zero certificate or numeric residual input",
    },
    {
        "fill_id": "FF532_2_first_numeric_slot",
        "scorecard_row": "SRC523_0_charge_current_normalization",
        "symbol": "epsilon_charge_numeric",
        "formula": "numeric epsilon_charge with units and source path",
        "current_value": "AWAITING_INPUT",
        "current_status": "template_written",
        "valid_for_claim": "false",
        "next_action": "fill P8_Y5_EPSILON_CHARGE_INPUT_TEMPLATE.csv",
    },
]


DECISION_ROWS = [
    {
        "decision_id": "D532_0_derivation_attempt",
        "status": "source_current_closure_theorem_attempt_written",
        "meaning": "the exact premises required to set epsilon_charge=0 are explicit",
        "claim_status": "conditional_not_satisfied",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D532_1_first_input",
        "status": "epsilon_charge_first_input_template_written",
        "meaning": "SRC523_0 now has theorem-zero, numeric, and component-envelope input routes",
        "claim_status": "unfilled_no_Newton_claim",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D532_2_measured_GM_not_yet",
        "status": "charge_current_equality_not_enough_for_Newton",
        "meaning": "even future epsilon_charge=0 still needs Poisson/Gauss/orbital calibration and derivative silence",
        "claim_status": "measured_GM_false",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D532_3_next",
        "status": "build_first_row_runner_or_supply_theorem_certificate",
        "meaning": "next work should either evaluate epsilon_charge from inputs or try to close the source-current theorem certificate",
        "claim_status": "active_private_research",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D532_4_private_no_push",
        "status": "private_no_github_no_promotion",
        "meaning": "no public/GitHub action is performed",
        "claim_status": "safe_private_work",
        "next_action": "continue_private_derivation",
    },
]


ROUTE_UPDATE_ROWS = [
    {
        "route_id": "SOURCE_CURRENT_CLOSURE",
        "previous_status": "measured_GM_precondition_unfilled",
        "new_status": "epsilon_charge_zero_route_explicit_but_not_derived",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "SRC523_0_EPSILON_CHARGE",
        "previous_status": "not_loaded_unfilled",
        "new_status": "first_input_template_written_no_value_or_theorem_supplied",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "PIM_PROJECTOR",
        "previous_status": "owner_fork_written_topological_best_Hodge_retained_readout_forbidden",
        "new_status": "central_premise_for_epsilon_charge_zero",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "EXTRA_MASS_PROJECTION",
        "previous_status": "silence_theorem_written_channelwise_bound_inputs_written_no_zero_derived",
        "new_status": "enters_epsilon_charge_component_envelope",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "SOURCE_NORMALIZED_NEWTON",
        "previous_status": "first_order_precondition_for_beta_and_local_GR",
        "new_status": "still_blocked_by_epsilon_charge_unfilled_plus_downstream_Gauss_orbital_rows",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "LOCAL_GR",
        "previous_status": "still_blocked_Newton_precondition_and_beta_envelope_missing_components",
        "new_status": "still_blocked_no_measured_GM_source_current_closure",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
]


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


def read_csv(path: Path) -> list[dict[str, str]]:
    full_path = ROOT / path
    if not full_path.exists():
        return []
    with full_path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def source_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in SOURCE_REGISTER:
        full_path = ROOT / item["source_file"]
        rows.append({**item, "exists": full_path.exists()})
    return rows


def validation_rows(sources: list[dict[str, Any]]) -> list[dict[str, str]]:
    missing_sources = [row["source_file"] for row in sources if row["exists"] is not True]
    ward_rows = read_csv(Path("source-intake/mts_residuals/P8_Y5_SOURCE_CURRENT_WARD_BRIDGE.csv"))
    pim_rows = read_csv(Path("source-intake/mts_residuals/P8_Y5_PIM_RADIAL_BOUND_INPUT.csv"))
    extra_rows = read_csv(Path("source-intake/mts_residuals/P8_Y5_EXTRA_MASS_CHANNELWISE_BOUND_INPUT.csv"))
    pg_rows = read_csv(Path("source-intake/mts_residuals/P8_Hamiltonian_charge_Poisson_Gauss_calibration_CONTRACT.csv"))
    sn_rows = read_csv(Path("source-intake/mts_residuals/P8_source_normalized_Newton_branch_STACK.csv"))
    scorecard = read_csv(Path("source-intake/mts_residuals/P8_Y5_SOURCE_NORMALIZATION_RESIDUAL_SCORECARD.csv"))
    src523_0_rows = [row for row in scorecard if row.get("score_id") == "SRC523_0_charge_current_normalization"]
    claim_closure = [row for row in CLOSURE_ATTEMPT_ROWS if row["valid_for_claim"] == "true"]
    claim_fill = [row for row in FIRST_FILL_ROWS if row["valid_for_claim"] == "true"]
    return [
        {
            "check_id": "V532_0_source_paths_exist",
            "result": "pass" if not missing_sources else "fail",
            "detail": f"missing={len(missing_sources)}",
        },
        {
            "check_id": "V532_1_prior_source_current_rows_loaded",
            "result": "pass" if len(ward_rows) >= 7 and len(pim_rows) >= 5 and len(extra_rows) >= 9 else "fail",
            "detail": f"ward_rows={len(ward_rows)};pim_rows={len(pim_rows)};extra_rows={len(extra_rows)}",
        },
        {
            "check_id": "V532_2_PG_and_SN_rows_loaded",
            "result": "pass" if len(pg_rows) >= 11 and len(sn_rows) >= 12 else "fail",
            "detail": f"pg_rows={len(pg_rows)};sn_rows={len(sn_rows)}",
        },
        {
            "check_id": "V532_3_SRC523_0_found",
            "result": "pass" if len(src523_0_rows) == 1 else "fail",
            "detail": f"SRC523_0_rows={len(src523_0_rows)}",
        },
        {
            "check_id": "V532_4_closure_attempt_written",
            "result": "pass" if len(CLOSURE_ATTEMPT_ROWS) == 8 else "fail",
            "detail": f"closure_rows={len(CLOSURE_ATTEMPT_ROWS)}",
        },
        {
            "check_id": "V532_5_first_input_templates_written",
            "result": "pass" if len(EPSILON_CHARGE_TEMPLATE_ROWS) == 3 and len(FIRST_FILL_ROWS) == 3 else "fail",
            "detail": f"template_rows={len(EPSILON_CHARGE_TEMPLATE_ROWS)};first_fill_rows={len(FIRST_FILL_ROWS)}",
        },
        {
            "check_id": "V532_6_no_claim_rows",
            "result": "pass" if not claim_closure and not claim_fill else "fail",
            "detail": f"claim_closure_rows={len(claim_closure)};claim_fill_rows={len(claim_fill)}",
        },
        {
            "check_id": "V532_7_no_overclaim",
            "result": "pass" if not claim_closure and not claim_fill else "fail",
            "detail": "epsilon_charge_filled=false; measured_GM_derived=false; source_normalized_Newton_derived=false; local_GR_claim_allowed=false",
        },
    ]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    full_path = ROOT / path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else []
    with full_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_run_csv(results_dir: Path, filename: str, rows: list[dict[str, Any]]) -> None:
    fieldnames = list(rows[0].keys()) if rows else []
    with (results_dir / filename).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    headers = list(rows[0].keys())
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        values = [str(row.get(header, "")).replace("\n", " ").replace("|", "\\|") for header in headers]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def build_doc(
    generated_at_utc: str,
    run_dir: Path,
    sources: list[dict[str, Any]],
    validations: list[dict[str, str]],
) -> str:
    return f"""# 532 - Y5 Measured-GM Source-Current Closure or First Input Fill

Generated: {generated_at_utc}  
Run: `{rel(run_dir)}`  
Status: `{STATUS}`  
Claim ceiling: `{CLAIM_CEILING}`

## 1. Verdict

This checkpoint attacks the first source-normalized Newton row:

```text
epsilon_charge = (B_xi/G_eff - M_H[Pi_M J_H]) / M_H.
```

The derivation route is now exact. To set `epsilon_charge=0`, the parent action must supply an observed-time Hamiltonian charge, a same-frame Hilbert source current, a parent-owned `Pi_M`, zero projector commutator, zero extra projected mass exchange, and fixed coupling normalization.

Current MTS does not yet satisfy that route. So the first input is not filled; it is made fillable without cheating.

## 2. Closure Theorem Attempt

{markdown_table(CLOSURE_ATTEMPT_ROWS)}

## 3. Epsilon-Charge Residual Decomposition

{markdown_table(RESIDUAL_DECOMPOSITION_ROWS)}

## 4. First Input Template

{markdown_table(EPSILON_CHARGE_TEMPLATE_ROWS)}

## 5. First Fill Status

{markdown_table(FIRST_FILL_ROWS)}

## 6. Decision

{markdown_table(DECISION_ROWS)}

## 7. Source Register

{markdown_table(sources)}

## 8. Validation

{markdown_table(validations)}

## 9. Route Update

{markdown_table(ROUTE_UPDATE_ROWS)}

## 10. Claim Ceiling

Allowed:

```text
The source-current closure theorem target is explicit.
SRC523_0 now has theorem-zero, numeric, and component-envelope input routes.
Current MTS has not filled epsilon_charge.
```

Forbidden:

```text
MTS has derived B_xi/G_eff = M_H[Pi_M J_H].
MTS has filled epsilon_charge.
MTS has derived measured GM, source-normalized Newton, beta, PPN, or local GR.
```

## 11. Practical Read

This is a useful pressure point. We are no longer waving at "the source" as if it is automatically the measured Newtonian mass. The first source row is now a precise theorem-or-data slot. If it closes, the route to Newton gets materially stronger. If it does not, MTS remains honest by carrying an explicit source-charge residual.

## 12. Next Target

`{NEXT_TARGET}`

Next: build the first-row runner or supply a theorem-zero certificate for `epsilon_charge`. Only after this row is filled should we try to promote the downstream Gauss/orbital and beta stages.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timestamp", default=datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S"))
    args = parser.parse_args()

    generated_at_utc = datetime.now(timezone.utc).isoformat()
    run_dir = ROOT / "runs" / f"{args.timestamp}-Y5-measured-GM-source-current-closure-or-first-input-fill"
    results_dir = run_dir / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    sources = source_rows()
    validations = validation_rows(sources)
    csv_outputs: list[tuple[Path, list[dict[str, Any]]]] = [
        (SOURCE_REGISTER_PATH, sources),
        (CLOSURE_ATTEMPT_PATH, CLOSURE_ATTEMPT_ROWS),
        (EPSILON_CHARGE_TEMPLATE_PATH, EPSILON_CHARGE_TEMPLATE_ROWS),
        (FIRST_FILL_PATH, FIRST_FILL_ROWS),
        (RESIDUAL_DECOMPOSITION_PATH, RESIDUAL_DECOMPOSITION_ROWS),
        (DECISION_PATH, DECISION_ROWS),
        (VALIDATION_PATH, validations),
        (ROUTE_UPDATE_PATH, ROUTE_UPDATE_ROWS),
    ]

    for path, rows in csv_outputs:
        write_csv(path, rows)
        write_run_csv(results_dir, path.name, rows)

    doc = build_doc(generated_at_utc, run_dir, sources, validations)
    (ROOT / DOC_PATH).write_text(doc, encoding="utf-8")

    missing_sources = [row["source_file"] for row in sources if row["exists"] is not True]
    failed_validations = [row for row in validations if row["result"] == "fail"]
    status = {
        "timestamp": args.timestamp,
        "generated_at_utc": generated_at_utc,
        "status": STATUS,
        "claim_ceiling": CLAIM_CEILING,
        "checkpoint_doc": str(DOC_PATH),
        "run_dir": str(run_dir),
        "results_dir": str(results_dir),
        "source_register": str(ROOT / SOURCE_REGISTER_PATH),
        "closure_attempt": str(ROOT / CLOSURE_ATTEMPT_PATH),
        "epsilon_charge_template": str(ROOT / EPSILON_CHARGE_TEMPLATE_PATH),
        "first_fill": str(ROOT / FIRST_FILL_PATH),
        "residual_decomposition": str(ROOT / RESIDUAL_DECOMPOSITION_PATH),
        "decision": str(ROOT / DECISION_PATH),
        "validation": str(ROOT / VALIDATION_PATH),
        "route_update": str(ROOT / ROUTE_UPDATE_PATH),
        "source_rows": len(sources),
        "source_paths_missing": len(missing_sources),
        "missing_sources": missing_sources,
        "failed_validation_rows": len(failed_validations),
        "closure_attempt_rows": len(CLOSURE_ATTEMPT_ROWS),
        "epsilon_charge_template_rows": len(EPSILON_CHARGE_TEMPLATE_ROWS),
        "first_fill_rows": len(FIRST_FILL_ROWS),
        "epsilon_charge_filled": False,
        "source_current_closure_derived_for_MTS": False,
        "measured_GM_derived": False,
        "source_normalized_Newton_derived": False,
        "beta_equals_one_derived": False,
        "PPN_promoted": False,
        "local_GR_claim_allowed": False,
        "github_push_performed": False,
        "next_target": NEXT_TARGET,
    }
    (run_dir / "status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    (run_dir / "DONE.txt").write_text(
        "done\nprivate_no_github\nno_measured_GM_Newton_beta_PPN_or_local_GR_promotion\n", encoding="utf-8"
    )

    print(json.dumps(status, indent=2))


if __name__ == "__main__":
    main()
