from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]

STATUS = "Y5_EH_family_mass_parameter_route_written_current_MTS_premises_open_beta_residual_fill_retained"
CLAIM_CEILING = "EH_family_mass_parameter_route_or_beta_residual_fill_only_no_beta_PPN_or_local_GR_pass"
NEXT_TARGET = "529-Y5-source-calibrated-EH-family-proof-stack-or-R11-beta-fill.md"

DOC_PATH = Path("528-Y5-EH-family-mass-parameter-route-or-beta-residual-fill.md")
SOURCE_REGISTER_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_SOURCE_REGISTER.csv")
THEOREM_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_MASS_PARAMETER_THEOREM.csv")
PREMISE_GATE_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_PREMISE_GATES.csv")
AB_EXTRACTION_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_AB_EXTRACTION.csv")
BETA_FILL_QUEUE_PATH = Path("source-intake/mts_residuals/P8_Y5_BETA_RESIDUAL_FILL_QUEUE.csv")
DECISION_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_DECISION.csv")
VALIDATION_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_VALIDATION.csv")
ROUTE_UPDATE_PATH = Path("source-intake/mts_residuals/P8_Y5_EH_FAMILY_ROUTE_UPDATE.csv")


SOURCE_REGISTER = [
    {
        "source_file": "527-Y5-fill-A-B-from-source-equation-or-demote-beta-to-residual.md",
        "role": "selects EH mass-parameter family as the clean beta route",
    },
    {
        "source_file": "526-Y5-beta-coefficient-fill-runner-or-q_loc-U2-bound.md",
        "role": "beta coefficient runner and q_loc U2 provisional bound",
    },
    {
        "source_file": "525-Y5-delta-beta-source-expansion-or-R11-input-fill.md",
        "role": "beta_eff=B/A^2 law",
    },
    {
        "source_file": "523-Y5-Gauss-orbital-calibration-or-source-normalization-residual-score.md",
        "role": "measured-GM and source-normalization calibration chain",
    },
    {
        "source_file": "439-EH-only-exterior-parent-premise-ladder.md",
        "role": "EH-only exterior parent-premise ladder",
    },
    {
        "source_file": "440-metric-only-second-order-sector-reduction-attempt.md",
        "role": "second-order metric-only/R11 reduction attempt",
    },
    {
        "source_file": "450-Hilbert-source-to-measured-monopole-calibration-gate.md",
        "role": "Hilbert source to measured monopole calibration blockers",
    },
    {
        "source_file": "458-Hamiltonian-charge-to-Poisson-Gauss-calibration-gate.md",
        "role": "Poisson/Gauss bridge to measured orbital GM",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_AB_ROUTE_TESTS.csv",
        "role": "527 route tests showing current EH/A-B route does not pass",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_BETA_DEMOTION_RESIDUAL_ROW.csv",
        "role": "527 beta demotion rows",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_GAUSS_ORBITAL_CALIBRATION_CHAIN.csv",
        "role": "523 Gauss/orbital measured-GM chain",
    },
    {
        "source_file": "source-intake/mts_residuals/P8_Y5_SOURCE_NORMALIZATION_RESIDUAL_SCORECARD.csv",
        "role": "523 source-normalization residual scorecard",
    },
    {
        "source_file": "source-intake/mts_residuals/R11_EH_ONLY_OR_EXECUTABLE_VECTOR_GATE.csv",
        "role": "EH-only or executable R11 vector gate",
    },
    {
        "source_file": "source-intake/mts_residuals/R11_EXECUTABLE_VECTOR_STATUS.csv",
        "role": "R11 status rows, currently template-only/no claim",
    },
    {
        "source_file": "source-intake/local_bounds/local_bound_claims.csv",
        "role": "local beta/gamma/PPN bound manifest",
    },
    {
        "source_file": "scripts/Y5_EH_family_mass_parameter_route_or_beta_residual_fill.py",
        "role": "this checkpoint generator",
    },
]


THEOREM_ROWS = [
    {
        "theorem_id": "EH528_0_mass_family_beta_theorem",
        "statement": "If the compact local exterior is the EH Schwarzschild or Schwarzschild-de Sitter family and the PPN readout uses the observed isotropic weak-field coordinate, then beta=1.",
        "math_form": "g00=-1+2 mu/(c^2 rho)-2 mu^2/(c^4 rho^2)+O(c^-6); U=mu/rho => beta_eff=1",
        "requires": "EH-only exterior; static/spherical or equivalent monopole/no-hair theorem; same observed metric/readout; local Lambda/tidal subtraction",
        "current_MTS_status": "conditional_theorem_not_current_MTS_derived",
        "valid_for_claim": "false",
    },
    {
        "theorem_id": "EH528_1_AB_square_from_mass_parameter",
        "statement": "For any first-order source amplitude A, if the nonlinear exterior metric is generated by the same mass parameter mu=A W rho, the quadratic coefficient is B=A^2.",
        "math_form": "g00=-1+2 A W/c^2-2 A^2 W^2/c^4+... so B=A^2 and B/A^2=1",
        "requires": "one mass parameter controls both U and U^2 terms; no extra quadratic source, R11, q_loc, boundary, or readout term",
        "current_MTS_status": "safe_pattern_written_not_matched",
        "valid_for_claim": "false",
    },
    {
        "theorem_id": "EH528_2_measured_mu_lock",
        "statement": "The EH mass parameter must be the measured orbital GM after source calibration, not merely a formal integration constant.",
        "math_form": "mu_EH = mu_obs = G0 M_H and partial_{t,r,A,lambda,frame} mu_obs=0",
        "requires": "523 chain passes; charge-current identity; Gauss surface equality; orbital readout; zero mu_extra; constant G_eff",
        "current_MTS_status": "not_derived_523_scorecard_unfilled",
        "valid_for_claim": "false",
    },
    {
        "theorem_id": "EH528_3_Lambda_tidal_background",
        "statement": "Local Lambda/tidal/background terms must be subtracted or shown not to contaminate the beta U^2 coefficient.",
        "math_form": "g00 includes background terms O(Lambda rho^2) or tidal pieces, which are not beta U^2 and require separate local-background handling",
        "requires": "local background subtraction or bound; no preferred-location xi leakage",
        "current_MTS_status": "background_handling_not_promoted",
        "valid_for_claim": "false",
    },
    {
        "theorem_id": "EH528_4_if_premises_fail",
        "statement": "If the EH mass-family premises fail, beta remains a component residual.",
        "math_form": "Delta_beta_total_abs=|delta_beta_source|+|delta_beta_R11|+|delta_beta_q_loc|+|delta_beta_boundary|+|delta_beta_readout|",
        "requires": "componentwise fill rows and no-cancellation beta envelope",
        "current_MTS_status": "residual_fill_queue_active",
        "valid_for_claim": "false",
    },
]


PREMISE_GATE_ROWS = [
    {
        "gate_id": "EHG528_0_EH_only_exterior",
        "premise": "exterior field equation is EH plus harmless Lambda/background subtraction",
        "evidence_needed": "439 P0-P8 closed or executable R11 vector with all non-EH families zero/below-lock",
        "current_evidence": "439/440 report EH-only and R11 theorem-zero not derived; R11 status template-only",
        "result": "fail_for_current_claim",
        "blocks": "B=A^2;gamma;beta;local_GR",
    },
    {
        "gate_id": "EHG528_1_nohair_mass_family",
        "premise": "compact exterior has a one-parameter monopole mass family",
        "evidence_needed": "Birkhoff/no-hair or equivalent theorem killing scalar/vector/boundary/domain/memory hair",
        "current_evidence": "extra sectors retained and source-normalization channels unfilled",
        "result": "fail_for_current_claim",
        "blocks": "mass_parameter_route",
    },
    {
        "gate_id": "EHG528_2_observed_PPN_readout",
        "premise": "the PPN expansion is in the same observed metric/coframe used by matter, clocks, and orbits",
        "evidence_needed": "same observed coframe/readout theorem through second order",
        "current_evidence": "same-frame/readout residual rows remain retained",
        "result": "fail_for_current_claim",
        "blocks": "beta;gamma;readout",
    },
    {
        "gate_id": "EHG528_3_measured_GM_mu_lock",
        "premise": "EH mass parameter mu equals measured orbital GM",
        "evidence_needed": "523 calibration chain closes and source-normalization scorecard scored",
        "current_evidence": "523 scorecard unfilled; measured_GM_parent_derived=false",
        "result": "fail_for_current_claim",
        "blocks": "Newton;beta;local_GR",
    },
    {
        "gate_id": "EHG528_4_zero_quadratic_leakage",
        "premise": "R11, q_loc, boundary/domain, and readout sectors add no independent U^2 coefficient",
        "evidence_needed": "R11 vector/EH theorem; q_loc Ward-zero or U2 bound; boundary no-flux; readout theorem",
        "current_evidence": "q_loc budget provisional only; R11 template-only; boundary/domain/readout beta rows retained",
        "result": "fail_for_current_claim",
        "blocks": "beta_residual_envelope",
    },
    {
        "gate_id": "EHG528_5_beta_residual_fallback",
        "premise": "if any mass-family gate fails, beta is filled/scored as a residual",
        "evidence_needed": "component rows for source/R11/q_loc/boundary/readout and beta lock comparison",
        "current_evidence": "527 demotion rows written but components unfilled",
        "result": "fallback_active_not_scored",
        "blocks": "PPN_promotion",
    },
]


AB_EXTRACTION_ROWS = [
    {
        "row_id": "ABEH528_0_EH_reference_family",
        "route": "EH_mass_parameter_reference",
        "A_source": "A_mu",
        "B_source": "A_mu^2",
        "beta_eff": "1",
        "delta_beta_source": "0",
        "source_path": "requires_EH_mass_family_proof_not_reference_row",
        "current_status": "reference_theorem_only",
        "valid_for_claim": "false",
    },
    {
        "row_id": "ABEH528_1_current_MTS",
        "route": "current_MTS_after_527",
        "A_source": "MISSING_A_SOURCE",
        "B_source": "MISSING_B_SOURCE",
        "beta_eff": "",
        "delta_beta_source": "retained",
        "source_path": "no_second_order_source_equation_or_EH_family_proof_loaded",
        "current_status": "not_evaluable",
        "valid_for_claim": "false",
    },
    {
        "row_id": "ABEH528_2_residual_branch",
        "route": "beta_component_residual_fill",
        "A_source": "fill_or_derive",
        "B_source": "fill_or_derive",
        "beta_eff": "B/A^2 after fill",
        "delta_beta_source": "B/A^2-1",
        "source_path": "P8_Y5_BETA_DEMOTION_RESIDUAL_ROW.csv",
        "current_status": "fallback_active_unfilled",
        "valid_for_claim": "false",
    },
]


BETA_FILL_QUEUE_ROWS = [
    {
        "queue_id": "BFQ528_0_source_AB",
        "component": "delta_beta_source",
        "required_fill": "A_source;B_source;source equation or EH mass-family proof",
        "current_status": "missing",
        "priority": "highest",
    },
    {
        "queue_id": "BFQ528_1_R11_beta",
        "component": "delta_beta_R11",
        "required_fill": "EH-only theorem-zero or executable R11 beta coefficient vector",
        "current_status": "template_only",
        "priority": "high",
    },
    {
        "queue_id": "BFQ528_2_q_loc_U2",
        "component": "delta_beta_q_loc",
        "required_fill": "Ward-zero through O(U2) or physical beta-normalized q_loc profile/conversion",
        "current_status": "provisional_budget_only",
        "priority": "high",
    },
    {
        "queue_id": "BFQ528_3_boundary_domain",
        "component": "delta_beta_boundary_domain",
        "required_fill": "boundary/domain/projector no-flux theorem or coefficient map",
        "current_status": "unfilled",
        "priority": "high",
    },
    {
        "queue_id": "BFQ528_4_readout",
        "component": "delta_beta_readout",
        "required_fill": "same observed metric/coframe/readout theorem through O(U2)",
        "current_status": "unfilled",
        "priority": "high",
    },
    {
        "queue_id": "BFQ528_5_total_envelope",
        "component": "Delta_beta_total_abs",
        "required_fill": "all components filled/theorem-zero and no-cancellation sum below beta lock",
        "current_status": "not_run",
        "priority": "gate",
    },
]


DECISION_ROWS = [
    {
        "decision_id": "D528_0_EH_family_theorem_written",
        "status": "conditional_theorem_written",
        "meaning": "an EH Schwarzschild-family exterior with measured mass parameter derives B=A^2 and beta=1",
        "claim_status": "not_current_MTS_derived",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D528_1_current_premises_fail_open",
        "status": "EH_R11_measured_GM_q_loc_gates_open",
        "meaning": "current MTS does not yet prove EH-only exterior, measured mu lock, no quadratic leakage, or same-readout PPN family",
        "claim_status": "beta_residual_retained",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D528_2_reference_rows_not_evidence",
        "status": "reference_family_no_claim",
        "meaning": "the EH reference row explains the target but is not counted as current MTS evidence",
        "claim_status": "overclaim_blocked",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D528_3_fill_queue_active",
        "status": "beta_fill_queue_written",
        "meaning": "if the EH family route does not land, beta must be filled component-by-component and compared to the beta lock",
        "claim_status": "no_PPN_or_local_GR_claim",
        "next_action": NEXT_TARGET,
    },
    {
        "decision_id": "D528_4_private_no_push",
        "status": "private_no_github_no_promotion",
        "meaning": "this is private framework work and nothing is pushed",
        "claim_status": "safe_private_work",
        "next_action": "continue_private_derivation",
    },
]


ROUTE_UPDATE_ROWS = [
    {
        "route_id": "EH_MASS_PARAMETER_ROUTE",
        "previous_status": "identified_as_cleanest_path_to_B_equals_A_squared",
        "new_status": "conditional_theorem_written_current_premises_open",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "BETA_DEMOTION",
        "previous_status": "explicit_component_residual_rows_active",
        "new_status": "fill_queue_written_source_R11_q_loc_boundary_readout_components_unfilled",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "SOURCE_NORMALIZED_NEWTON",
        "previous_status": "523_scorecard_unfilled",
        "new_status": "still_required_to_identify_EH_mass_parameter_with_measured_GM",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "R11_EH_OPERATOR",
        "previous_status": "R11_template_only_blocks_beta_claim",
        "new_status": "must_be_EH_only_or_executable_before_mass_family_route_can_claim",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
    {
        "route_id": "LOCAL_GR",
        "previous_status": "still_blocked_beta_demoted_to_residual_and_EH_mass_family_not_derived",
        "new_status": "still_blocked_mass_family_premises_open_and_beta_fill_queue_unscored",
        "accepted_for_claim": "false",
        "next_target": NEXT_TARGET,
    },
]


def rel(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT)).replace("\\", "/")
    except ValueError:
        return str(path)


def read_csv(path: Path) -> list[dict[str, str]]:
    full_path = ROOT / path
    if not full_path.exists():
        return []
    with full_path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def source_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for item in SOURCE_REGISTER:
        full_path = ROOT / item["source_file"]
        rows.append({**item, "exists": full_path.exists()})
    return rows


def validation_rows(sources: list[dict[str, Any]]) -> list[dict[str, str]]:
    missing_sources = [row["source_file"] for row in sources if row["exists"] is not True]
    ab_tests = read_csv(Path("source-intake/mts_residuals/P8_Y5_AB_ROUTE_TESTS.csv"))
    demotion_rows = read_csv(Path("source-intake/mts_residuals/P8_Y5_BETA_DEMOTION_RESIDUAL_ROW.csv"))
    r11_status = read_csv(Path("source-intake/mts_residuals/R11_EXECUTABLE_VECTOR_STATUS.csv"))
    gauss_score = read_csv(Path("source-intake/mts_residuals/P8_Y5_SOURCE_NORMALIZATION_RESIDUAL_SCORECARD.csv"))
    claim_rows = [
        *[row for row in THEOREM_ROWS if row["valid_for_claim"] == "true"],
        *[row for row in AB_EXTRACTION_ROWS if row["valid_for_claim"] == "true"],
    ]
    current_pass_gates = [row for row in PREMISE_GATE_ROWS if row["result"] == "pass_for_current_claim"]
    return [
        {
            "check_id": "V528_0_source_paths_exist",
            "result": "pass" if not missing_sources else "fail",
            "detail": f"missing={len(missing_sources)}",
        },
        {
            "check_id": "V528_1_prior_527_rows_loaded",
            "result": "pass" if len(ab_tests) >= 6 and len(demotion_rows) >= 6 else "fail",
            "detail": f"ab_route_tests={len(ab_tests)};beta_demotion_rows={len(demotion_rows)}",
        },
        {
            "check_id": "V528_2_R11_and_523_status_loaded",
            "result": "pass" if len(r11_status) >= 10 and len(gauss_score) >= 12 else "fail",
            "detail": f"r11_status_rows={len(r11_status)};gauss_score_rows={len(gauss_score)}",
        },
        {
            "check_id": "V528_3_theorem_and_premise_gates_written",
            "result": "pass" if len(THEOREM_ROWS) == 5 and len(PREMISE_GATE_ROWS) == 6 else "fail",
            "detail": f"theorem_rows={len(THEOREM_ROWS)};premise_gates={len(PREMISE_GATE_ROWS)}",
        },
        {
            "check_id": "V528_4_fill_queue_written",
            "result": "pass" if len(BETA_FILL_QUEUE_ROWS) == 6 else "fail",
            "detail": f"fill_queue_rows={len(BETA_FILL_QUEUE_ROWS)}",
        },
        {
            "check_id": "V528_5_current_premises_do_not_pass",
            "result": "pass" if not current_pass_gates else "fail",
            "detail": f"pass_for_current_claim_gates={len(current_pass_gates)}",
        },
        {
            "check_id": "V528_6_no_overclaim",
            "result": "pass" if not claim_rows else "fail",
            "detail": "EH_mass_family_derived_for_MTS=false; B_equals_A_squared_derived=false; beta_equals_one_derived=false; local_GR_claim_allowed=false",
        },
    ]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    full_path = ROOT / path
    full_path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else []
    with full_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_run_csv(results_dir: Path, filename: str, rows: list[dict[str, Any]]) -> None:
    fieldnames = list(rows[0].keys()) if rows else []
    with (results_dir / filename).open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def markdown_table(rows: list[dict[str, Any]]) -> str:
    if not rows:
        return ""
    headers = list(rows[0].keys())
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        values = [str(row.get(header, "")).replace("\n", " ").replace("|", "\\|") for header in headers]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def build_doc(
    generated_at_utc: str,
    run_dir: Path,
    sources: list[dict[str, Any]],
    validations: list[dict[str, str]],
) -> str:
    return f"""# 528 - Y5 EH Family Mass-Parameter Route or Beta Residual Fill

Generated: {generated_at_utc}  
Run: `{rel(run_dir)}`  
Status: `{STATUS}`  
Claim ceiling: `{CLAIM_CEILING}`

## 1. Verdict

The clean beta route is real:

```text
EH exterior + one measured mass parameter mu
=> g00 = -1 + 2U/c^2 - 2U^2/c^4 + ...
=> B = A^2
=> beta = 1.
```

But current MTS has not yet earned the route. EH-only exterior, measured `mu=GM`, R11 silence, q_loc U2 silence, boundary/domain silence, and same-readout PPN expansion are all still open.

So this checkpoint records the theorem target and keeps the beta residual fill queue active.

## 2. EH Mass-Parameter Theorem

{markdown_table(THEOREM_ROWS)}

## 3. Premise Gates

{markdown_table(PREMISE_GATE_ROWS)}

## 4. A/B Extraction

{markdown_table(AB_EXTRACTION_ROWS)}

## 5. Beta Fill Queue

{markdown_table(BETA_FILL_QUEUE_ROWS)}

## 6. Decision

{markdown_table(DECISION_ROWS)}

## 7. Source Register

{markdown_table(sources)}

## 8. Validation

{markdown_table(validations)}

## 9. Route Update

{markdown_table(ROUTE_UPDATE_ROWS)}

## 10. Claim Ceiling

Allowed:

```text
The EH mass-parameter route to beta=1 is explicit and mathematically clean.
The current MTS branch has not yet satisfied the route.
The beta fill queue remains active.
```

Forbidden:

```text
MTS has derived EH-only local exterior.
MTS has shown the EH mass parameter equals measured orbital GM.
MTS has derived B=A^2, beta=1, PPN, or local GR.
```

## 11. Next Target

`{NEXT_TARGET}`

Next, either build the source-calibrated EH family proof stack rung-by-rung, or fill the beta residual components. That is the fork now.
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--timestamp", default=datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S"))
    args = parser.parse_args()

    generated_at_utc = datetime.now(timezone.utc).isoformat()
    run_dir = ROOT / "runs" / f"{args.timestamp}-Y5-EH-family-mass-parameter-route-or-beta-residual-fill"
    results_dir = run_dir / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    sources = source_rows()
    validations = validation_rows(sources)
    csv_outputs: list[tuple[Path, list[dict[str, Any]]]] = [
        (SOURCE_REGISTER_PATH, sources),
        (THEOREM_PATH, THEOREM_ROWS),
        (PREMISE_GATE_PATH, PREMISE_GATE_ROWS),
        (AB_EXTRACTION_PATH, AB_EXTRACTION_ROWS),
        (BETA_FILL_QUEUE_PATH, BETA_FILL_QUEUE_ROWS),
        (DECISION_PATH, DECISION_ROWS),
        (VALIDATION_PATH, validations),
        (ROUTE_UPDATE_PATH, ROUTE_UPDATE_ROWS),
    ]

    for path, rows in csv_outputs:
        write_csv(path, rows)
        write_run_csv(results_dir, path.name, rows)

    doc = build_doc(generated_at_utc, run_dir, sources, validations)
    (ROOT / DOC_PATH).write_text(doc, encoding="utf-8")

    missing_sources = [row["source_file"] for row in sources if row["exists"] is not True]
    failed_validations = [row for row in validations if row["result"] == "fail"]
    status = {
        "timestamp": args.timestamp,
        "generated_at_utc": generated_at_utc,
        "status": STATUS,
        "claim_ceiling": CLAIM_CEILING,
        "checkpoint_doc": str(DOC_PATH),
        "run_dir": str(run_dir),
        "results_dir": str(results_dir),
        "source_register": str(ROOT / SOURCE_REGISTER_PATH),
        "theorem": str(ROOT / THEOREM_PATH),
        "premise_gates": str(ROOT / PREMISE_GATE_PATH),
        "ab_extraction": str(ROOT / AB_EXTRACTION_PATH),
        "beta_fill_queue": str(ROOT / BETA_FILL_QUEUE_PATH),
        "decision": str(ROOT / DECISION_PATH),
        "validation": str(ROOT / VALIDATION_PATH),
        "route_update": str(ROOT / ROUTE_UPDATE_PATH),
        "source_rows": len(sources),
        "source_paths_missing": len(missing_sources),
        "missing_sources": missing_sources,
        "theorem_rows": len(THEOREM_ROWS),
        "premise_gate_rows": len(PREMISE_GATE_ROWS),
        "ab_extraction_rows": len(AB_EXTRACTION_ROWS),
        "beta_fill_queue_rows": len(BETA_FILL_QUEUE_ROWS),
        "failed_validation_rows": len(failed_validations),
        "EH_mass_parameter_route_written": True,
        "EH_mass_family_derived_for_MTS": False,
        "measured_mu_equals_GM_derived": False,
        "B_equals_A_squared_derived_for_MTS": False,
        "beta_fill_queue_active": True,
        "beta_equals_one_derived": False,
        "PPN_promoted": False,
        "local_GR_claim_allowed": False,
        "github_push_performed": False,
        "next_target": NEXT_TARGET,
    }
    (run_dir / "status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    print(json.dumps(status, indent=2))


if __name__ == "__main__":
    main()
