from __future__ import annotations

import csv
import math
from datetime import datetime, timezone
from pathlib import Path


RUN_STARTED = datetime.now(timezone.utc)
RUN_STARTED_TS = RUN_STARTED.timestamp()

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parent
FW = REPO / "formalization-workbench"
OUT = ROOT / "source-intake" / "mts_residuals"

INPUTS = OUT / "P8_Y5_R2FR_3195_INPUTS.csv"
FINITE_LAYER = OUT / "P8_Y5_R2FR_3195_FINITE_LAYER_DERIVATION.csv"
SCALING_RUNNER = OUT / "P8_Y5_R2FR_3195_COMPLIANCE_SCALING_RUNNER.csv"
PARENT_GATES = OUT / "P8_Y5_R2FR_3195_PARENT_SIGNATURE_GATE.csv"
CLASSIFICATION = OUT / "P8_Y5_R2FR_3195_ROUTE_CLASSIFICATION.csv"
DECISION = OUT / "P8_Y5_R2FR_3195_DECISION.csv"
VALIDATION = OUT / "P8_Y5_R2FR_3195_VALIDATION.csv"

MULTIPLIERS_3194 = OUT / "P8_Y5_R2FR_3194_MULTIPLIER_SOLUTIONS.csv"
CLASSIFICATION_3194 = OUT / "P8_Y5_R2FR_3194_CLOSURE_CLASSIFICATION.csv"
VALIDATION_3194 = OUT / "P8_Y5_R2FR_3194_VALIDATION.csv"


def stamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError(f"no rows for {path}")
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def resolve(base: str, relative: str) -> Path:
    if base == "post_checkpoint":
        return ROOT / relative
    if base == "formalization":
        return FW / relative
    raise ValueError(base)


def input_rows() -> list[dict[str, object]]:
    now = stamp()
    rows = [
        (
            "post_checkpoint",
            "3194-Y5-R2FR-source-owned-boundary-layer-action-or-modified-parent-profile-functional-under-AX1090.md",
            "3194 gluing multiplier action and classification",
        ),
        (
            "post_checkpoint",
            "source-intake/mts_residuals/P8_Y5_R2FR_3194_MULTIPLIER_SOLUTIONS.csv",
            "3194 solved multiplier rows",
        ),
        (
            "post_checkpoint",
            "source-intake/mts_residuals/P8_Y5_R2FR_3194_CLOSURE_CLASSIFICATION.csv",
            "3194 route classification",
        ),
        (
            "post_checkpoint",
            "source-intake/mts_residuals/P8_Y5_R2FR_3194_VALIDATION.csv",
            "3194 validation evidence",
        ),
        (
            "formalization",
            "83-parent-equations-v1.md",
            "current parent equation scaffold",
        ),
    ]
    return [
        {
            "input_id": f"IN3195_{index}",
            "base": base,
            "path": str(resolve(base, relative).resolve()),
            "exists": str(resolve(base, relative).exists()).lower(),
            "role": role,
            "valid_for_claim": "false",
            "generated_utc": now,
        }
        for index, (base, relative, role) in enumerate(rows)
    ]


def finite_layer_derivation_rows() -> list[dict[str, object]]:
    now = stamp()
    rows = [
        {
            "derivation_id": "FL3195_0_layer_coordinate",
            "statement": "Replace the sharp interface by a thin layer of thickness delta carrying the C1 mismatch variables.",
            "formula": "z=(Delta F, Delta F')",
            "status": "FINITE_LAYER_SETUP",
        },
        {
            "derivation_id": "FL3195_1_elastic_layer_energy",
            "statement": "A positive layer stiffness matrix K gives an effective mismatch energy after integrating through the layer.",
            "formula": "S_layer=(1/(2 delta)) z^T K z",
            "status": "DERIVED_EFFECTIVE_LAYER_FORM",
        },
        {
            "derivation_id": "FL3195_2_layer_force",
            "statement": "The conjugate interface force generated by the layer is the derivative with respect to the mismatch.",
            "formula": "lambda = dS_layer/dz = (K/delta) z",
            "status": "DERIVED",
        },
        {
            "derivation_id": "FL3195_3_compliance",
            "statement": "Define the compliance matrix C_delta=delta K^-1.",
            "formula": "z = C_delta lambda",
            "status": "DERIVED",
        },
        {
            "derivation_id": "FL3195_4_hard_constraint_limit",
            "statement": "If K remains positive and delta -> 0, z -> 0 while lambda can remain finite.",
            "formula": "z=delta K^-1 lambda -> 0, lambda finite",
            "status": "HARD_C1_LIMIT_DERIVED",
        },
        {
            "derivation_id": "FL3195_5_energy_scaling",
            "statement": "The stored layer energy vanishes for finite lambda in the hard-constraint limit.",
            "formula": "S_layer=(1/2) lambda^T C_delta lambda -> 0",
            "status": "FINITE_REACTION_ZERO_THICKNESS_ENERGY_LIMIT",
        },
        {
            "derivation_id": "FL3195_6_relation_to_3194",
            "statement": "The 3194 gluing multipliers are recovered as finite reaction forces of the vanishing layer.",
            "formula": "lambda_i=-[Pi_i]=lim_{delta->0}(K/delta z)_i",
            "status": "GLUING_MULTIPLIER_AS_FINITE_LAYER_LIMIT",
        },
        {
            "derivation_id": "FL3195_7_parent_gate",
            "statement": "This is not yet parent-signed: MTS must derive K, delta scaling, localization, and coupling universality.",
            "formula": "S_parent -> S_bulk + lim_delta S_layer",
            "status": "PARENT_SIGNATURE_REQUIRED",
        },
    ]
    return [{**row, "valid_for_claim": "false", "generated_utc": now} for row in rows]


def multiplier_values(row: dict[str, str]) -> dict[str, float]:
    return {
        "left_Pi1": float(row["lambda_left_Pi1"]),
        "left_Pi0": float(row["lambda_left_Pi0"]),
        "right_Pi1": float(row["lambda_right_Pi1"]),
        "right_Pi0": float(row["lambda_right_Pi0"]),
    }


def scaling_runner_rows() -> list[dict[str, object]]:
    now = stamp()
    rows: list[dict[str, object]] = []
    epsilons = [1.0e-1, 1.0e-3, 1.0e-6, 1.0e-9, 1.0e-12]
    for multiplier in read_csv(MULTIPLIERS_3194):
        lambdas = multiplier_values(multiplier)
        lambda_norm = math.sqrt(sum(value * value for value in lambdas.values()))
        for epsilon in epsilons:
            mismatches = {name: epsilon * value for name, value in lambdas.items()}
            recovered = {name: mismatches[name] / epsilon for name in lambdas}
            residuals = {name: recovered[name] - lambdas[name] for name in lambdas}
            mismatch_norm = epsilon * lambda_norm
            energy = 0.5 * epsilon * lambda_norm**2
            rows.append(
                {
                    "run_id": f"FL3195_{multiplier['solution_id']}_eps{epsilon:.0e}",
                    "source_solution": multiplier["solution_id"],
                    "source_selection": multiplier["source_selection"],
                    "transition_width": multiplier["transition_width"],
                    "epsilon_compliance": f"{epsilon:.15e}",
                    "lambda_norm": f"{lambda_norm:.15e}",
                    "mismatch_left_Pi1_slot": f"{mismatches['left_Pi1']:.15e}",
                    "mismatch_left_Pi0_slot": f"{mismatches['left_Pi0']:.15e}",
                    "mismatch_right_Pi1_slot": f"{mismatches['right_Pi1']:.15e}",
                    "mismatch_right_Pi0_slot": f"{mismatches['right_Pi0']:.15e}",
                    "mismatch_norm": f"{mismatch_norm:.15e}",
                    "layer_energy_proxy": f"{energy:.15e}",
                    "recovered_lambda_left_Pi1": f"{recovered['left_Pi1']:.15e}",
                    "recovered_lambda_left_Pi0": f"{recovered['left_Pi0']:.15e}",
                    "recovered_lambda_right_Pi1": f"{recovered['right_Pi1']:.15e}",
                    "recovered_lambda_right_Pi0": f"{recovered['right_Pi0']:.15e}",
                    "max_abs_recovery_residual": f"{max(abs(value) for value in residuals.values()):.15e}",
                    "limit_status": "FINITE_FORCE_WITH_VANISHING_MISMATCH_AND_ENERGY",
                    "source_status": "FINITE_LAYER_LIMIT_NOT_PARENT_SIGNED",
                    "valid_for_claim": "false",
                    "generated_utc": now,
                }
            )
    return rows


def parent_signature_gate_rows() -> list[dict[str, object]]:
    now = stamp()
    rows = [
        {
            "gate_id": "GATE3195_0_layer_degrees",
            "requirement": "Identify parent MTS degrees of freedom that live in or generate the finite interface layer.",
            "current_evidence": "No parent-owned layer variable or auxiliary edge field has been extracted yet.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
        {
            "gate_id": "GATE3195_1_positive_stiffness",
            "requirement": "Derive a positive stiffness/compliance matrix K for z=(Delta F, Delta F').",
            "current_evidence": "3195 uses K>0 as the finite-layer ansatz condition.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
        {
            "gate_id": "GATE3195_2_hard_constraint_scaling",
            "requirement": "Derive the scaling C_delta=delta K^-1 -> 0 while lambda remains finite.",
            "current_evidence": "Scaling is mathematically consistent but not yet derived from MTS source dynamics.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
        {
            "gate_id": "GATE3195_3_covariant_localization",
            "requirement": "Express the layer measure and interface localization covariantly, not only in the radial profile coordinate x.",
            "current_evidence": "Current derivation is radial-profile level.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
        {
            "gate_id": "GATE3195_4_width_selection",
            "requirement": "Derive the selected transition width/profile from the parent action or a finite-layer variational principle.",
            "current_evidence": "3194/3195 keep several candidate widths; none is parent-selected.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
        {
            "gate_id": "GATE3195_5_observable_residuals",
            "requirement": "Show finite-layer remnants do not violate PPN, clock, WEP, orbital, or R10/local-G constraints.",
            "current_evidence": "No observational transfer calculation has been performed for the finite-layer route.",
            "status": "OPEN",
            "blocks_claim": "true",
        },
    ]
    return [{**row, "valid_for_claim": "false", "generated_utc": now} for row in rows]


def classification_rows(scaling_rows: list[dict[str, object]]) -> list[dict[str, object]]:
    now = stamp()
    reference_smallest = min(
        (row for row in scaling_rows if row["source_solution"] == "GLUE3194_0_3190_width"),
        key=lambda row: float(row["epsilon_compliance"]),
    )
    balanced_smallest = min(
        (row for row in scaling_rows if row["source_solution"] == "GLUE3194_1_balanced_Fpp_jump"),
        key=lambda row: float(row["epsilon_compliance"]),
    )
    return [
        {
            "classification_id": "CLASS3195_0_multiplier_origin",
            "finding": "The 3194 C1 gluing multipliers can be represented as the hard-constraint limit of a finite positive layer.",
            "math_status": "FINITE_LAYER_LIMIT_CONSTRUCTED",
            "physics_status": "PARENT_ORIGIN_NOT_YET_PROVEN",
            "next_requirement": "derive the layer degrees and stiffness from the parent MTS action",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "classification_id": "CLASS3195_1_reference_scaling",
            "finding": f"For the reference-width row at epsilon={reference_smallest['epsilon_compliance']}, mismatch_norm={reference_smallest['mismatch_norm']} and layer_energy_proxy={reference_smallest['layer_energy_proxy']}.",
            "math_status": "FORCE_RECOVERY_EXACT",
            "physics_status": "HARD_CONSTRAINT_LIMIT_ONLY",
            "next_requirement": "source the epsilon/compliance scaling",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "classification_id": "CLASS3195_2_balanced_scaling",
            "finding": f"For the balanced row at epsilon={balanced_smallest['epsilon_compliance']}, mismatch_norm={balanced_smallest['mismatch_norm']} and layer_energy_proxy={balanced_smallest['layer_energy_proxy']}.",
            "math_status": "FORCE_RECOVERY_EXACT",
            "physics_status": "WIDTH_SELECTION_NOT_PARENT_DERIVED",
            "next_requirement": "derive profile/width selection and finite-layer regularity weights",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "classification_id": "CLASS3195_3_claim_status",
            "finding": "This removes the objection that gluing multipliers are purely arbitrary, but it does not yet make them MTS-derived.",
            "math_status": "MECHANISM_PLAUSIBLE",
            "physics_status": "LOCAL_GR_STILL_BLOCKED",
            "next_requirement": "parent-signature gates must close before PPN/local-G claims",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
    ]


def decision_rows() -> list[dict[str, object]]:
    now = stamp()
    return [
        {
            "decision_id": "DEC3195_0_finite_layer_limit",
            "finding": "Constructed a finite-layer/hard-constraint limit in which C1 gluing multipliers arise as finite reaction forces with vanishing mismatch.",
            "claim_status": "FINITE_LAYER_MECHANISM_CONSTRUCTED_NONCLAIM",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "decision_id": "DEC3195_1_parent_signature",
            "finding": "The mechanism is mathematically coherent but parent ownership is still open: MTS must derive layer variables, positive stiffness, scaling, covariance, and observable residual suppression.",
            "claim_status": "PARENT_SIGNATURE_REQUIRED",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "decision_id": "DEC3195_2_best_route",
            "finding": "Best current route is to search the parent action for an auxiliary edge/layer field whose elimination produces the compliance matrix.",
            "claim_status": "AUXILIARY_LAYER_FIELD_ROUTE_SELECTED",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
        {
            "decision_id": "DEC3195_3_next_target",
            "finding": "3196-Y5-R2FR-auxiliary-layer-field-elimination-or-parent-compliance-matrix-under-AX1090",
            "claim_status": "NEXT_TARGET",
            "valid_for_claim": "false",
            "generated_utc": now,
        },
    ]


def formalization_recent_file_count() -> int:
    if not FW.exists():
        return -1
    count = 0
    for path in FW.rglob("*"):
        if path.is_file() and path.stat().st_mtime >= RUN_STARTED_TS:
            count += 1
    return count


def validation_rows(rows_by_path: dict[Path, list[dict[str, object]]]) -> list[dict[str, object]]:
    now = stamp()
    inputs = rows_by_path[INPUTS]
    finite_layer = rows_by_path[FINITE_LAYER]
    scaling = rows_by_path[SCALING_RUNNER]
    gates = rows_by_path[PARENT_GATES]
    decisions = rows_by_path[DECISION]
    all_rows = [row for rows in rows_by_path.values() for row in rows]
    recent_fw = formalization_recent_file_count()
    max_recovery = max(float(row["max_abs_recovery_residual"]) for row in scaling)
    reference_rows = [
        row for row in scaling
        if row["source_solution"] == "GLUE3194_0_3190_width"
    ]
    reference_sorted = sorted(reference_rows, key=lambda row: float(row["epsilon_compliance"]), reverse=True)
    mismatch_decreases = all(
        float(reference_sorted[index]["mismatch_norm"]) > float(reference_sorted[index + 1]["mismatch_norm"])
        for index in range(len(reference_sorted) - 1)
    )
    energy_decreases = all(
        float(reference_sorted[index]["layer_energy_proxy"]) > float(reference_sorted[index + 1]["layer_energy_proxy"])
        for index in range(len(reference_sorted) - 1)
    )
    return [
        {
            "check_id": "VAL3195_0_inputs_exist",
            "check": "all cited input paths exist",
            "pass": str(all(row["exists"] == "true" for row in inputs)).lower(),
            "detail": "; ".join(row["input_id"] for row in inputs if row["exists"] != "true") or "all inputs resolved",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_1_finite_layer_derivation_present",
            "check": "finite-layer derivation includes hard limit, energy scaling, and relation to 3194 multipliers",
            "pass": str(
                any(row["status"] == "HARD_C1_LIMIT_DERIVED" for row in finite_layer)
                and any(row["status"] == "FINITE_REACTION_ZERO_THICKNESS_ENERGY_LIMIT" for row in finite_layer)
                and any(row["status"] == "GLUING_MULTIPLIER_AS_FINITE_LAYER_LIMIT" for row in finite_layer)
            ).lower(),
            "detail": "z=delta K^-1 lambda; S_layer=(1/2)lambda^T C_delta lambda",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_2_scaling_shape",
            "check": "scaling runner covers three multiplier solutions and five compliance values",
            "pass": str(len(scaling) == 15).lower(),
            "detail": f"scaling_rows={len(scaling)}",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_3_force_recovery",
            "check": "compliance mismatch recovers all target multipliers",
            "pass": str(max_recovery < 1.0e-12).lower(),
            "detail": f"max_abs_recovery_residual={max_recovery:.15e}",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_4_hard_constraint_limit",
            "check": "reference row mismatch norm and energy proxy decrease as compliance decreases",
            "pass": str(mismatch_decreases and energy_decreases).lower(),
            "detail": "reference finite-force limit behaves monotonically",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_5_parent_gates_open",
            "check": "parent signature gates remain explicit blockers",
            "pass": str(len(gates) == 6 and all(row["status"] == "OPEN" and row["blocks_claim"] == "true" for row in gates)).lower(),
            "detail": f"open_parent_gates={len(gates)}",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_6_next_target_selected",
            "check": "decision selects auxiliary layer field elimination or parent compliance matrix",
            "pass": str(any("3196-Y5-R2FR-auxiliary-layer-field" in row["finding"] for row in decisions)).lower(),
            "detail": "next target is 3196",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_7_no_claim_leak",
            "check": "no generated row sets valid_for_claim=true",
            "pass": str(not any(str(row.get("valid_for_claim", "")).lower() == "true" for row in all_rows)).lower(),
            "detail": "all rows are private/nonclaim",
            "generated_utc": now,
        },
        {
            "check_id": "VAL3195_8_formalization_workbench_untouched",
            "check": "formalization-workbench files modified during this run remain zero",
            "pass": str(recent_fw == 0).lower(),
            "detail": f"formalization_recent_file_count={recent_fw}",
            "generated_utc": now,
        },
    ]


def all_output_rows() -> dict[Path, list[dict[str, object]]]:
    inputs = input_rows()
    finite_layer = finite_layer_derivation_rows()
    scaling = scaling_runner_rows()
    gates = parent_signature_gate_rows()
    classification = classification_rows(scaling)
    decisions = decision_rows()
    return {
        INPUTS: inputs,
        FINITE_LAYER: finite_layer,
        SCALING_RUNNER: scaling,
        PARENT_GATES: gates,
        CLASSIFICATION: classification,
        DECISION: decisions,
    }


def main() -> None:
    rows_by_path = all_output_rows()
    rows_by_path[VALIDATION] = validation_rows(rows_by_path)
    for path, rows in rows_by_path.items():
        write_csv(path, rows)
    for path in rows_by_path:
        print(path)


if __name__ == "__main__":
    main()
