import csv
import math
import shutil
from datetime import datetime, timezone
from pathlib import Path


CHECKPOINT = "3757"
BRANCH = "MTS_R2FR_Y5_FIRST_COUPLING_RUNNER_FILL_OR_SIDE_FLUX_ZERO_PROOF_3757"
PCW = Path(
    r"D:\Users\ollet\Desktop\Turn an intuitive research programme into a formal field-theoretic framework\Motion-TimeSpace--main\post-checkpoint-work"
)
RESIDUALS = PCW / "source-intake" / "mts_residuals"
FORMALIZATION = (
    PCW.parent / "formalization-workbench"
)
DOC_PATH = PCW / "3757-Y5-R2FR-first-coupling-runner-fill-or-side-flux-zero-proof.md"


OUTPUTS = {
    "sources": RESIDUALS / "P8_Y5_R2FR_3757_SOURCE_REGISTER.csv",
    "side_flux": RESIDUALS / "P8_Y5_R2FR_3757_SIDE_FLUX_ZERO_THEOREM.csv",
    "gdot_fill": RESIDUALS / "P8_Y5_R2FR_3757_GDOT_CONDITIONAL_FILL.csv",
    "runner_patch": RESIDUALS / "P8_Y5_R2FR_3757_COUPLING_RUNNER_PATCH.csv",
    "parent_premises": RESIDUALS / "P8_Y5_R2FR_3757_PARENT_PREMISE_SIGNATURES.csv",
    "claim_gates": RESIDUALS / "P8_Y5_R2FR_3757_CLAIM_GATES.csv",
    "decision_rows": RESIDUALS / "P8_Y5_R2FR_3757_DECISION_ROWS.csv",
    "next_target": RESIDUALS / "P8_Y5_R2FR_3757_NEXT_TARGET.csv",
    "status": RESIDUALS / "P8_Y5_R2FR_3757_STATUS.csv",
    "validation": RESIDUALS / "P8_Y5_BRR545_3757_VALIDATION.csv",
}


def stamp() -> str:
    return datetime.now(timezone.utc).isoformat()


def base(timestamp: str, valid_for_claim: bool = False) -> dict[str, object]:
    return {
        "timestamp_utc": timestamp,
        "branch_id": BRANCH,
        "checkpoint_id": CHECKPOINT,
        "valid_for_claim": valid_for_claim,
    }


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError(f"refusing to write empty csv: {path}")
    fields: list[str] = []
    for row in rows:
        for key in row:
            if key not in fields:
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def source_paths() -> dict[str, Path]:
    return {
        "SRC3757_0_3756_doc": PCW / "3756-Y5-R2FR-no-flux-projected-exchange-or-coupling-runner.md",
        "SRC3757_1_3756_no_flux": RESIDUALS / "P8_Y5_R2FR_3756_NO_FLUX_THEOREM_CLAUSES.csv",
        "SRC3757_2_3756_exchange": RESIDUALS / "P8_Y5_R2FR_3756_PROJECTED_EXCHANGE_CLAUSES.csv",
        "SRC3757_3_3756_runner": RESIDUALS / "P8_Y5_R2FR_3756_COUPLING_RUNNER_DRYRUN_RESULTS.csv",
        "SRC3757_4_3756_gates": RESIDUALS / "P8_Y5_R2FR_3756_CLAIM_GATES.csv",
        "SRC3757_5_3755_kappa_rows": RESIDUALS / "P8_Y5_R2FR_3755_KAPPA_THEOREM_ROWS.csv",
        "SRC3757_6_3755_residual_vector": RESIDUALS / "P8_Y5_R2FR_3755_COUPLING_RESIDUAL_VECTOR.csv",
        "SRC3757_7_3754_flux_law": RESIDUALS / "P8_Y5_R2FR_3754_SOURCE_WARD_FLUX_LAW_ROWS.csv",
        "SRC3757_8_owner_identity": RESIDUALS / "P8_Ward_source_owner_identity_CONTRACT.csv",
        "SRC3757_9_source_current": RESIDUALS / "P8_source_current_Ward_universality_CONTRACT.csv",
        "SRC3757_10_flux_closure": RESIDUALS / "P8_PiM_flux_closure_Ward_topological_CONTRACT.csv",
        "SRC3757_11_local_bounds": PCW / "source-intake" / "local_bounds" / "local_bound_claims.csv",
    }


def source_register(timestamp: str) -> list[dict[str, object]]:
    rows = []
    for source_id, path in source_paths().items():
        rows.append(
            {
                **base(timestamp),
                "source_id": source_id,
                "source_path": str(path),
                "source_exists": path.exists(),
                "role": "3757 derivation input",
            }
        )
    return rows


def side_flux_theorem_rows(timestamp: str) -> list[dict[str, object]]:
    entries = [
        (
            "SFT3757_0_balance",
            "For a spacetime tube W with caps Sigma_0,Sigma_1 and side S, Delta ell_M(J_H) = - int_S J_M + int_W Pi_M q_exchange.",
            "Stokes/Ward balance imported from 3754 and sharpened in 3756.",
            "DERIVED_BALANCE_INTERFACE",
            "This is the exact place where source leakage or exchange enters the local Newton/PPN sector.",
            True,
        ),
        (
            "SFT3757_1_material_side_wall",
            "If J_M^a = rho_M u^a and the side wall is generated by u, then n_a J_M^a = rho_M n_a u^a = 0 on S.",
            "Requires parent-defined material/source flow u and a comoving side wall, not an arbitrary observational cut.",
            "EXACT_CONDITIONAL_ZERO_PROOF",
            "This proves Phi_side=0 for a material tube; it does not yet prove the parent action supplies that tube.",
            False,
        ),
        (
            "SFT3757_2_compact_support_variant",
            "If support(J_M) does not intersect S, then int_S J_M = 0 independently of a chosen material flow.",
            "Requires compact-localized source support or an exterior decay theorem strong enough to make the side integral vanish.",
            "EXACT_CONDITIONAL_ZERO_PROOF",
            "This is the safer asymptotic version for isolated bodies.",
            False,
        ),
        (
            "SFT3757_3_projected_exchange_zero",
            "If Pi_M q_exchange = 0 throughout W, then ell_M(J_H) is cap-conserved once Phi_side=0.",
            "Requires the channel-by-channel projected exchange zero not signed in 3756.",
            "EXACT_CONDITIONAL_CONSERVATION_PROOF",
            "This closes the mass/source charge, not every PPN residual.",
            False,
        ),
        (
            "SFT3757_4_Gdot_bridge",
            "If G_eff is calibrated by a parent constant kappa_eff and the Poisson residual is zero, then d ln G_eff/dt = d ln kappa_eff/dt.",
            "Requires the 3755 global-kappa/superselection premises or an explicit kappa evolution law.",
            "EXACT_CONDITIONAL_BRIDGE",
            "This turns the LLR/Gdot row into the first scoreable coupling row.",
            False,
        ),
        (
            "SFT3757_5_conditional_result",
            "Phi_side=0, Pi_M q_exchange=0, and d_t kappa_eff=0 imply d ln G_eff/dt = 0.",
            "All three premises must be parent-signed before any local-GR or Gdot claim is allowed.",
            "CONDITIONAL_THEOREM_NOT_CLAIMED",
            "The derivation is real; the parent signatures are the remaining work.",
            False,
        ),
    ]
    return [
        {
            **base(timestamp),
            "theorem_id": theorem_id,
            "statement": statement,
            "premise_or_derivation": premise,
            "status": status,
            "notes": notes,
            "proved_inside_3757": proved,
            "parent_signed": False if not proved else "imported",
            "claim_allowed": False,
        }
        for theorem_id, statement, premise, status, notes, proved in entries
    ]


def parent_premise_rows(timestamp: str) -> list[dict[str, object]]:
    entries = [
        (
            "PR3757_0_parent_material_tube",
            "parent action defines the local material/source worldtube rather than a hand-cut surface",
            "MISSING_PARENT_WORLD_TUBE",
            "needed for SFT3757_1",
        ),
        (
            "PR3757_1_no_side_crossing",
            "source current is tangent to that side wall or compactly supported away from it",
            "MISSING_NO_SIDE_CROSSING_THEOREM",
            "needed for Phi_side=0",
        ),
        (
            "PR3757_2_no_projected_exchange",
            "Pi_M q_exchange vanishes or is separately bounded in the local tube",
            "MISSING_CHANNEL_ZERO_OR_BOUND",
            "needed for cap conservation",
        ),
        (
            "PR3757_3_global_kappa",
            "kappa_eff is a global superselected constant in the local matter sector",
            "CONDITIONAL_FROM_3755_NOT_PARENT_SIGNED",
            "needed for d ln G_eff/dt = 0",
        ),
        (
            "PR3757_4_poisson_residual",
            "Poisson bridge has no residual drift in the local Newton limit",
            "MISSING_LOCAL_POISSON_RESIDUAL_ZERO",
            "needed before calling it a local-GR result",
        ),
        (
            "PR3757_5_bound_source",
            "LLR/Gdot bound source is locally present and numeric",
            "SOURCE_READY",
            "allows a conditional numerical comparison",
        ),
    ]
    return [
        {
            **base(timestamp),
            "premise_id": premise_id,
            "premise": premise,
            "signature_status": status,
            "use": use,
            "parent_signed": status == "SOURCE_READY",
            "claim_allowed": False,
        }
        for premise_id, premise, status, use in entries
    ]


def to_float(value: str) -> float | None:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    if math.isfinite(parsed):
        return parsed
    return None


def gdot_fill_rows(timestamp: str) -> list[dict[str, object]]:
    runner = read_csv(source_paths()["SRC3757_3_3756_runner"])
    gdot = next(row for row in runner if row["residual_id"] == "KRV3755_0_Gdot")
    bound = to_float(gdot["bound_value"])
    prediction = 0.0
    conditional_pass = bound is not None and abs(prediction) <= bound
    return [
        {
            **base(timestamp),
            "fill_id": "GF3757_0_Gdot_conditional_zero",
            "source_runner_row": gdot["runner_row_id"],
            "residual_id": gdot["residual_id"],
            "symbol": gdot["symbol"],
            "arena": gdot["arena"],
            "bound_value": gdot["bound_value"],
            "units": gdot["units"],
            "prediction_formula": "dln_Geff_dt = dln_kappa_eff_dt = 0",
            "prediction_value": prediction,
            "conditional_score_status": "CONDITIONAL_NUMERIC_PASS" if conditional_pass else "CONDITIONAL_NUMERIC_FAIL",
            "absolute_margin_to_bound": "" if bound is None else bound - abs(prediction),
            "required_parent_premises": "PR3757_0_parent_material_tube;PR3757_1_no_side_crossing;PR3757_2_no_projected_exchange;PR3757_3_global_kappa;PR3757_4_poisson_residual",
            "parent_signature_status": "UNSIGNED",
            "score_ready_if_parent_signed": conditional_pass,
            "valid_prediction_row": False,
            "claim_allowed": False,
        }
    ]


def runner_patch_rows(timestamp: str) -> list[dict[str, object]]:
    rows = []
    gdot_fill = gdot_fill_rows(timestamp)[0]
    for row in read_csv(source_paths()["SRC3757_3_3756_runner"]):
        patched = {
            **base(timestamp),
            "patched_runner_row_id": f"RUN3757_{row['residual_id']}",
            "source_runner_row": row["runner_row_id"],
            "residual_id": row["residual_id"],
            "symbol": row["symbol"],
            "arena": row["arena"],
            "bound_value": row["bound_value"],
            "units": row["units"],
            "prediction_status_3756": row["prediction_status"],
            "prediction_value_3756": row["prediction_value"],
            "score_status_3756": row["score_status"],
            "prediction_status_3757": row["prediction_status"],
            "prediction_value_3757": row["prediction_value"],
            "score_status_3757": row["score_status"],
            "conditional_score_ready": False,
            "valid_prediction_row": False,
            "claim_allowed": False,
            "notes": "unchanged from 3756",
        }
        if row["residual_id"] == "KRV3755_0_Gdot":
            patched.update(
                {
                    "prediction_status_3757": "CONDITIONAL_ZERO_IF_PARENT_KAPPA_AND_NO_FLUX_EXCHANGE_SIGNED",
                    "prediction_value_3757": gdot_fill["prediction_value"],
                    "score_status_3757": "CONDITIONAL_PASS_UNSIGNED_PARENT_PREMISES",
                    "conditional_score_ready": True,
                    "notes": "first row is now numerically fillable, but remains nonclaim until parent premises are signed",
                }
            )
        rows.append(patched)
    return rows


def claim_gate_rows(timestamp: str, grouped: dict[str, list[dict[str, object]]]) -> list[dict[str, object]]:
    all_sources = all(Path(str(row["source_path"])).exists() for row in grouped["sources"])
    gates = [
        ("CG3757_0_sources", "all 3757 source paths exist", all_sources, "path hygiene"),
        ("CG3757_1_side_flux_theorem", "material-tube side-flux zero theorem constructed", True, "conditional proof exists"),
        ("CG3757_2_side_flux_parent_signed", "side-flux zero theorem parent-signed", False, "worldtube/no-crossing premise unsigned"),
        ("CG3757_3_projected_exchange_parent_signed", "Pi_M q_exchange=0 parent-signed", False, "channel zero remains open"),
        ("CG3757_4_gdot_conditional_fill", "Gdot row has a conditional numeric zero fill", True, "first scoreable coupling row exists conditionally"),
        ("CG3757_5_gdot_claim", "Gdot claim allowed", False, "parent signatures absent"),
        ("CG3757_6_wep_claim", "WEP/source-blind coupling claim allowed", False, "not filled in this checkpoint"),
        ("CG3757_7_local_gr_claim", "local GR/PPN claim allowed", False, "local branch still nonclaim"),
    ]
    return [
        {
            **base(timestamp),
            "gate_id": gate_id,
            "gate": gate,
            "passed": passed,
            "details": details,
            "claim_allowed": False,
        }
        for gate_id, gate, passed, details in gates
    ]


def decision_rows(timestamp: str) -> list[dict[str, object]]:
    entries = [
        (
            "DEC3757_0",
            "Gdot is the best first coupling row because a signed global-kappa theorem gives prediction 0 against a numeric LLR bound.",
            "keep the row nonclaim until parent signatures are real",
        ),
        (
            "DEC3757_1",
            "The side-flux zero route is now a proper theorem for a material tube, not merely a missing-item note.",
            "next work must make the tube/flow parent-owned or switch to a numeric residual bound",
        ),
        (
            "DEC3757_2",
            "WEP/source-blind coupling is likely the next human-meaningful row after Gdot, but it needs species/source-label blindness of kappa_M.",
            "do not move to public local-GR language yet",
        ),
    ]
    return [
        {
            **base(timestamp),
            "decision_id": decision_id,
            "decision": decision,
            "action": action,
            "claim_allowed": False,
        }
        for decision_id, decision, action in entries
    ]


def next_target_rows(timestamp: str) -> list[dict[str, object]]:
    return [
        {
            **base(timestamp),
            "next_id": "NEXT3757_0",
            "target_doc": "3758-Y5-R2FR-kappa-superselection-signature-or-Gdot-numeric-bound.md",
            "target_script": "scripts/Y5_R2FR_3758_kappa_superselection_signature_or_Gdot_numeric_bound.py",
            "objective": "try to parent-sign global kappa/no-flux premises; if that fails, derive a nonzero dln_kappa_eff residual and compare it numerically to the Gdot bound",
            "reason": "3757 makes Gdot conditionally scoreable; 3758 must decide whether the conditional zero is earned or replaced by a bounded residual",
            "claim_allowed": False,
        }
    ]


def status_rows(timestamp: str) -> list[dict[str, object]]:
    return [
        {
            **base(timestamp),
            "status": "FIRST_COUPLING_ROW_CONDITIONALLY_SCOREABLE",
            "summary": "3757 proves a material-tube side-flux zero theorem and converts the Gdot residual into a conditional zero prediction. The row passes its numeric bound only if the parent action signs no-flux/no-exchange/global-kappa premises.",
            "claim_allowed": False,
        }
    ]


def validation_rows(timestamp: str, grouped: dict[str, list[dict[str, object]]]) -> list[dict[str, object]]:
    generated_csvs = [path for key, path in OUTPUTS.items() if key != "validation"]
    checks = [
        ("sources_exist", "all 3757 source paths exist", all(Path(str(row["source_path"])).exists() for row in grouped["sources"])),
        ("generated_csvs_parse", "all generated 3757 csvs parse", all(read_csv(path) for path in generated_csvs)),
        (
            "side_flux_material_theorem",
            "material-tube side-flux zero theorem emitted",
            any(row["theorem_id"] == "SFT3757_1_material_side_wall" and row["status"] == "EXACT_CONDITIONAL_ZERO_PROOF" for row in grouped["side_flux"]),
        ),
        (
            "gdot_conditional_zero",
            "Gdot conditional zero fill emitted",
            any(row["residual_id"] == "KRV3755_0_Gdot" and str(row["prediction_value"]) in {"0.0", "0"} for row in grouped["gdot_fill"]),
        ),
        (
            "gdot_conditional_pass",
            "Gdot conditional fill passes numeric bound",
            any(row["conditional_score_status"] == "CONDITIONAL_NUMERIC_PASS" for row in grouped["gdot_fill"]),
        ),
        (
            "runner_patch_nonclaim",
            "patched runner remains nonclaim",
            all(str(row["claim_allowed"]) == "False" or row["claim_allowed"] is False for row in grouped["runner_patch"]),
        ),
        (
            "parent_unsigned",
            "at least one required parent premise remains unsigned",
            any(str(row["parent_signed"]) == "False" or row["parent_signed"] is False for row in grouped["parent_premises"]),
        ),
        (
            "claim_gate_blocked",
            "local GR claim remains false",
            any(row["gate_id"] == "CG3757_7_local_gr_claim" and row["passed"] is False for row in grouped["claim_gates"]),
        ),
        (
            "next_target",
            "3758 target emitted",
            grouped["next_target"][0]["target_doc"] == "3758-Y5-R2FR-kappa-superselection-signature-or-Gdot-numeric-bound.md",
        ),
        (
            "no_formalization_leak",
            "no 3757 files written to formalization-workbench",
            not FORMALIZATION.exists() or not list(FORMALIZATION.rglob("*3757*")),
        ),
    ]
    return [
        {
            **base(timestamp),
            "validation_id": validation_id,
            "description": description,
            "result": "PASS" if result else "FAIL",
            "details": "" if result else "check failed",
        }
        for validation_id, description, result in checks
    ]


def render_doc(grouped: dict[str, list[dict[str, object]]]) -> str:
    lines = [
        "# 3757 — First Coupling Runner Fill Or Side-Flux Zero Proof",
        "",
        "## Status",
        "",
        f"`{grouped['status'][0]['status']}`.",
        "",
        grouped["status"][0]["summary"],
        "",
        "## Actual Derivation Step",
        "",
        "This checkpoint does not merely record that coupling is missing. It proves the conditional side-flux result needed by the local branch:",
        "",
        "- For a tube `W` with caps `Sigma_0,Sigma_1` and side `S`, the imported Ward/Stokes balance is `Delta ell_M(J_H) = - int_S J_M + int_W Pi_M q_exchange`.",
        "- If the parent supplies a material/source flow `u` with `J_M^a = rho_M u^a`, and the side wall is generated by `u`, then `n_a J_M^a = rho_M n_a u^a = 0` on `S`.",
        "- Therefore `Phi_side = int_S J_M = 0` for a parent-owned material tube, or for a compact-support side wall that misses `support(J_M)`.",
        "- If additionally `Pi_M q_exchange=0`, the source charge is cap-conserved.",
        "- If additionally `kappa_eff` is globally superselected and the Poisson residual has no local drift, then `d ln G_eff/dt = 0`.",
        "",
        "That is the first honest conditional coupling fill: the LLR/Gdot row has a zero prediction if the parent premises are signed.",
        "",
        "## Side-Flux Clauses",
    ]
    for row in grouped["side_flux"]:
        lines.append(f"- `{row['theorem_id']}` `{row['status']}`: {row['statement']}")
    lines.extend(["", "## Gdot Conditional Fill"])
    for row in grouped["gdot_fill"]:
        lines.append(
            f"- `{row['fill_id']}` `{row['conditional_score_status']}`: `{row['symbol']}` prediction `{row['prediction_value']} {row['units']}` against bound `{row['bound_value']} {row['units']}`; claim=`{row['claim_allowed']}`"
        )
    lines.extend(["", "## Patched Runner"])
    for row in grouped["runner_patch"]:
        lines.append(
            f"- `{row['patched_runner_row_id']}` `{row['score_status_3757']}`: `{row['symbol']}` conditional_score_ready=`{row['conditional_score_ready']}` claim=`{row['claim_allowed']}`"
        )
    lines.extend(["", "## Parent Premises Still Needed"])
    for row in grouped["parent_premises"]:
        lines.append(f"- `{row['premise_id']}` `{row['signature_status']}`: {row['premise']}")
    lines.extend(["", "## Claim Gates"])
    for row in grouped["claim_gates"]:
        lines.append(f"- `{row['gate_id']}` pass=`{row['passed']}`: {row['gate']} — {row['details']}")
    lines.extend(["", "## Decisions"])
    for row in grouped["decision_rows"]:
        lines.append(f"- `{row['decision_id']}`: {row['decision']} Action: {row['action']}.")
    lines.extend(["", "## Next Target"])
    for row in grouped["next_target"]:
        lines.append(f"- `{row['target_doc']}`: {row['objective']}")
    lines.extend(["", "## Validation"])
    for row in grouped["validation"]:
        lines.append(f"- `{row['validation_id']}` `{row['result']}`: {row['description']}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    timestamp = stamp()
    RESIDUALS.mkdir(parents=True, exist_ok=True)

    grouped: dict[str, list[dict[str, object]]] = {
        "sources": source_register(timestamp),
        "side_flux": side_flux_theorem_rows(timestamp),
        "gdot_fill": gdot_fill_rows(timestamp),
        "parent_premises": parent_premise_rows(timestamp),
        "runner_patch": runner_patch_rows(timestamp),
        "decision_rows": decision_rows(timestamp),
        "next_target": next_target_rows(timestamp),
        "status": status_rows(timestamp),
    }
    grouped["claim_gates"] = claim_gate_rows(timestamp, grouped)

    write_csv(OUTPUTS["sources"], grouped["sources"])
    write_csv(OUTPUTS["side_flux"], grouped["side_flux"])
    write_csv(OUTPUTS["gdot_fill"], grouped["gdot_fill"])
    write_csv(OUTPUTS["runner_patch"], grouped["runner_patch"])
    write_csv(OUTPUTS["parent_premises"], grouped["parent_premises"])
    write_csv(OUTPUTS["claim_gates"], grouped["claim_gates"])
    write_csv(OUTPUTS["decision_rows"], grouped["decision_rows"])
    write_csv(OUTPUTS["next_target"], grouped["next_target"])
    write_csv(OUTPUTS["status"], grouped["status"])

    grouped["validation"] = validation_rows(timestamp, grouped)
    write_csv(OUTPUTS["validation"], grouped["validation"])

    DOC_PATH.write_text(render_doc(grouped), encoding="utf-8")

    cache = Path(__file__).resolve().parent / "__pycache__"
    if cache.exists():
        shutil.rmtree(cache)

    failures = [row for row in grouped["validation"] if row["result"] != "PASS"]
    if failures:
        raise SystemExit(f"3757 validation failed: {failures}")
    print("wrote 3757 checkpoint: first coupling row conditionally scoreable")


if __name__ == "__main__":
    main()
