from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUN_SLUG = "Cperp-relative-exactness-C-sector"
STATUS = "Cperp_scalar_relative_exactness_not_derived_projected_metric_demoted_to_explicit_closure"
CLAIM_CEILING = "Cperp_exactness_failed_internal_closure_label_no_local_GR_or_unification_promotion"

B_MEM = 2.0 / 27.0
LOCAL_DELTA_C_GATE = 4.6e-05
LOCAL_QR_GATE = 2.3e-05


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def relpath(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def source_register_rows() -> list[dict[str, Any]]:
    sources = [
        (ROOT / "60-relative-cohomology-boundary-contract.md", "relative cohomology boundary contract"),
        (ROOT / "231-Jrel-cohomology-projector-or-local-EH-limit.md", "Jrel cohomology exactness precedent"),
        (ROOT / "272-quotient-configuration-principle-from-topological-projector.md", "quotient principle conditional route"),
        (ROOT / "271-parent-no-Cperp-action-or-closure.md", "no-Cperp quotient action skeleton"),
        (ROOT / "scripts" / "Cperp_relative_exactness_C_sector.py", "this C-sector exactness gate"),
    ]
    return [
        {
            "source": relpath(path),
            "role": role,
            "exists": "yes" if path.exists() else "no",
        }
        for path, role in sources
    ]


def cohomology_degree_audit_rows() -> list[dict[str, Any]]:
    return [
        {
            "object": "J_rel_memory_flux",
            "degree": "2-form/current-like object",
            "relative_group": "H^2(Sigma_ext, partial Sigma_ext)",
            "math_result": "vanishes on compact shell after mass/shear projection",
            "verdict": "conditional_pass_for_Jrel",
            "comment": "This is the valid checkpoint-231 cohomology win.",
        },
        {
            "object": "Cperp_scalar",
            "degree": "0-form/scalar representative",
            "relative_group": "H^0(D, partial D)",
            "math_result": "for connected D with nonempty boundary, relative closed 0-classes are trivial",
            "verdict": "does_not_prove_arbitrary_Cperp_exactness",
            "comment": "H^0 relative triviality says boundary-zero closed scalars vanish; it does not turn arbitrary local scalar profiles into gauge.",
        },
        {
            "object": "eta_perp_scalar_shift",
            "degree": "0-form shift parameter",
            "relative_group": "exact 0-forms are not generated by d of a (-1)-form",
            "math_result": "ordinary de Rham exactness does not define arbitrary scalar shifts as exact",
            "verdict": "fail_as_de_Rham_exactness",
            "comment": "A scalar shift can be gauge only from a constraint/gauge principle, not from ordinary exactness alone.",
        },
        {
            "object": "dCperp_gradient",
            "degree": "exact 1-form",
            "relative_group": "exact by definition if Cperp is smooth",
            "math_result": "dCperp is exact but can still be physically observable through gradient energy or forces",
            "verdict": "insufficient",
            "comment": "Exact gradients are not automatically unphysical unless the action has no representative dependence.",
        },
        {
            "object": "lifted_C_connection_route",
            "degree": "connection/current form rather than scalar",
            "relative_group": "could use H^1/H^2 relative machinery",
            "math_result": "possible future route if C is derived as holonomy/boundary class of a form field",
            "verdict": "future_theorem_target",
            "comment": "This would change the C-sector ontology; not derived in current branch.",
        },
    ]


def exactness_gate_rows() -> list[dict[str, Any]]:
    return [
        {
            "gate": "transfer_Jrel_exactness_to_Cperp",
            "result": "fail",
            "evidence": "Jrel is a projected flux/current form; Cperp is currently a scalar representative",
            "claim_effect": "Jrel cohomology analogy cannot prove Cperp exactness",
        },
        {
            "gate": "relative_H0_scalar_gate",
            "result": "fail_for_arbitrary_profiles",
            "evidence": "H^0(D,partial D)=0 only kills closed boundary-zero scalar classes",
            "claim_effect": "does not make all Cperp residuals gauge",
        },
        {
            "gate": "dCperp_exact_1form_gate",
            "result": "insufficient",
            "evidence": "dCperp exactness does not remove gradient observables if the action contains them",
            "claim_effect": "still needs no-Cperp action or lifted form gauge symmetry",
        },
        {
            "gate": "first_class_constraint_gate",
            "result": "not_derived",
            "evidence": "requires parent no-Cperp Hamiltonian as a principle, not just skeleton",
            "claim_effect": "metric selector cannot be promoted",
        },
        {
            "gate": "projected_metric_closure_policy",
            "result": "demote",
            "evidence": "Cperp exactness for scalar C-sector failed in current route",
            "claim_effect": "exp(P_D C)g becomes explicit effective closure unless C-sector is later lifted",
        },
        {
            "gate": "support_claim_allowed",
            "result": "no",
            "evidence": "projected metric selector is closure-labelled and Bmem/local-GR remain open",
            "claim_effect": "no local-GR or unification promotion",
        },
    ]


def closure_label_rows() -> list[dict[str, Any]]:
    return [
        {
            "item": "projected_matter_metric",
            "status": "explicit_effective_closure",
            "allowed_use": "local-silence / BAO common-mode effective branch with clear label",
            "forbidden_use": "parent-derived matter coupling or local-GR proof",
        },
        {
            "item": "quotient_configuration_space",
            "status": "theorem_target_only",
            "allowed_use": "conditional derivation route if C-sector is later lifted to form/topological class",
            "forbidden_use": "assumed physical configuration space in public claim",
        },
        {
            "item": "Cperp_first_class_constraint",
            "status": "not_derived",
            "allowed_use": "constraint algebra target",
            "forbidden_use": "claiming Cperp is gauge",
        },
        {
            "item": "ordinary_expC_metric",
            "status": "rejected_as_lead",
            "allowed_use": "ablation / failure baseline",
            "forbidden_use": "local-silence branch without huge screening",
        },
        {
            "item": "lifted_C_form_sector",
            "status": "future_theorem_route",
            "allowed_use": "new derivation attempt",
            "forbidden_use": "retroactively treating current scalar Cperp as exact",
        },
    ]


def future_theorem_contract_rows() -> list[dict[str, Any]]:
    return [
        {
            "contract": "L1_lift_C_to_form_or_holonomy",
            "required_form": "C_D arises as boundary/holonomy/domain integral of a form/current, not as raw scalar profile",
            "status": "future_route",
            "failure_mode": "scalar Cperp exactness remains unavailable",
        },
        {
            "contract": "L2_relative_exact_local_residual",
            "required_form": "local residual lies in exact relative class with pure-gauge boundary primitive",
            "status": "not_derived",
            "failure_mode": "local residual can be observable",
        },
        {
            "contract": "L3_FLRW_nonzero_class_survives",
            "required_form": "coherent FLRW boundary class is nontrivial",
            "status": "conditional_previous",
            "failure_mode": "same quotient kills cosmological signal",
        },
        {
            "contract": "L4_matter_on_class_observables",
            "required_form": "matter couples to class/holonomy representative only",
            "status": "closure_currently",
            "failure_mode": "projected metric remains imposed",
        },
        {
            "contract": "L5_domain_variation_and_Bianchi",
            "required_form": "domain labels, boundaries, and projector stresses varied",
            "status": "open",
            "failure_mode": "hidden external force/conservation issue",
        },
        {
            "contract": "L6_amplitude_reduction",
            "required_form": "same lifted sector derives or preserves Bmem theorem target",
            "status": "not_derived",
            "failure_mode": "no unified amplitude claim",
        },
    ]


def comparison_rows() -> list[dict[str, Any]]:
    return [
        {
            "question": "Does Jrel exactness transfer to scalar Cperp?",
            "answer": "no",
            "reason": "form/current cohomology and scalar representative cohomology are different gates",
            "consequence": "do not claim Cperp exactness from checkpoint 231",
        },
        {
            "question": "Does H^0 relative triviality help?",
            "answer": "only_narrowly",
            "reason": "it kills closed boundary-zero scalar classes, not arbitrary residual profiles",
            "consequence": "insufficient for quotient gauge orbit",
        },
        {
            "question": "Does dCperp exactness help?",
            "answer": "not_enough",
            "reason": "exact gradients can still be physical if action depends on them",
            "consequence": "still need no-representative action principle",
        },
        {
            "question": "Should projected metric be promoted?",
            "answer": "no",
            "reason": "Cperp relative exactness for C-sector not derived",
            "consequence": "label exp(P_D C)g as effective closure",
        },
        {
            "question": "Is there still a future route?",
            "answer": "yes",
            "reason": "lift C-sector to a form/holonomy/boundary class and rerun exactness",
            "consequence": "new theorem target, not current result",
        },
    ]


def numeric_rows() -> list[dict[str, Any]]:
    return [
        {
            "quantity": "B_mem",
            "value": B_MEM,
            "meaning": "fixed closure/theorem target carried forward",
        },
        {
            "quantity": "epsilon_local_DeltaC_max",
            "value": LOCAL_DELTA_C_GATE / B_MEM,
            "meaning": "if projected metric leaks Cperp matter coupling, local Delta C gate requires below this",
        },
        {
            "quantity": "epsilon_local_qR_max",
            "value": LOCAL_QR_GATE / B_MEM,
            "meaning": "stricter qR-like leak bound",
        },
    ]


def decision_rows() -> list[dict[str, Any]]:
    return [
        {
            "decision": STATUS,
            "claim_ceiling": CLAIM_CEILING,
            "meaning": (
                "The current scalar Cperp sector does not inherit the Jrel relative-cohomology exactness theorem. "
                "Relative H^0 triviality is too weak, and dCperp exactness does not make gradients unphysical. "
                "Therefore exp(P_D C)g must be labelled an explicit effective closure unless a future lifted form/holonomy C-sector derives Cperp exactness."
            ),
            "next_target": "either_lift_C_sector_to_form_holonomy_class_or_pivot_to_empirical_closure_tests",
        }
    ]


def build_outputs(timestamp: str) -> dict[str, Any]:
    run_dir = ROOT / "runs" / f"{timestamp}-{RUN_SLUG}"
    results_dir = run_dir / "results"
    results_dir.mkdir(parents=True, exist_ok=True)

    outputs = {
        "source_register.csv": (source_register_rows(), ["source", "role", "exists"]),
        "cohomology_degree_audit.csv": (
            cohomology_degree_audit_rows(),
            ["object", "degree", "relative_group", "math_result", "verdict", "comment"],
        ),
        "exactness_gate_results.csv": (exactness_gate_rows(), ["gate", "result", "evidence", "claim_effect"]),
        "closure_labels.csv": (closure_label_rows(), ["item", "status", "allowed_use", "forbidden_use"]),
        "future_theorem_contract.csv": (future_theorem_contract_rows(), ["contract", "required_form", "status", "failure_mode"]),
        "derivation_vs_closure.csv": (comparison_rows(), ["question", "answer", "reason", "consequence"]),
        "numeric_bounds.csv": (numeric_rows(), ["quantity", "value", "meaning"]),
        "decision.csv": (decision_rows(), ["decision", "claim_ceiling", "meaning", "next_target"]),
    }
    for filename, (rows, fieldnames) in outputs.items():
        write_csv(results_dir / filename, rows, fieldnames)

    status = decision_rows()[0]["decision"]
    payload = {
        "status": status,
        "claim_ceiling": CLAIM_CEILING,
        "run_dir": str(run_dir),
        "results_dir": str(results_dir),
        "generated": list(outputs),
        "Cperp_scalar_relative_exactness_derived": False,
        "projected_metric_label": "explicit_effective_closure",
        "ordinary_expC_metric_rejected_as_lead": True,
        "future_lifted_C_form_route_open": True,
        "local_GR_or_unification_claim_allowed": False,
        "next_target": "either_lift_C_sector_to_form_holonomy_class_or_pivot_to_empirical_closure_tests",
    }
    write_json(run_dir / "status.json", payload)
    (run_dir / "DONE.txt").write_text(status + "\n", encoding="utf-8")
    return payload


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Cperp relative exactness test for scalar C-sector.")
    parser.add_argument("--timestamp", default=datetime.now().strftime("%Y%m%d-%H%M%S"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = build_outputs(args.timestamp)
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
