from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, Iterable, List


def write_csv(path: Path, rows: Iterable[Dict[str, object]]) -> None:
    row_list = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not row_list:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(row_list[0].keys()))
        writer.writeheader()
        writer.writerows(row_list)


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def inventory_signature_rows() -> List[Dict[str, object]]:
    return [
        {
            "signature_id": "PAI4476_0_parent_action_alphabet",
            "clause": "local parent bulk action alphabet is declared before variation",
            "formal_test": "S_bulk belongs to Alg[g,e,omega,Hilbert matter,EM,topological kappa,quotient fields] and not to an algebra enlarged by M_cell, R_obs, P_active, finite J, labelled species, or marker auxiliaries",
            "derivation": "An action inventory is a grammar statement: if a symbol is not in the allowed local bulk alphabet, no local monomial containing that symbol can be projected out of S_bulk.",
            "if_signed": "marker bulk ideal is empty at the action-algebra level",
            "current_status": "ACTION_ALPHABET_NOT_PARENT_SIGNED",
            "parent_signed": False,
            "valid_for_claim": False,
        },
        {
            "signature_id": "PAI4476_1_marker_ideal_empty",
            "clause": "marker ideal projection vanishes",
            "formal_test": "I_M=<M_cell,R_obs_as_bulk,P_active,J_finite,labelled_species,M_aux>; Pi_{I_M}(S_bulk)=0",
            "derivation": "The 4475 lambda_M law becomes an ideal-membership test. If the projection of S_bulk onto the marker ideal is zero, every bulk lambda_M coefficient is zero.",
            "if_signed": "lambda_M_bulk=0 for all marker monomials, not just the first guessed operator",
            "current_status": "MARKER_IDEAL_ZERO_UNSIGNED",
            "parent_signed": False,
            "valid_for_claim": False,
        },
        {
            "signature_id": "PAI4476_2_external_readout_compartment",
            "clause": "readout variables live only in O_read or J=0 diagnostic insertions",
            "formal_test": "R_obs appears in O_read[Phi;R_obs] or int J O_read with J=0 before local variation, never in S_bulk",
            "derivation": "This imports the 4474 lemma into the action grammar: external readout can label observations but cannot create an action coefficient.",
            "if_signed": "R_obs cannot source lambda_M, C_marker, c_R2_marker or T_marker",
            "current_status": "READOUT_COMPARTMENT_UNSIGNED",
            "parent_signed": False,
            "valid_for_claim": False,
        },
        {
            "signature_id": "PAI4476_3_escape_routes_closed",
            "clause": "finite-source, spurion, auxiliary and boundary substitutes are absent or routed",
            "formal_test": "J_finite=0, P_active not a background/spurion, no hidden M_aux integrates out, and Pi_loc(delta S_boundary/delta marker)=0",
            "derivation": "A proof that explicit lambda_M is absent is insufficient if the same operator is regenerated by a finite diagnostic source, material background, hidden auxiliary sector, or boundary/interface variation.",
            "if_signed": "the lambda_M zero theorem is not bypassed by another marker channel",
            "current_status": "ESCAPE_ROUTES_UNSIGNED",
            "parent_signed": False,
            "valid_for_claim": False,
        },
        {
            "signature_id": "PAI4476_4_projection_fallback_required",
            "clause": "if the inventory signature is not signed, the finite branch projects into local residuals",
            "formal_test": "Pi_{I_M}(S_bulk)!=0 implies lambda_M rows must map to c_R2_marker, C_marker, T_marker/J_marker and boundary_marker without cancellation",
            "derivation": "This is the useful fallback: failed zero proof does not end the route; it makes the finite coupling scoreable in R10, PPN, WEP, clock and orbital arenas.",
            "if_signed": "finite marker branch becomes a bounded local-test branch",
            "current_status": "DERIVED_FALLBACK_LAW",
            "parent_signed": True,
            "valid_for_claim": False,
        },
        {
            "signature_id": "PAI4476_5_verdict",
            "clause": "parent inventory is not signed yet, so projection map is mandatory",
            "formal_test": "PAI4476_0 through PAI4476_3 sign together, or the projection fallback PAI4476_4 is used",
            "derivation": "Current MTS has a clean conditional inventory route, but not a signed parent action alphabet. Therefore 4476 supplies the finite projection map rather than pretending the branch is closed.",
            "if_signed": "lambda_M zero branch can advance toward local-GR closure",
            "current_status": "INVENTORY_SIGNATURE_PARENT_UNSIGNED_PROJECTION_MAP_DERIVED",
            "parent_signed": False,
            "valid_for_claim": False,
        },
    ]


def lambda_projection_map_rows() -> List[Dict[str, object]]:
    return [
        {
            "map_id": "PMAP4476_0_universal_projection",
            "source_operator_class": "any marker monomial lambda_M F_M O_a",
            "local_projection": "define marker moments mu0_M=<F_M>, mu2_M=<r^2 F_M> and basis projector zeta_a",
            "formula": "C_a^M = lambda_M*(zeta_a*mu0_M + zeta_grad_a*mu2_M/L_loc^2)/N_a",
            "target_rows": "all marker residual channels",
            "derived_status": "DERIVED_NORMAL_FORM",
            "needed_inputs": "lambda_M; F_M moments; operator basis; local scale; normalization N_a",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_1_curvature_square",
            "source_operator_class": "O_a in {R^2,Ricci^2,Weyl^2,Riemann^2}",
            "local_projection": "marker term is already a quadratic-curvature residual",
            "formula": "c_R2_marker = lambda_M*(zeta_R2*mu0_M + zeta_R2_grad*mu2_M/L_loc^2)/N_EH + c_marker_aux + c_marker_boundary",
            "target_rows": "c_R2_marker;R10_alpha_lambda;PPN_gamma_beta",
            "derived_status": "DERIVED_PROJECTION_TEMPLATE",
            "needed_inputs": "quadratic basis channel; mu0_M; mu2_M; zeta_R2; N_EH; auxiliary/boundary guards",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_2_linear_curvature",
            "source_operator_class": "O_a=R or Ricci-contracted EH-like operator",
            "local_projection": "common profile renormalizes kappa; varying/material profile becomes source-measure or PPN residual",
            "formula": "delta kappa_eff/kappa_eff ~ lambda_M*mu0_M/N_EH; material gradients feed C_marker or boundary_marker rather than a free scalaron unless a dynamic marker mode is kept",
            "target_rows": "C_marker;kappa_drift;PPN;clock;orbital",
            "derived_status": "DERIVED_CLASSIFICATION",
            "needed_inputs": "whether F_M is common, material dependent, dynamic or boundary supported",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_3_source_measure",
            "source_operator_class": "O_a in {rho_H,T_H,Z_H,matter-frame multiplier}",
            "local_projection": "marker changes the matter/source normalization",
            "formula": "C_marker = lambda_M*zeta_src*mu0_M/N_src; Delta_C_AB = C_marker,A - C_marker,B for composition-dependent profiles",
            "target_rows": "C_marker;WEP;R10_common_mode;PPN;clock",
            "derived_status": "DERIVED_SOURCE_PROJECTION",
            "needed_inputs": "source operator; material dependence; N_src; zeta_src; screening branch",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_4_em_or_stress",
            "source_operator_class": "O_a in {F_EM^2,T_EM,Poynting/stress operator}",
            "local_projection": "marker creates an EM/stress side-channel unless it is the already-owned Maxwell-Hodge Hilbert stress",
            "formula": "T_marker^{mu nu}=(-2/sqrt(-g))*delta Delta S_M/delta g_{mu nu}; zeta3_EM_marker = Pi_EM(T_marker)",
            "target_rows": "T_marker/J_marker;EM_stress;PPN;clock",
            "derived_status": "DERIVED_STRESS_PROJECTION",
            "needed_inputs": "EM operator; metric variation; same-source ownership; zeta3_EM projection",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_5_scalar_gamma_khat",
            "source_operator_class": "O_a in {chi,Gamma_eff,K_hat,q_loc,Z_H derivative}",
            "local_projection": "marker feeds scalar/current residuals and local fifth-force arenas",
            "formula": "J_marker = delta Delta S_M/delta chi or delta Delta S_M/delta Gamma_eff; q_marker^nu = Pi_loc(nabla^nu Gamma_eff - nabla_mu K_hat^{mu nu})|marker",
            "target_rows": "C_marker;q_loc;R10;PPN;clock",
            "derived_status": "DERIVED_CURRENT_PROJECTION",
            "needed_inputs": "which scalar/current operator is present; support; derivative order; screening",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_6_boundary_interface",
            "source_operator_class": "boundary/reference marker",
            "local_projection": "not a bulk lambda_M term, but still contributes if boundary variation projects into local response",
            "formula": "boundary_marker = Pi_loc(delta S_boundary/delta R_obs) unless fixed/topological/no-flux/Hamiltonian-routed",
            "target_rows": "boundary_marker;clock;orbital;local_GR",
            "derived_status": "BOUNDARY_ROUTE_SEPARATED",
            "needed_inputs": "boundary action; routing theorem; compact-support proof; flux/matching data",
            "valid_for_claim": False,
        },
        {
            "map_id": "PMAP4476_7_no_cancellation_envelope",
            "source_operator_class": "all finite marker channels",
            "local_projection": "componentwise absolute envelope",
            "formula": "R_marker_abs = abs(c_R2_marker)+abs(C_marker)+abs(T_marker_projection)+abs(boundary_marker)",
            "target_rows": "claim_gate_guard",
            "derived_status": "DERIVED_NO_CANCELLATION_GUARD",
            "needed_inputs": "all component values or separate zero certificates",
            "valid_for_claim": False,
        },
    ]


def projection_intake_rows() -> List[Dict[str, object]]:
    return [
        {
            "row_id": "PIR4476_0_parent_inventory_signature",
            "quantity": "Z_inventory",
            "definition": "parent action inventory certificate proving the marker ideal is empty",
            "formula_or_test": "Z_inventory=True iff Pi_{I_M}(S_bulk)=0 and all escape routes are closed",
            "needed_inputs": "field alphabet; action monomial list; readout compartment; auxiliary/boundary firewalls",
            "current_value": "MISSING_PARENT_ACTION_INVENTORY_SIGNATURE",
            "units": "boolean_certificate",
            "target": "lambda_M_zero",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "row_id": "PIR4476_1_mu0_M",
            "quantity": "mu0_M",
            "definition": "zeroth marker-profile moment entering local projection",
            "formula_or_test": "mu0_M=<F_M> over the local support/normalization convention",
            "needed_inputs": "F_M; support; normalization; whether varied",
            "current_value": "MISSING_MARKER_PROFILE_MOMENT",
            "units": "profile_integral_units",
            "target": "all_PMAP4476_targets",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "row_id": "PIR4476_2_mu2_M",
            "quantity": "mu2_M",
            "definition": "second marker-profile moment controlling finite-size/gradient leakage",
            "formula_or_test": "mu2_M=<r^2 F_M> ~ ell_marker^2 mu0_M for compact profiles",
            "needed_inputs": "ell_marker or profile; support; local-scale expansion",
            "current_value": "MISSING_MARKER_SECOND_MOMENT",
            "units": "m^2_times_profile_units",
            "target": "c_R2_marker;boundary/gradient_leakage",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "row_id": "PIR4476_3_zeta_basis",
            "quantity": "zeta_a",
            "definition": "basis projector from O_marker to canonical residual channel",
            "formula_or_test": "O_marker -> {zeta_R2,zeta_src,zeta_EM,zeta_gamma,zeta_boundary}",
            "needed_inputs": "operator basis; variation convention; channel sign",
            "current_value": "MISSING_MARKER_BASIS_PROJECTORS",
            "units": "dimensionless_or_declared",
            "target": "c_R2_marker;C_marker;T_marker;boundary_marker",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "row_id": "PIR4476_4_normalizations",
            "quantity": "N_EH,N_src,N_stress,N_boundary",
            "definition": "normalizations converting lambda_M projections into canonical local residual rows",
            "formula_or_test": "C_a^M=lambda_M*zeta_a*mu0_M/N_a",
            "needed_inputs": "EH/source/stress/boundary normalization; units; sign convention",
            "current_value": "MISSING_PROJECTION_NORMALIZATIONS",
            "units": "declared_by_channel",
            "target": "all_PMAP4476_targets",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "row_id": "PIR4476_5_projection_values",
            "quantity": "Pi_local(lambda_M)",
            "definition": "finite marker projection vector",
            "formula_or_test": "Pi_local(lambda_M)=(c_R2_marker,C_marker,T_marker_projection,boundary_marker)",
            "needed_inputs": "lambda_M; moments; projectors; normalizations; no-cancellation envelope",
            "current_value": "MISSING_LAMBDAM_PROJECTION_VALUES",
            "units": "mixed_declared_components",
            "target": "R10;WEP;PPN;clock;orbital",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
    ]


def decision_rows(next_target: str) -> List[Dict[str, object]]:
    return [
        {
            "decision_id": "DEC4476_0_inventory_contract",
            "finding": "the parent inventory closure is now an ideal-projection signature, Pi_{I_M}(S_bulk)=0",
            "consequence": "a true zero proof must sign the whole action alphabet, not just omit one written lambda_M",
            "next_action": next_target,
            "valid_for_claim": False,
        },
        {
            "decision_id": "DEC4476_1_projection_map",
            "finding": "finite lambda_M now has a projection map into c_R2_marker, C_marker, T_marker/J_marker and boundary_marker",
            "consequence": "if the inventory proof fails, local tests can score the branch componentwise",
            "next_action": next_target,
            "valid_for_claim": False,
        },
        {
            "decision_id": "DEC4476_2_next_target",
            "finding": "the sharpest next derivation is to attack Z_inventory directly or derive the first source moment mu0_M/mu2_M from the parent geometry",
            "consequence": "next work should try the inventory signature first; fallback is marker-profile moment derivation",
            "next_action": next_target,
            "valid_for_claim": False,
        },
    ]


def claim_gate_rows(
    source_rows: List[Dict[str, object]],
    inventory_rows: List[Dict[str, object]],
    projection_rows: List[Dict[str, object]],
    intake_rows: List[Dict[str, object]],
) -> List[Dict[str, object]]:
    sources_ok = all(row.get("local_path_exists") is True and row.get("needle_found") is True for row in source_rows)
    inventory_written = any(row.get("signature_id") == "PAI4476_5_verdict" for row in inventory_rows)
    inventory_signed = any(row.get("signature_id") == "PAI4476_5_verdict" and row.get("parent_signed") is True for row in inventory_rows)
    projection_map_written = all(
        any(row.get("map_id") == map_id for row in projection_rows)
        for map_id in [
            "PMAP4476_1_curvature_square",
            "PMAP4476_3_source_measure",
            "PMAP4476_4_em_or_stress",
            "PMAP4476_6_boundary_interface",
            "PMAP4476_7_no_cancellation_envelope",
        ]
    )
    intake_ready = all(
        "MISSING" not in str(row.get("current_value")) and row.get("status") != "BLOCKED_SOURCE_READY"
        for row in intake_rows
    )
    no_claims = all(
        str(row.get("valid_for_claim")).lower() == "false"
        for group in [source_rows, inventory_rows, projection_rows, intake_rows]
        for row in group
    )
    return [
        {
            "gate_id": "CG4476_0_sources",
            "claim": "all cited local sources exist and needles are found",
            "gate_pass": sources_ok,
            "claim_allowed": False,
            "detail": "source register validates 4475 handoff and 4474 marker residual channels",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4476_1_inventory_signature_written",
            "claim": "parent action inventory signature is explicit",
            "gate_pass": inventory_written,
            "claim_allowed": False,
            "detail": "Pi_{I_M}(S_bulk)=0 is the required signature",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4476_2_inventory_parent_signed",
            "claim": "MTS parent signs the marker ideal is empty",
            "gate_pass": inventory_signed,
            "claim_allowed": False,
            "detail": "action alphabet, readout compartment and escape routes remain unsigned",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4476_3_projection_map_written",
            "claim": "finite lambda_M projection map is written",
            "gate_pass": projection_map_written,
            "claim_allowed": False,
            "detail": "projection covers c_R2, source-measure, stress/EM, scalar/current, boundary and no-cancellation channels",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4476_4_projection_values_ready",
            "claim": "finite projection values are numeric/source ready",
            "gate_pass": intake_ready,
            "claim_allowed": False,
            "detail": "projection intake rows still need parent inventory or marker moments/projectors/normalizations",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4476_5_no_generated_claim_rows",
            "claim": "no generated row is promoted to public/local-GR evidence",
            "gate_pass": no_claims,
            "claim_allowed": False,
            "detail": "4476 is an inventory signature plus projection map checkpoint",
            "valid_for_claim": False,
        },
    ]
