from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUN_SLUG = "parent-action-minimality-no-extension-theorem-attempt"
CHECKPOINT_DOC = "423-parent-action-minimality-no-extension-theorem-attempt.md"
STATUS = "parent_action_minimality_no_extension_attempt_written_fixed_spurions_excluded_but_material_extensions_not_parent_forbidden_no_local_GR_pass"
CLAIM_CEILING = "parent_action_minimality_no_extension_attempt_only_no_WEP_EH_Newton_PPN_fifth_force_flux_domain_or_local_GR_pass"
NEXT_TARGET = "424-same-frame-EH-source-Poisson-reduction-gate.md"


SOURCE_DOCS = [
    {
        "path": "338-action-level-exact-readout-gate.md",
        "role": "source-at-zero/readout versus physical spurion distinction",
    },
    {
        "path": "339-Pactive-boundary-observable-Ward-gate.md",
        "role": "active projector as boundary observable versus material marker",
    },
    {
        "path": "340-full-cell-equivalence-gauge-redundancy-gate.md",
        "role": "gauge label redundancy and material marker counterexample",
    },
    {
        "path": "341-indistinguishable-cell-quotient-parent-action-gate.md",
        "role": "strict quotient excludes fixed active labels but admits marker-extended quotient",
    },
    {
        "path": "342-finite-fibre-basis-relabeling-gate.md",
        "role": "basis-free finite fibre and marker-extended fibre split",
    },
    {
        "path": "382-parent-local-action-minimal-contract.md",
        "role": "minimal local parent-action contract and residual policy",
    },
    {
        "path": "384-parent-action-first-variation-obstruction-map.md",
        "role": "first-variation obstruction from observed-coframe pullback",
    },
    {
        "path": "407-primitive-relational-quotient-action-sketch.md",
        "role": "configuration-space sketch and no-marker theorem gap",
    },
    {
        "path": "413-no-marker-parent-action-theorem-attempt.md",
        "role": "fixed spurion partial theorem and material marker failure",
    },
    {
        "path": "414-local-quotient-invariant-algebra-triviality-gate.md",
        "role": "local invariant algebra triviality burden",
    },
    {
        "path": "422-matter-functor-blindness-readout-after-variation-theorem-attempt.md",
        "role": "matter/readout no-cheat contract and no-extension target",
    },
    {
        "path": "runs/20260602-051500-local-runner-v4-derived-vs-closure-queue/results/runner_v4_matrix.csv",
        "role": "runner-v4 row states for no-promotion audit",
    },
]


MINIMALITY_REQUIREMENTS = [
    {
        "requirement": "primitive_universal_property",
        "symbolic_form": "Q_MTS is the free/minimal quotient object generated by motion-time-space primitives",
        "current_status": "not_derived",
        "why_needed": "without it, Q_tilde=(Q,m)/G_rel is a legal extended parent configuration",
        "rows_at_risk": "R0;R1;R10;R11",
    },
    {
        "requirement": "closed_parent_field_list",
        "symbolic_form": "Conf_parent = {Q_MTS,e_obs,h,J_rel,...}/G with no external material objects",
        "current_status": "contract_only",
        "why_needed": "otherwise extra marker fields can be appended consistently",
        "rows_at_risk": "R0;R1;R2;R5",
    },
    {
        "requirement": "no_natural_marker_functor",
        "symbolic_form": "No nonconstant natural transformation M: Q_MTS -> Marker beyond Obs(Q) and constants",
        "current_status": "not_derived",
        "why_needed": "a covariant marker is not killed by quotient covariance",
        "rows_at_risk": "R0;R1;R8;R10",
    },
    {
        "requirement": "extension_variation_tax",
        "symbolic_form": "Every added field m has E_m=0, T_munu[m], and matter/source vertices tracked",
        "current_status": "retained_policy_written",
        "why_needed": "prevents hidden extensions from earning theorem-zero credit",
        "rows_at_risk": "R1;R2;R7;R9;R10",
    },
    {
        "requirement": "pure_gauge_or_auxiliary_exception",
        "symbolic_form": "m is safe only if gauge, algebraic with unique universal m0, or topological with no local stress",
        "current_status": "conditional_only",
        "why_needed": "some extensions can be harmless, but only after their variation is owned",
        "rows_at_risk": "R1;R10;R11",
    },
    {
        "requirement": "readout_not_parent_field",
        "symbolic_form": "P_read in R_read: Sol(S_parent)->Obs, not in Conf_parent",
        "current_status": "conditional_contract_from_422",
        "why_needed": "post-readout EFT can reintroduce active labels through the action",
        "rows_at_risk": "R0;R1;R5;R11",
    },
    {
        "requirement": "local_invariant_algebra_closure",
        "symbolic_form": "I_loc(Q)=I_geom[J^k(e_obs)] tensor universal constants",
        "current_status": "not_derived",
        "why_needed": "quotient-invariant scalars can act as material markers",
        "rows_at_risk": "R1;R2;R5;R10",
    },
    {
        "requirement": "same_frame_EH_source_after_minimality",
        "symbolic_form": "S_EH and S_matter vary the same observed frame with constant kappa",
        "current_status": "separate_open_gate",
        "why_needed": "no-extension alone does not prove GR/Newton",
        "rows_at_risk": "R3;R4;R9;R11",
    },
]


EXTENSION_TAXONOMY = [
    {
        "extension_type": "fixed_active_spurion",
        "symbolic_form": "P_active fixed in S_parent",
        "admissibility": "excluded_if_strict_quotient_parent_is_proven",
        "local_effect": "fixed labels are non-orbit functions",
        "verdict": "conditional_exclusion",
    },
    {
        "extension_type": "transforming_material_marker",
        "symbolic_form": "m -> g.m, Q_tilde=(Q,m)/G_rel",
        "admissibility": "legal_extended_theory",
        "local_effect": "covariance preserved while marker-local terms become allowed",
        "verdict": "not_forbidden_without_no_extension_theorem",
    },
    {
        "extension_type": "pure_gauge_marker",
        "symbolic_form": "m = gauge representative, E_m first-class constraint",
        "admissibility": "safe_if_constraint_derived",
        "local_effect": "no independent local observable",
        "verdict": "conditional_safe",
    },
    {
        "extension_type": "universal_auxiliary_marker",
        "symbolic_form": "delta S/delta m=0 -> m=m0 universal",
        "admissibility": "safe_if_unique_source_independent_solution_derived",
        "local_effect": "renormalizes constants only",
        "verdict": "conditional_safe_not_derived",
    },
    {
        "extension_type": "topological_boundary_marker",
        "symbolic_form": "m in H_rel or boundary class with metric-independent action",
        "admissibility": "safe_if_no_local_stress_and_no_matter_vertex",
        "local_effect": "can carry exchange/class data if not silenced",
        "verdict": "conditional_or_retained",
    },
    {
        "extension_type": "readout_probe",
        "symbolic_form": "P_read applied to solutions only",
        "admissibility": "allowed_after_variation",
        "local_effect": "observable extraction, not source term",
        "verdict": "conditional_safe",
    },
    {
        "extension_type": "post_readout_EFT",
        "symbolic_form": "S_red[P_read Q] varied as action",
        "admissibility": "forbidden_for_theorem_zero",
        "local_effect": "active/projector counterterms return",
        "verdict": "closure_or_retained_only",
    },
    {
        "extension_type": "species_constant_marker",
        "symbolic_form": "theta_A(m), q_A(I_Q), sigma_A C_D O_A",
        "admissibility": "legal_unless_universality_theorem",
        "local_effect": "WEP/source-charge/clock pressure",
        "verdict": "retained",
    },
]


UNIVERSAL_PROPERTY_ROUTES = [
    {
        "route": "minimal_configuration_axiom",
        "mechanism": "declare the parent configuration to be the minimal quotient generated by M/T/S primitives",
        "strength": "clean and usable as closure",
        "failure": "definition/axiom, not derivation from existing parent variation",
        "status": "closure_only",
    },
    {
        "route": "categorical_initial_object",
        "mechanism": "prove Q_MTS is initial/free in a category of relational motion-time-space observables",
        "strength": "would be a real no-extension theorem",
        "failure": "category, morphisms, and universal proof not present in corpus",
        "status": "not_derived",
    },
    {
        "route": "no_natural_marker_transformation",
        "mechanism": "show all natural local maps from Q_MTS are functions of e_obs and constants",
        "strength": "directly kills covariant material markers",
        "failure": "local invariant algebra still has extra generators",
        "status": "not_derived",
    },
    {
        "route": "first_class_constraint_owner",
        "mechanism": "derive gauge constraints whose orbits include every candidate marker",
        "strength": "turns marker into pure gauge",
        "failure": "no such full constraint algebra has been derived",
        "status": "not_derived",
    },
    {
        "route": "extension_variation_tax",
        "mechanism": "any new marker is allowed only as retained sector with stress/source/PPN budget",
        "strength": "prevents cheating and keeps runner honest",
        "failure": "does not forbid extension; only demotes it",
        "status": "pass_as_policy",
    },
    {
        "route": "empirical_no_new_sector_fit",
        "mechanism": "bound marker coefficients with WEP/PPN/local/fifth-force data",
        "strength": "testable",
        "failure": "empirical smallness is not a derivation of no-extension",
        "status": "future_test_not_theorem",
    },
]


CONDITIONAL_NO_EXTENSION_CHAIN = [
    {
        "step": 1,
        "claim": "The parent object is defined by a primitive universal property, not by a convenient field list.",
        "identity": "Q_MTS = FreeRel(M,T,S)/G_rel or equivalent",
        "status": "not_derived",
    },
    {
        "step": 2,
        "claim": "Allowed action terms are natural/local class functions of Q_MTS and observed geometry.",
        "identity": "S_parent = S[Q_MTS, Obs(Q_MTS), universal constants]",
        "status": "contract_only",
    },
    {
        "step": 3,
        "claim": "A fixed active spurion is not a function on the quotient.",
        "identity": "P_active not invariant under relabeling/representative changes",
        "status": "conditional_pass_if_strict_quotient",
    },
    {
        "step": 4,
        "claim": "A transforming material marker is an extension, not a quotient representative.",
        "identity": "Q_tilde=(Q_MTS,m)/G_rel adds independent invariant generators",
        "status": "pass_as_classification",
    },
    {
        "step": 5,
        "claim": "All nontrivial extensions must be varied and retained.",
        "identity": "E_m=0, T_munu[m], q_A(m), fifth-force/source terms enter residual ledger",
        "status": "pass_as_guardrail",
    },
    {
        "step": 6,
        "claim": "Only pure gauge, universal auxiliary, or stress-free topological extensions can be harmless.",
        "identity": "m gauge or m=m0 universal or delta_g S_m=delta_psi S_m=0",
        "status": "conditional_not_derived",
    },
    {
        "step": 7,
        "claim": "Therefore material markers are absent from the local branch.",
        "identity": "No m with independent matter-visible invariant remains",
        "status": "not_proven",
    },
]


COUNTEREXAMPLE_EXTENSIONS = [
    {
        "counterexample": "co_moving_marker_field",
        "symbolic_form": "Q_tilde=(Q,m(x))/G_rel, S includes f(m)T",
        "why_it_survives": "covariant extension descends to an extended quotient",
        "required_blocker": "universal-property no-extension theorem",
    },
    {
        "counterexample": "transforming_active_projector",
        "symbolic_form": "P_active(x) -> g P_active g^-1",
        "why_it_survives": "formal covariance is preserved while active-local terms are legal",
        "required_blocker": "readout-only proof plus no material defect",
    },
    {
        "counterexample": "post_readout_reduced_action",
        "symbolic_form": "S_red[P_read Q] varied after projection",
        "why_it_survives": "effective reduction can be written unless parent forbids backreaction",
        "required_blocker": "exact readout-after-variation theorem",
    },
    {
        "counterexample": "species_class_spurion",
        "symbolic_form": "sigma_A I_Q O_A or theta_A(m)",
        "why_it_survives": "species constants can be quotient-invariant but nonuniversal",
        "required_blocker": "constant-sector universality theorem",
    },
    {
        "counterexample": "domain_class_marker",
        "symbolic_form": "lambda chi_D T or lambda H_rel T",
        "why_it_survives": "domain/class scalars are quotient-invariant extra generators",
        "required_blocker": "local invariant algebra triviality and physical class selection",
    },
    {
        "counterexample": "source_dependent_auxiliary_marker",
        "symbolic_form": "delta S/delta m=0 -> m=m0 + T/M^2",
        "why_it_survives": "auxiliary field exists but is not universal",
        "required_blocker": "source-independent universal auxiliary solution",
    },
    {
        "counterexample": "separate_matter_metric_marker",
        "symbolic_form": "S_EH[g] + S_matter[exp(F(m))g]",
        "why_it_survives": "one can keep covariance while splitting source and geometry frames",
        "required_blocker": "same-frame EH/source theorem",
    },
]


ROW_IDS = [
    "R0_identity_coframe_direct",
    "R1_WEP_source_charge",
    "R2_clock_redshift",
    "R3_gamma",
    "R4_beta",
    "R5_alpha1",
    "R6_alpha2",
    "R7_alpha3",
    "R8_xi",
    "R9_Gdot",
    "R10_fifth_force",
    "R11_EH_operator_ledger",
]


DECISION = [
    {
        "decision": (
            "The no-extension route gains a sharper result but not a local-GR derivation. Fixed active spurions can be "
            "excluded conditionally by strict quotient logic, and every genuine marker extension must now pay an explicit "
            "variation/residual tax. But a covariant material marker Q_tilde=(Q,m)/G_rel remains a legal extended parent "
            "theory unless MTS supplies a universal-property/minimal-configuration theorem proving that Q_MTS is the full "
            "primitive object and that no nonconstant natural marker functor exists. The current corpus does not derive "
            "that theorem. Therefore material-marker absence remains a closure/minimality contract or a retained-sector "
            "policy, not a theorem-zero/local-GR pass."
        )
    }
]


NEXT_QUEUE = [
    {
        "target": "424-same-frame-EH-source-Poisson-reduction-gate.md",
        "reason": "no-extension alone cannot connect to Newton; the next GR bridge is same-frame EH/source to Poisson",
    },
    {
        "target": "424-local-bound-real-data-source-plan.md",
        "reason": "prepare empirical local-bound tests with theorem/closure/retained sectors separated",
    },
    {
        "target": "424-retained-marker-extension-ledger.md",
        "reason": "if no-extension stays closure-only, every allowed marker needs a retained coefficient and lock",
    },
]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def source_register_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source_doc in SOURCE_DOCS:
        source_path = ROOT / source_doc["path"]
        rows.append(
            {
                "source_file": source_doc["path"],
                "role": source_doc["role"],
                "exists": source_path.exists(),
            }
        )
    return rows


def runner_v4_rows() -> list[dict[str, str]]:
    return read_csv(ROOT / "runs/20260602-051500-local-runner-v4-derived-vs-closure-queue/results/runner_v4_matrix.csv")


def row_transition_rows() -> list[dict[str, Any]]:
    matrix_by_id = {row["row_id"]: row for row in runner_v4_rows()}
    reasons = {
        "R0_identity_coframe_direct": "fixed spurion exclusion is conditional; material-marker extensions remain legal",
        "R1_WEP_source_charge": "species/class/marker constants remain retained without no-extension and universality",
        "R2_clock_redshift": "marker-dependent clock constants remain possible",
        "R3_gamma": "no-extension does not select EH-only same-frame exterior",
        "R4_beta": "source normalization and nonlinear marker/source hair remain open",
        "R5_alpha1": "domain/readout marker extensions can create preferred-frame leakage",
        "R6_alpha2": "normal/vector marker extensions remain possible without full constraint algebra",
        "R7_alpha3": "boundary marker/exchange extensions remain retained unless Ward-owned",
        "R8_xi": "domain/class marker can source preferred-location terms",
        "R9_Gdot": "marker-dependent constants and measured-GM drift remain retained",
        "R10_fifth_force": "material marker fields can mediate finite-range or composition-dependent forces",
        "R11_EH_operator_ledger": "minimality does not derive metric-only second-order EH operator content",
    }
    rows: list[dict[str, Any]] = []
    for row_id in ROW_IDS:
        previous_state = matrix_by_id.get(row_id, {}).get("runner_v4_state", "missing")
        rows.append(
            {
                "row_id": row_id,
                "previous_state": previous_state,
                "new_state": previous_state,
                "result": "not_upgraded",
                "reason": reasons[row_id],
                "theorem_credit": False,
                "claim_allowed": False,
            }
        )
    return rows


def gate_rows(
    source_rows: list[dict[str, Any]],
    transition_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    missing_sources = [row for row in source_rows if not row["exists"]]
    theorem_rows = [row for row in transition_rows if row["theorem_credit"]]
    claim_rows = [row for row in transition_rows if row["claim_allowed"]]
    return [
        {
            "gate": "source_paths_exist",
            "status": "pass" if not missing_sources else "fail",
            "evidence": "all cited source paths exist" if not missing_sources else f"{len(missing_sources)} missing source paths",
        },
        {
            "gate": "minimality_requirements_written",
            "status": "pass",
            "evidence": f"{len(MINIMALITY_REQUIREMENTS)} minimality requirements recorded",
        },
        {
            "gate": "extension_taxonomy_written",
            "status": "pass",
            "evidence": f"{len(EXTENSION_TAXONOMY)} extension classes classified",
        },
        {
            "gate": "fixed_spurion_excluded_if_strict_quotient",
            "status": "conditional_pass",
            "evidence": "fixed P_active is not an admissible strict quotient function",
        },
        {
            "gate": "extension_variation_tax_enforced",
            "status": "pass",
            "evidence": "nontrivial marker extensions are demoted to retained sectors",
        },
        {
            "gate": "conditional_no_extension_chain_written",
            "status": "conditional_pass",
            "evidence": "universal-property no-extension theorem shape stated",
        },
        {
            "gate": "parent_universal_property_derived",
            "status": "fail",
            "evidence": "no proof that Q_MTS is the free/minimal primitive quotient object",
        },
        {
            "gate": "no_natural_marker_theorem_derived",
            "status": "fail",
            "evidence": "no theorem excluding nonconstant natural marker functors",
        },
        {
            "gate": "material_marker_extension_blocked",
            "status": "fail",
            "evidence": "Q_tilde=(Q,m)/G_rel remains a legal extended theory",
        },
        {
            "gate": "local_invariant_algebra_triviality_derived",
            "status": "fail",
            "evidence": "extra quotient-invariant generators remain from checkpoint 414",
        },
        {
            "gate": "auxiliary_universal_integration_derived",
            "status": "fail",
            "evidence": "marker fields are not proven gauge, universal auxiliary, or stress-free topological",
        },
        {
            "gate": "runner_rows_promoted_to_theorem_zero",
            "status": "fail",
            "evidence": f"{len(theorem_rows)} theorem-credit row upgrades",
        },
        {
            "gate": "claim_leaks",
            "status": "pass" if not claim_rows else "fail",
            "evidence": f"{len(claim_rows)} claim-allowed rows",
        },
        {
            "gate": "local_GR_promoted",
            "status": "fail",
            "evidence": "minimality/no-extension attempt only; no local-GR/Newton pass",
        },
        {
            "gate": "claim_ceiling_enforced",
            "status": "pass",
            "evidence": CLAIM_CEILING,
        },
    ]


def md_cell(value: Any) -> str:
    return str(value).replace("|", ";")


def markdown_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        body.append("| " + " | ".join(md_cell(row[column]) for column in columns) + " |")
    return "\n".join([header, separator, *body])


def write_checkpoint_markdown(
    run_dir: Path,
    transition_rows: list[dict[str, Any]],
    gate_result_rows: list[dict[str, Any]],
) -> None:
    requirement_table_rows = [
        {
            "requirement": row["requirement"],
            "current_status": row["current_status"],
            "why_needed": row["why_needed"],
            "rows_at_risk": row["rows_at_risk"],
        }
        for row in MINIMALITY_REQUIREMENTS
    ]
    taxonomy_table_rows = [
        {
            "extension_type": row["extension_type"],
            "admissibility": row["admissibility"],
            "local_effect": row["local_effect"],
            "verdict": row["verdict"],
        }
        for row in EXTENSION_TAXONOMY
    ]
    route_table_rows = [
        {
            "route": row["route"],
            "status": row["status"],
            "failure": row["failure"],
        }
        for row in UNIVERSAL_PROPERTY_ROUTES
    ]
    chain_table_rows = [
        {
            "step": row["step"],
            "claim": row["claim"],
            "status": row["status"],
        }
        for row in CONDITIONAL_NO_EXTENSION_CHAIN
    ]
    counterexample_table_rows = [
        {
            "counterexample": row["counterexample"],
            "why_it_survives": row["why_it_survives"],
            "required_blocker": row["required_blocker"],
        }
        for row in COUNTEREXAMPLE_EXTENSIONS
    ]
    transition_table_rows = [
        {
            "row_id": row["row_id"],
            "previous_state": row["previous_state"],
            "new_state": row["new_state"],
            "result": row["result"],
        }
        for row in transition_rows
    ]
    gate_table_rows = [
        {
            "gate": row["gate"],
            "status": row["status"],
            "evidence": row["evidence"],
        }
        for row in gate_result_rows
    ]
    text = f"""# 423 - Parent-Action Minimality / No-Extension Theorem Attempt

Private no-extension/local-GR checkpoint. This is not a public WEP, Einstein-Hilbert, Newtonian-limit, PPN, fifth-force, flux, domain, cosmology, or unified-field claim.

## 1. Purpose

Checkpoint 422 gave the exact matter/readout no-cheat contract, but left the hardest loophole: why is a material marker extension not allowed in the parent action? This checkpoint tests whether no-extension can be derived, or whether it remains a closure/minimality contract.

## 2. Run Manifest

| Item | Value |
| --- | --- |
| Script | `scripts/parent_action_minimality_no_extension_theorem_attempt.py` |
| Run directory | `runs/{run_dir.name}` |
| Status | `{STATUS}` |
| Claim ceiling | `{CLAIM_CEILING}` |
| Next target | `{NEXT_TARGET}` |

## 3. Minimality Requirements

{markdown_table(requirement_table_rows, ["requirement", "current_status", "why_needed", "rows_at_risk"])}

## 4. Extension Taxonomy

{markdown_table(taxonomy_table_rows, ["extension_type", "admissibility", "local_effect", "verdict"])}

## 5. Universal-Property Routes

{markdown_table(route_table_rows, ["route", "status", "failure"])}

## 6. Conditional No-Extension Chain

{markdown_table(chain_table_rows, ["step", "claim", "status"])}

Exact theorem target:

```text
If Q_MTS is the free/minimal primitive quotient object generated by motion-time-space,
if every allowed action term is a natural/local class function of Q_MTS, Obs(Q_MTS), and universal constants,
and if every candidate marker m is either pure gauge, a universal auxiliary constant, or absent from Conf_parent,
then no material marker extension can contribute to local matter pullback, WEP/source charge, clock drift, or fifth-force rows.
```

The current corpus does not yet prove the universal property or the no-natural-marker theorem.

## 7. Counterexample Extensions

{markdown_table(counterexample_table_rows, ["counterexample", "why_it_survives", "required_blocker"])}

## 8. Row Transition Attempt

{markdown_table(transition_table_rows, ["row_id", "previous_state", "new_state", "result"])}

## 9. Gate Results

{markdown_table(gate_table_rows, ["gate", "status", "evidence"])}

## 10. Decision

{DECISION[0]["decision"]}

Practical read: this is not grim; it is clarifying. We can now say exactly what would have to make MTS unlike a patchwork EFT: the parent configuration must be primitive-minimal, not merely chosen minimal by taste. Until that is derived, marker absence is an explicit closure contract and every extension pays the retained-row tax.

## 11. Next Target

`{NEXT_TARGET}`
"""
    (ROOT / CHECKPOINT_DOC).write_text(text, encoding="utf-8")


def write_run(timestamp: str) -> Path:
    run_dir = ROOT / "runs" / f"{timestamp}-{RUN_SLUG}"
    results_dir = run_dir / "results"
    source_rows = source_register_rows()
    transition_rows = row_transition_rows()
    gate_result_rows = gate_rows(source_rows, transition_rows)

    write_csv(results_dir / "source_register.csv", source_rows)
    write_csv(results_dir / "minimality_requirements.csv", MINIMALITY_REQUIREMENTS)
    write_csv(results_dir / "extension_taxonomy.csv", EXTENSION_TAXONOMY)
    write_csv(results_dir / "universal_property_routes.csv", UNIVERSAL_PROPERTY_ROUTES)
    write_csv(results_dir / "conditional_no_extension_chain.csv", CONDITIONAL_NO_EXTENSION_CHAIN)
    write_csv(results_dir / "counterexample_extensions.csv", COUNTEREXAMPLE_EXTENSIONS)
    write_csv(results_dir / "row_transition_attempt.csv", transition_rows)
    write_csv(results_dir / "gate_results.csv", gate_result_rows)
    write_csv(results_dir / "decision.csv", DECISION)
    write_csv(results_dir / "next_queue.csv", NEXT_QUEUE)

    missing_sources = [row["source_file"] for row in source_rows if not row["exists"]]
    status = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": STATUS,
        "claim_ceiling": CLAIM_CEILING,
        "run_dir": str(run_dir),
        "source_paths_missing": len(missing_sources),
        "missing_sources": missing_sources,
        "minimality_requirements": len(MINIMALITY_REQUIREMENTS),
        "extension_taxonomy_written": True,
        "fixed_spurion_excluded_if_strict_quotient": True,
        "extension_variation_tax_enforced": True,
        "conditional_no_extension_chain_written": True,
        "parent_universal_property_derived": False,
        "no_natural_marker_theorem_derived": False,
        "material_marker_extension_blocked": False,
        "local_invariant_algebra_triviality_derived": False,
        "auxiliary_universal_integration_derived": False,
        "theorem_zero_upgrades": 0,
        "claim_allowed_rows": 0,
        "local_GR_claim_allowed": False,
        "checkpoint_doc": CHECKPOINT_DOC,
        "next_target": NEXT_TARGET,
    }
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    (run_dir / "DONE.txt").write_text(f"{STATUS}\n", encoding="utf-8")
    write_checkpoint_markdown(run_dir, transition_rows, gate_result_rows)
    return run_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Write checkpoint 423 parent-action minimality/no-extension theorem attempt artifacts."
    )
    parser.add_argument(
        "--timestamp",
        default=datetime.now().strftime("%Y%m%d-%H%M%S"),
        help="Run timestamp prefix.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_dir = write_run(args.timestamp)
    print(json.dumps({"status": STATUS, "run_dir": str(run_dir)}, indent=2))


if __name__ == "__main__":
    main()
