from __future__ import annotations

import argparse
import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
RUN_SLUG = "relative-current-boundary-generator-theorem-attempt"
CHECKPOINT_DOC = "420-relative-current-boundary-generator-theorem-attempt.md"
STATUS = "relative_current_boundary_generator_theorem_attempt_written_formal_candidate_generation_possible_but_physical_representative_and_Bianchi_open_no_local_GR_pass"
CLAIM_CEILING = "relative_current_boundary_generator_theorem_attempt_only_no_WEP_EH_Newton_PPN_fifth_force_flux_domain_or_local_GR_pass"
NEXT_TARGET = "421-finite-fibre-spectrum-decoupling-theorem-attempt.md"


SOURCE_DOCS = [
    {
        "path": "365-lifted-C-boundary-primitive-and-domain-Euler-equation.md",
        "role": "relative class admissibility and physical class selection gap",
    },
    {
        "path": "415-local-trivial-class-selector-theorem-attempt.md",
        "role": "conditional local zero-class theorem",
    },
    {
        "path": "417-boundary-exchange-nohair-theorem-attempt.md",
        "role": "boundary exchange no-hair routes and retained fallback",
    },
    {
        "path": "418-Cexp-domain-candidate-generator.md",
        "role": "candidates-first C_exp contract",
    },
    {
        "path": "419-boundary-exchange-coefficient-retained-evaluator.md",
        "role": "retained exchange coefficient fallback",
    },
    {
        "path": "71-relative-boundary-current-construction-attempt.md",
        "role": "formal relative current construction",
    },
    {
        "path": "72-relative-current-action-owner-attempt.md",
        "role": "relative-current action owner attempt and selection failure",
    },
    {
        "path": "runs/20260531-113439-relative-boundary-current-construction-attempt/results/construction_chain.csv",
        "role": "relative current construction chain",
    },
    {
        "path": "runs/20260531-113439-relative-boundary-current-construction-attempt/results/closure_tests.csv",
        "role": "local/FLRW relative current closure tests",
    },
    {
        "path": "runs/20260531-113439-relative-boundary-current-construction-attempt/results/stress_safety_ledger.csv",
        "role": "relative current stress safety ledger",
    },
    {
        "path": "runs/20260531-113740-relative-current-action-owner-attempt/results/selection_tests.csv",
        "role": "relative current action selection tests",
    },
    {
        "path": "runs/20260602-072500-Cexp-domain-candidate-generator/results/candidate_domain_sources.csv",
        "role": "candidate domain source register",
    },
    {
        "path": "runs/20260602-051500-local-runner-v4-derived-vs-closure-queue/results/runner_v4_matrix.csv",
        "role": "runner-v4 row states",
    },
]


GENERATOR_REQUIREMENTS = [
    {
        "requirement": "parent_owned_relative_pair",
        "symbolic_form": "J_rel=(j_3,b_2) appears in S_parent, not hand-inserted",
        "current_status": "formal_action_route_only",
        "missing": "physical representative and Bianchi completion",
    },
    {
        "requirement": "closed_relative_current",
        "symbolic_form": "d_rel J_rel=(d j_3, i_star j_3-d_boundary b_2)=0",
        "current_status": "formal_pass_with_multiplier",
        "missing": "does not select local-zero versus FLRW-nonzero class",
    },
    {
        "requirement": "candidate_boundary_rule",
        "symbolic_form": "partial D_i generated by support, exactness, or cycles of J_rel",
        "current_status": "written_here_as_contract",
        "missing": "parent proof that this is the admissible candidate family",
    },
    {
        "requirement": "finite_or_integrable_candidate_measure",
        "symbolic_form": "{D_i} or dmu(D|J_rel) well-defined before C_exp scoring",
        "current_status": "not_derived",
        "missing": "measure/compactness/regularity theorem",
    },
    {
        "requirement": "physical_representative_selection",
        "symbolic_form": "local D_i has [J_rel]=0 while FLRW D_i may have [J_rel]!=0",
        "current_status": "not_derived",
        "missing": "single parent local/FLRW selector",
    },
    {
        "requirement": "stress_safe_boundary",
        "symbolic_form": "J_rel boundary is topological/exact bookkeeping, not metric wall stress",
        "current_status": "conditional_only",
        "missing": "metric variation/Bianchi proof",
    },
    {
        "requirement": "C_exp_after_generation",
        "symbolic_form": "D_i first, then C_exp[D_i]",
        "current_status": "contract_pass",
        "missing": "full parent generator theorem",
    },
]


CANDIDATE_GENERATION_ROUTES = [
    {
        "route": "support_components_of_Jrel",
        "candidate_rule": "D_i are connected components/collars of support(j_3) or support(b_2)",
        "strength": "non-posthoc and current-based",
        "failure": "support can be empty, singular, nonunique, or not a physical bound domain",
    },
    {
        "route": "exact_zero_local_components",
        "candidate_rule": "D_i where j_3=d a_2 and b_2=d_boundary a_1 or both vanish",
        "strength": "matches local trivial class route",
        "failure": "requires local exact representative already selected",
    },
    {
        "route": "relative_cycle_boundaries",
        "candidate_rule": "partial D_i are representatives of relative cycles/classes",
        "strength": "topological and stress-safe in principle",
        "failure": "closed class can be nonzero; class selection remains open",
    },
    {
        "route": "transition_exchange_shells",
        "candidate_rule": "D_i bounded by shells where b_2 carries local-to-FLRW exchange",
        "strength": "honestly tracks exchange instead of hiding it",
        "failure": "shell current feeds retained alpha3/Gdot/domain coefficients unless no-hair is derived",
    },
    {
        "route": "BF_multiplier_integral_surfaces",
        "candidate_rule": "D_i are integral regions compatible with d_rel J_rel=0 from multiplier/BF term",
        "strength": "closest parent-action route",
        "failure": "closure equation does not choose physical representative",
    },
    {
        "route": "metric_surface_stress_boundaries",
        "candidate_rule": "D_i generated by physical wall action extrema",
        "strength": "variationally concrete",
        "failure": "dangerous local stress/fifth-force route; rejected for theorem-zero",
    },
]


CONDITIONAL_THEOREM_CHAIN = [
    {
        "step": 1,
        "claim": "Parent action supplies a relative current pair.",
        "identity": "S_parent contains J_rel=(j_3,b_2) and variation gives d_rel J_rel=0",
        "status": "formal_possible",
    },
    {
        "step": 2,
        "claim": "J_rel induces admissible candidate regions before scoring.",
        "identity": "G[J_rel] -> {D_i} or dmu(D|J_rel)",
        "status": "conditional_theorem_shape_written",
    },
    {
        "step": 3,
        "claim": "Candidates carry boundary exchange bookkeeping.",
        "identity": "i_star j_3=d_boundary b_2 on partial D_i",
        "status": "formal_closure_possible",
    },
    {
        "step": 4,
        "claim": "Candidate family is finite/integrable and regular.",
        "identity": "sum_i or integral dmu(D|J_rel) well-defined",
        "status": "not_derived",
    },
    {
        "step": 5,
        "claim": "Physical local representative is trivial.",
        "identity": "[J_rel]_{D_local}=0",
        "status": "not_derived",
    },
    {
        "step": 6,
        "claim": "FLRW candidate can remain nontrivial under same rule.",
        "identity": "[J_rel]_{D_FLRW}!=0 allowed for coherent expansion class",
        "status": "contract_only",
    },
    {
        "step": 7,
        "claim": "C_exp scores the parent-generated candidates.",
        "identity": "C_exp[D_i] evaluated after G[J_rel]",
        "status": "contract_pass_not_full_derivation",
    },
]


OBSTRUCTION_TESTS = [
    {
        "test": "closure_not_selection",
        "result": "fail_open",
        "detail": "d_rel J_rel=0 supplies conservation but not local-zero/FLRW-nonzero representative choice",
    },
    {
        "test": "support_not_domain",
        "result": "fail_open",
        "detail": "support of a current may not define physical bound domains or a finite candidate family",
    },
    {
        "test": "topology_not_triviality",
        "result": "fail_open",
        "detail": "relative cycles can be nontrivial; no-defect/trivial-class condition remains open",
    },
    {
        "test": "boundary_exchange_not_silence",
        "result": "fail_open",
        "detail": "transition exchange shells remain retained coefficient sources unless no-hair is proven",
    },
    {
        "test": "metric_wall_stress_rejected",
        "result": "pass_guardrail",
        "detail": "physical surface-stress boundaries cannot earn theorem-zero",
    },
    {
        "test": "Cexp_posthoc_blocked",
        "result": "pass_guardrail",
        "detail": "C_exp can only score candidates generated before residual/data scoring",
    },
]


ROW_TRANSITION_ATTEMPT = [
    {
        "row_id": "R0_identity_coframe_direct",
        "new_state": "closure_zero",
        "reason": "candidate generation does not yet prove no-marker/local trivial class",
    },
    {
        "row_id": "R5_alpha1",
        "new_state": "retained_budget",
        "reason": "candidate boundary vector leakage not theorem-zero",
    },
    {
        "row_id": "R6_alpha2",
        "new_state": "retained_budget",
        "reason": "domain anisotropy/vector representative remains possible",
    },
    {
        "row_id": "R7_alpha3",
        "new_state": "retained_contingent_budget",
        "reason": "transition exchange shells can feed alpha3 unless no-hair/Ward ownership is derived",
    },
    {
        "row_id": "R8_xi",
        "new_state": "retained_budget",
        "reason": "relative/topological preferred-location class remains open",
    },
    {
        "row_id": "R9_Gdot",
        "new_state": "retained_contingent_budget",
        "reason": "candidate exchange/domain drift remains retained",
    },
    {
        "row_id": "R10_fifth_force",
        "new_state": "unscored_parameterized",
        "reason": "metric wall or selector transition route can behave like fifth-force channel",
    },
]


DECISION = [
    {
        "status": STATUS,
        "decision": "Relative-current boundaries can now be stated as a serious candidate-domain generator theorem target: if a parent-owned J_rel=(j_3,b_2) is closed, regular, stress-safe, and equipped with a finite/integrable candidate measure, then candidate domains can be generated before C_exp scoring. This partially repairs the circularity. But the theorem does not yet pass: closure is not physical representative selection, support is not automatically a bound domain, relative topology need not be trivial, and transition exchange remains a retained coefficient source. Therefore this is a candidate-generator contract, not local GR.",
        "candidate_generation_theorem_shape_written": True,
        "parent_candidate_generator_derived": False,
        "physical_representative_selected": False,
        "Bianchi_boundary_exchange_owned": False,
        "theorem_zero_upgrades": 0,
        "local_GR_claim_allowed": False,
        "claim_ceiling": CLAIM_CEILING,
        "next_target": NEXT_TARGET,
    }
]


NEXT_QUEUE = [
    {
        "priority": 1,
        "target": NEXT_TARGET,
        "task": "test whether finite-cell fibre spectra can be integrated out or reduced to universal constants",
        "pass_condition": "finite fibre does not create local matter-visible marker channels",
    },
    {
        "priority": 2,
        "target": "422-local-bounds-real-data-source-plan.md",
        "task": "prepare verified local-bound source intake using the 411 interface",
        "pass_condition": "external local-bound rows can be filled with references and no claim leaks",
    },
    {
        "priority": 3,
        "target": "423-relative-current-candidate-measure-theorem-attempt.md",
        "task": "try to derive finite/integrable measure over J_rel-generated candidate domains",
        "pass_condition": "candidate family is mathematically controlled or closure-labelled",
    },
]


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def source_register_rows() -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source_doc in SOURCE_DOCS:
        source_path = ROOT / source_doc["path"]
        rows.append(
            {
                "source_file": source_doc["path"],
                "exists": source_path.exists(),
                "role": source_doc["role"],
            }
        )
    return rows


def runner_v4_rows() -> list[dict[str, str]]:
    return read_csv(ROOT / "runs/20260602-051500-local-runner-v4-derived-vs-closure-queue/results/runner_v4_matrix.csv")


def row_transition_rows() -> list[dict[str, Any]]:
    matrix_by_id = {row["row_id"]: row for row in runner_v4_rows()}
    rows: list[dict[str, Any]] = []
    for transition in ROW_TRANSITION_ATTEMPT:
        matrix_row = matrix_by_id.get(transition["row_id"], {})
        rows.append(
            {
                "row_id": transition["row_id"],
                "previous_state": matrix_row.get("runner_v4_state", "missing"),
                "new_state": transition["new_state"],
                "result": "not_upgraded",
                "theorem_credit_allowed": False,
                "claim_allowed": False,
                "reason": transition["reason"],
            }
        )
    return rows


def gate_rows(
    source_rows: list[dict[str, Any]],
    transition_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    missing_sources = [row["source_file"] for row in source_rows if not row["exists"]]
    theorem_rows = [row for row in transition_rows if row["theorem_credit_allowed"]]
    claim_rows = [row for row in transition_rows if row["claim_allowed"]]
    return [
        {
            "gate": "source_paths_exist",
            "status": "pass" if not missing_sources else "fail",
            "evidence": ";".join(missing_sources) if missing_sources else "all cited source paths exist",
        },
        {
            "gate": "generator_requirements_written",
            "status": "pass",
            "evidence": f"{len(GENERATOR_REQUIREMENTS)} requirements recorded",
        },
        {
            "gate": "candidate_generation_routes_written",
            "status": "pass",
            "evidence": f"{len(CANDIDATE_GENERATION_ROUTES)} routes classified",
        },
        {
            "gate": "relative_current_candidate_generation_shape",
            "status": "conditional_pass",
            "evidence": "G[J_rel] -> {D_i} before C_exp scoring is stated",
        },
        {
            "gate": "parent_candidate_generator_derived",
            "status": "fail",
            "evidence": "J_rel ownership/candidate measure/regularity not derived",
        },
        {
            "gate": "physical_representative_selected",
            "status": "fail",
            "evidence": "closure does not choose local-zero/FLRW-nonzero representative",
        },
        {
            "gate": "Bianchi_boundary_exchange_owned",
            "status": "fail",
            "evidence": "candidate boundaries do not yet carry fully owned exchange current",
        },
        {
            "gate": "Cexp_posthoc_blocked",
            "status": "pass",
            "evidence": "C_exp scores only after candidate generation",
        },
        {
            "gate": "metric_wall_stress_rejected",
            "status": "pass",
            "evidence": "surface-stress route rejected for theorem-zero",
        },
        {
            "gate": "runner_rows_promoted_to_theorem_zero",
            "status": "fail",
            "evidence": f"{len(theorem_rows)} theorem-credit row upgrades",
        },
        {
            "gate": "claim_leaks",
            "status": "pass" if not claim_rows else "fail",
            "evidence": f"{len(claim_rows)} claim-allowed rows",
        },
        {
            "gate": "local_GR_promoted",
            "status": "fail",
            "evidence": "relative-current boundary generator attempt only; no local-GR pass",
        },
        {
            "gate": "claim_ceiling_enforced",
            "status": "pass",
            "evidence": CLAIM_CEILING,
        },
    ]


def markdown_table(rows: list[dict[str, Any]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        body.append("| " + " | ".join(str(row[column]) for column in columns) + " |")
    return "\n".join([header, separator, *body])


def write_checkpoint_markdown(
    run_dir: Path,
    transition_rows: list[dict[str, Any]],
    gate_result_rows: list[dict[str, Any]],
) -> None:
    requirement_table_rows = [
        {
            "requirement": row["requirement"],
            "status": row["current_status"],
            "missing": row["missing"],
        }
        for row in GENERATOR_REQUIREMENTS
    ]
    route_table_rows = [
        {
            "route": row["route"],
            "strength": row["strength"],
            "failure": row["failure"],
        }
        for row in CANDIDATE_GENERATION_ROUTES
    ]
    chain_table_rows = [
        {
            "step": row["step"],
            "claim": row["claim"],
            "status": row["status"],
        }
        for row in CONDITIONAL_THEOREM_CHAIN
    ]
    test_table_rows = [
        {
            "test": row["test"],
            "result": row["result"],
            "detail": row["detail"],
        }
        for row in OBSTRUCTION_TESTS
    ]
    transition_table_rows = [
        {
            "row_id": row["row_id"],
            "previous_state": row["previous_state"],
            "new_state": row["new_state"],
            "result": row["result"],
        }
        for row in transition_rows
    ]
    gate_table_rows = [
        {
            "gate": row["gate"],
            "status": row["status"],
            "evidence": row["evidence"],
        }
        for row in gate_result_rows
    ]
    text = f"""# 420 - Relative-Current Boundary Generator Theorem Attempt

Private relative-current/domain/local-GR checkpoint. This is not a public WEP, Einstein-Hilbert, Newtonian-limit, PPN, fifth-force, flux, domain, cosmology, or unified-field claim.

## 1. Purpose

Checkpoint 418 required candidate domains before `C_exp[D]` scoring. This checkpoint tests the best non-posthoc source: can the relative current pair `J_rel=(j_3,b_2)` itself generate admissible candidate boundaries?

## 2. Run Manifest

| Item | Value |
| --- | --- |
| Script | `scripts/relative_current_boundary_generator_theorem_attempt.py` |
| Run directory | `runs/{run_dir.name}` |
| Status | `{STATUS}` |
| Claim ceiling | `{CLAIM_CEILING}` |
| Next target | `{NEXT_TARGET}` |

## 3. Generator Requirements

{markdown_table(requirement_table_rows, ["requirement", "status", "missing"])}

## 4. Candidate Generation Routes

{markdown_table(route_table_rows, ["route", "strength", "failure"])}

## 5. Conditional Theorem Chain

{markdown_table(chain_table_rows, ["step", "claim", "status"])}

## 6. Obstruction Tests

{markdown_table(test_table_rows, ["test", "result", "detail"])}

## 7. Row Transition Attempt

{markdown_table(transition_table_rows, ["row_id", "previous_state", "new_state", "result"])}

## 8. Gate Results

{markdown_table(gate_table_rows, ["gate", "status", "evidence"])}

## 9. Decision

{DECISION[0]["decision"]}

Practical read: this partially repairs the domain-candidate problem, but it does not yet select the physical local representative. `J_rel` can draw a theory-native candidate map; it cannot yet tell us which local box is the GR one without the next theorem.

## 10. Next Target

`{NEXT_TARGET}`
"""
    (ROOT / CHECKPOINT_DOC).write_text(text, encoding="utf-8")


def write_run(timestamp: str) -> Path:
    run_dir = ROOT / "runs" / f"{timestamp}-{RUN_SLUG}"
    results_dir = run_dir / "results"
    source_rows = source_register_rows()
    transition_rows = row_transition_rows()
    gate_result_rows = gate_rows(source_rows, transition_rows)

    write_csv(results_dir / "source_register.csv", source_rows)
    write_csv(results_dir / "generator_requirements.csv", GENERATOR_REQUIREMENTS)
    write_csv(results_dir / "candidate_generation_routes.csv", CANDIDATE_GENERATION_ROUTES)
    write_csv(results_dir / "conditional_theorem_chain.csv", CONDITIONAL_THEOREM_CHAIN)
    write_csv(results_dir / "obstruction_tests.csv", OBSTRUCTION_TESTS)
    write_csv(results_dir / "row_transition_attempt.csv", transition_rows)
    write_csv(results_dir / "gate_results.csv", gate_result_rows)
    write_csv(results_dir / "decision.csv", DECISION)
    write_csv(results_dir / "next_queue.csv", NEXT_QUEUE)

    missing_sources = [row["source_file"] for row in source_rows if not row["exists"]]
    status = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "status": STATUS,
        "claim_ceiling": CLAIM_CEILING,
        "run_dir": str(run_dir),
        "source_paths_missing": len(missing_sources),
        "missing_sources": missing_sources,
        "candidate_generation_theorem_shape_written": True,
        "parent_candidate_generator_derived": False,
        "physical_representative_selected": False,
        "Bianchi_boundary_exchange_owned": False,
        "theorem_zero_upgrades": 0,
        "claim_allowed_rows": 0,
        "local_GR_claim_allowed": False,
        "checkpoint_doc": CHECKPOINT_DOC,
        "next_target": NEXT_TARGET,
    }
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "status.json").write_text(json.dumps(status, indent=2), encoding="utf-8")
    (run_dir / "DONE.txt").write_text(f"{STATUS}\n", encoding="utf-8")
    write_checkpoint_markdown(run_dir, transition_rows, gate_result_rows)
    return run_dir


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Write checkpoint 420 relative-current boundary generator theorem attempt artifacts."
    )
    parser.add_argument(
        "--timestamp",
        default=datetime.now().strftime("%Y%m%d-%H%M%S"),
        help="Run timestamp prefix.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    run_dir = write_run(args.timestamp)
    print(json.dumps({"status": STATUS, "run_dir": str(run_dir)}, indent=2))


if __name__ == "__main__":
    main()
