from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "source-intake" / "mts_residuals"
FORMALIZATION = ROOT.parent / "formalization-workbench"
DOC = ROOT / "3520-Y5-R2FR-quotient-action-principle-derives-q-normal-form-or-finite-source-bounds.md"
CANONICAL_STATUS = OUT / "P8_EM_quotient_action_derives_q_normal_form_status.csv"


SOURCES: dict[str, dict[str, Any]] = {
    "script_3520": {"path": Path(__file__).resolve(), "role": "3520 generator"},
    "doc_3519": {
        "path": ROOT / "3519-Y5-R2FR-vq-parent-object-language-normal-form-or-source-channel-bound.md",
        "role": "3519 q normal-form handoff",
    },
    "next_3519": {
        "path": OUT / "P8_Y5_R2FR_3519_NEXT_TARGET.csv",
        "role": "3520 target handoff",
    },
    "normal_form_3519": {
        "path": OUT / "P8_Y5_R2FR_3519_PARENT_Q_OBJECT_LANGUAGE_NORMAL_FORM.csv",
        "role": "3519 candidate q object language",
    },
    "operator_inventory_3519": {
        "path": OUT / "P8_Y5_R2FR_3519_FORBIDDEN_OPERATOR_INVENTORY.csv",
        "role": "3519 live operator inventory",
    },
    "quotient_407": {
        "path": ROOT / "407-primitive-relational-quotient-action-sketch.md",
        "role": "primitive relational quotient action sketch",
    },
    "field_quotient_2570": {
        "path": OUT / "P8_Y5_FIELD_QUOTIENT_2570_THEOREM_ATTEMPT.csv",
        "role": "field quotient chain-rule theorem attempt",
    },
    "matter_descent_2570": {
        "path": OUT / "P8_Y5_FIELD_QUOTIENT_2570_MATTER_DESCENT_GATE.csv",
        "role": "matter descent gate",
    },
    "readout_order_2570": {
        "path": OUT / "P8_Y5_FIELD_QUOTIENT_2570_READOUT_ORDER_GATE.csv",
        "role": "variation-before-readout gate",
    },
    "primitive_2623": {
        "path": OUT / "P8_Y5_PRIMITIVE_QUOTIENT_GATE_2623_PRIMITIVE_QUOTIENT_THEOREM_ATTEMPT.csv",
        "role": "primitive quotient theorem attempt",
    },
    "signature_2970": {
        "path": ROOT / "2970-Y5-R2FR-parent-quotient-map-and-basic-matter-action-signature-or-DqZ-JA-coefficient-row-under-AX1090.md",
        "role": "parent quotient/basic matter signature attempt",
    },
    "qmap_3134": {
        "path": OUT / "P8_Y5_R2FR_3134_QUOTIENT_MAP_ATTEMPT.csv",
        "role": "quotient map attempt",
    },
    "double_zero_3112": {
        "path": OUT / "P8_Y5_R2FR_3112_DOUBLE_ZERO_QUOTIENT_ACTION_GATE.csv",
        "role": "double-zero quotient action gate",
    },
    "fiber_theorem_3271": {
        "path": OUT / "P8_Y5_R2FR_3271_QUOTIENT_FIBER_DESCENT_THEOREM.csv",
        "role": "quotient fibre descent theorem",
    },
    "absent_quotient_3449": {
        "path": OUT / "P8_Y5_R2FR_3449_ABSENT_QUOTIENT_ZERO_PROOF.csv",
        "role": "absent quotient zero proof",
    },
}


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def bool_text(value: bool) -> str:
    return "True" if value else "False"


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def source_register_rows() -> list[dict[str, Any]]:
    return [
        {
            "source_id": source_id,
            "path": str(metadata["path"]),
            "exists": bool_text(Path(metadata["path"]).exists()),
            "role": metadata["role"],
            "valid_for_claim": "False",
        }
        for source_id, metadata in SOURCES.items()
    ]


def quotient_action_theorem_rows() -> list[dict[str, Any]]:
    return [
        {
            "theorem_id": "QAP3520_0_principle",
            "claim": "Physical parent actions are functionals on equivalence classes before matter/source variation.",
            "formal_statement": "Let pi: Conf_parent -> Conf_phys be the quotient by representative changes generated by v_q. The quotient action principle is S_parent = pi^* S_phys + dB_basic + S_constraint, with S_constraint first-class and boundary-silent on the local branch.",
            "derivation": "If two representatives are physically indistinguishable, the action phase/stationary equations cannot depend on the representative coordinate without making the representative observable. Therefore the physical action descends to Conf_phys; vertical variation is zero modulo first-class constraints and proper boundary terms.",
            "what_it_proves": "delta_vq S_parent=0 for physical bulk terms; nonbasic q_private source operators are illegal unless q_private is promoted to a physical scalar.",
            "current_status": "EXACT_PRINCIPLE_TO_NORMAL_FORM_THEOREM_NOT_PARENT_SIGNED",
            "fires_now": "False",
            "source_path": str(SOURCES["quotient_407"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "QAP3520_1_basic_local_density",
            "claim": "Any local bulk density in a quotient action must be q-basic or vertically exact/proper.",
            "formal_statement": "For every vertical v_q in ker Dpi, L_vq L_bulk = d alpha_vq or zero. On compact/proper local variations with alpha_vq boundary-silent, the Euler contraction E(L_bulk)(v_q)=0.",
            "derivation": "This is the variational form of descent: L_bulk = pi^* L_phys plus exact terms. Contracting the variational one-form with a vertical vector kills pi^* L_phys because Dpi[v_q]=0; exact terms need the separate boundary gate.",
            "what_it_proves": "bulk C_qT, q_private Weyl spurion terms and source-prefactor q dependence cannot be present as physical local operators.",
            "current_status": "EXACT_CONDITIONAL_THEOREM",
            "fires_now": "False",
            "source_path": str(SOURCES["absent_quotient_3449"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "QAP3520_2_operator_basicness_test",
            "claim": "A direct operator f(q_private) O_basic is admissible only when f is constant on q fibres or the operator is a pure constraint/boundary term.",
            "formal_statement": "If O_basic and mu are q-basic, then L_vq[mu f(q_private) O_basic] = mu f'(q_private)L_vq(q_private)O_basic. For arbitrary nonzero O_basic and L_vq(q_private) not identically zero, f'=0.",
            "derivation": "The quotient principle requires the variation to vanish for all local representatives and sources. Since O_basic is arbitrary and independent of the representative coordinate, the coefficient of O_basic must vanish pointwise.",
            "what_it_proves": "linear f=C q_private forces C=0; q_private T and q_private P_W C_abcd are forbidden unless q_private is physical or the term is a boundary/constraint.",
            "current_status": "EXACT_THEOREM_IF_VQ_REPRESENTATIVE_COORDINATE",
            "fires_now": "False",
            "source_path": str(SOURCES["normal_form_3519"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "QAP3520_3_matter_functor",
            "claim": "If ordinary matter is a functor of the physical quotient stack Qvis, direct q_private matter/source variation vanishes.",
            "formal_statement": "S_matter[Phi,Psi]=Sbar_matter[Qvis(Phi),Psi,theta_rep], DQvis[v_q]=0, and L_vq theta_rep=0 imply D_vq S_matter=0.",
            "derivation": "Apply the chain rule: D_vq S_matter = DSbar[DQvis[v_q]] + partial_theta Sbar L_vq theta_rep = 0.",
            "what_it_proves": "j_matter=0 and C_qT=0 after the quotient-action object language is parent signed.",
            "current_status": "EXACT_CONDITIONAL_THEOREM_NOT_PARENT_SIGNED",
            "fires_now": "False",
            "source_path": str(SOURCES["matter_descent_2570"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "QAP3520_4_readout_firewall",
            "claim": "Readout maps cannot reenter the action before variation without becoming parent fields subject to the same quotient-basicness test.",
            "formal_statement": "Variation is performed on S_parent over Conf_parent first; Obs_A=Obsbar_A(pi(Phi)) is applied after solving. If Obs_A appears inside S_parent, it is not a readout but an action argument and must be q-basic or bounded.",
            "derivation": "Otherwise a post-variation projector could be tuned to erase or create a source current, violating the quotient action domain.",
            "what_it_proves": "readout/projector q tails are zero only when the firewall is parent signed; otherwise they remain explicit finite terms.",
            "current_status": "GUARDRAIL_THEOREM_NOT_FULL_ZERO",
            "fires_now": "False",
            "source_path": str(SOURCES["readout_order_2570"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "QAP3520_5_limit_of_the_principle",
            "claim": "Quotient action descent does not by itself prove EH/local-GR if extra q-basic hidden sectors remain and are integrated out.",
            "formal_statement": "S_parent=pi^*S_phys[g] + S_hidden[pi(Phi),Z] can be quotient invariant while still inducing R2/fR/Weyl2/nonlocal operators after solving for Z.",
            "derivation": "The hidden sector is already quotient-basic, so vertical representative silence holds, but physical metric equations can still receive non-EH corrections.",
            "what_it_proves": "3520 can derive the q_private normal form but not the full local-GR reduction; no-integrated-out-tower/EH operator selection remains separate.",
            "current_status": "COUNTERMODEL_GUARD_ACTIVE",
            "fires_now": "False",
            "source_path": str(SOURCES["primitive_2623"]["path"]),
            "valid_for_claim": "False",
        },
    ]


def normal_form_derivation_rows() -> list[dict[str, Any]]:
    return [
        {
            "rule_id": "DER3520_0_parent_domain",
            "normal_form_rule": "ParentDomain before readout/fitting",
            "derived_from_qap": "Yes_conditional",
            "derivation_result": "the action domain is Conf_parent -> Conf_phys before empirical projection; post-solve source labels cannot be action primitives",
            "remaining_parent_signature_gap": "Conf_parent and equivalence relation are still candidate objects, not derived from MTS primitives",
            "status": "DERIVED_FROM_QAP_NOT_PARENT_SIGNED",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_1_Qvis",
            "normal_form_rule": "single quotient visible stack",
            "derived_from_qap": "Yes_conditional",
            "derivation_result": "ordinary physical arguments are sections over Conf_phys; vertical representative data cannot define a second source metric",
            "remaining_parent_signature_gap": "Qvis constructor and DQvis[v_q]=0 must be signed field-by-field",
            "status": "DERIVED_FROM_QAP_NEEDS_QMAP_KERNEL",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_2_matter_functor",
            "normal_form_rule": "S_matter factors through Qvis",
            "derived_from_qap": "Yes_conditional",
            "derivation_result": "matter sees physical quotient data; direct q_private matter slots are nonbasic and gauge-variant",
            "remaining_parent_signature_gap": "theta/marker constants and no source-only prefactor closure remain unsigned",
            "status": "DERIVED_FROM_QAP_WITH_MARKER_GUARD",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_3_curvature_language",
            "normal_form_rule": "no q_private Weyl spurion/readout kernel",
            "derived_from_qap": "Partial",
            "derivation_result": "q_private times a q-basic curvature scalar is forbidden; linear Weyl also needs the independent no-spurion index theorem",
            "remaining_parent_signature_gap": "a quotient-basic P_W spurion could still be a physical operator unless primitive minimality/no-spurion is signed",
            "status": "PARTIAL_QAP_PLUS_INDEX_THEOREM_REQUIRED",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_4_universal_scale",
            "normal_form_rule": "no q_private-dependent source prefactor",
            "derived_from_qap": "Partial",
            "derivation_result": "nonconstant vertical dependence w_A(q_private) is forbidden; q-basic species constants still need common-measure/category owner",
            "remaining_parent_signature_gap": "single action-density/hbar/measure owner not derived by quotient principle alone",
            "status": "PARTIAL_QAP_COMMON_MODE_OWNER_STILL_REQUIRED",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_5_readout_firewall",
            "normal_form_rule": "variation before readout",
            "derived_from_qap": "Yes_conditional",
            "derivation_result": "readout is not an action argument; if it reenters action it must pass the same q-basicness test",
            "remaining_parent_signature_gap": "post-variation projection/order must be stated in the parent variational problem",
            "status": "DERIVED_GUARDRAIL_NOT_SOURCE_ZERO",
            "valid_for_claim": "False",
        },
        {
            "rule_id": "DER3520_6_boundary_reference",
            "normal_form_rule": "boundary/reference proper or q-basic",
            "derived_from_qap": "Partial",
            "derivation_result": "bulk quotient descent kills vertical bulk variation; boundary exact terms need proper/fixed boundary silence",
            "remaining_parent_signature_gap": "boundary charge and H_ref source-blindness remain separate local gates",
            "status": "PARTIAL_BOUNDARY_CLAUSE_REQUIRED",
            "valid_for_claim": "False",
        },
    ]


def operator_test_rows() -> list[dict[str, Any]]:
    return [
        {
            "test_id": "OPT3520_0_CqT",
            "operator": "Integral mu C_qT q_private T",
            "vertical_variation": "Integral mu C_qT L_vq(q_private) T",
            "qap_verdict": "C_qT=0 if q_private is representative-only and T is q-basic/arbitrary",
            "escape_route": "promote q_private to physical scalar; then vertical theorem fails and finite C_qT bound is required",
            "zero_if_signed": "C_qT=0;j_matter=0",
            "fires_now": "False",
            "valid_for_claim": "False",
        },
        {
            "test_id": "OPT3520_1_BqWeyl",
            "operator": "Integral mu B_qWeyl q_private P_W^{abcd} C_abcd",
            "vertical_variation": "Integral mu B_qWeyl L_vq(q_private) P_W^{abcd} C_abcd plus spurion variation",
            "qap_verdict": "B_qWeyl=0 if q_private is representative-only and no physical P_W spurion is admitted; metric/epsilon-only grammar also kills one-Weyl scalar",
            "escape_route": "physical quotient-basic P_W or Weyl2 tower; then finite curvature bound required",
            "zero_if_signed": "B_qWeyl_linear=0",
            "fires_now": "False",
            "valid_for_claim": "False",
        },
        {
            "test_id": "OPT3520_2_prefactor",
            "operator": "Integral mu w_A(q_private) L_A",
            "vertical_variation": "Integral mu w_A_prime L_vq(q_private) L_A",
            "qap_verdict": "vertical dependence is forbidden, so w_A_prime=0; relative q-basic constants require a separate common-measure/category theorem",
            "escape_route": "q-independent species weights survive as calibration/source-normalization residuals unless common-mode owner is signed",
            "zero_if_signed": "partial_q w_A=0;not full WEP weight zero by QAP alone",
            "fires_now": "False",
            "valid_for_claim": "False",
        },
        {
            "test_id": "OPT3520_3_readout_tail",
            "operator": "Integral mu Pi_readout(q_private) Source",
            "vertical_variation": "Integral mu D_q Pi_readout[v_q] Source",
            "qap_verdict": "not admissible as readout; if in action it is a parent field and must be q-basic or bounded",
            "escape_route": "post-variation readout with nonzero derivative retained as E_readout",
            "zero_if_signed": "E_readout=0 only under readout firewall and q-basic projector",
            "fires_now": "False",
            "valid_for_claim": "False",
        },
        {
            "test_id": "OPT3520_4_boundary",
            "operator": "q_private boundary/reference/corner term",
            "vertical_variation": "delta_vq B_boundary + delta_vq H_ref",
            "qap_verdict": "bulk QAP does not erase improper boundary charges; proper/fixed/q-basic boundary class required",
            "escape_route": "finite E_boundary row",
            "zero_if_signed": "E_boundary=0 only under proper boundary-source silence",
            "fires_now": "False",
            "valid_for_claim": "False",
        },
    ]


def parent_signature_gate_rows() -> list[dict[str, Any]]:
    return [
        {
            "gate_id": "GATE3520_0_equivalence_relation",
            "gate": "MTS-derived representative equivalence relation",
            "needed_for": "quotient action principle parent ownership",
            "current_evidence": "407 sketches relational quotient; 3134 declares q map; neither derives the equivalence relation from primitives",
            "passed": "False",
            "if_failed": "QAP remains conditional/adoption candidate",
            "valid_for_claim": "False",
        },
        {
            "gate_id": "GATE3520_1_qmap_kernel",
            "gate": "q map and v_q in ker(Dq) signed field-by-field",
            "needed_for": "DQvis[v_q]=0 and matter/readout chain-rule zero",
            "current_evidence": "3134/3517 give candidate q and Dq matrix; source/readout/boundary components remain unsigned",
            "passed": "False",
            "if_failed": "Dq[v_q] finite bound remains",
            "valid_for_claim": "False",
        },
        {
            "gate_id": "GATE3520_2_action_descent",
            "gate": "S_parent descends to quotient before variation",
            "needed_for": "forbid direct q_private source operators",
            "current_evidence": "3112 and 3449 prove exact conditional descent but parent action signature is not owned",
            "passed": "False",
            "if_failed": "C_qT/B_qWeyl/source-prefactor rows stay finite",
            "valid_for_claim": "False",
        },
        {
            "gate_id": "GATE3520_3_boundary_properness",
            "gate": "boundary/reference terms are q-basic, fixed, exact or proper",
            "needed_for": "local Hamiltonian and source mass silence",
            "current_evidence": "3449 identifies the boundary clause as separate; 3519 keeps boundary residual live",
            "passed": "False",
            "if_failed": "E_boundary remains live",
            "valid_for_claim": "False",
        },
        {
            "gate_id": "GATE3520_4_no_tower",
            "gate": "no integrated-out q-basic hidden tower induces non-EH operators",
            "needed_for": "local GR/Newton reduction, not merely q_private source silence",
            "current_evidence": "2623 says no-tower primitive theorem is not derived",
            "passed": "False",
            "if_failed": "R2/fR/Weyl2/nonlocal residuals remain separate",
            "valid_for_claim": "False",
        },
        {
            "gate_id": "GATE3520_5_total_verdict",
            "gate": "3520 parent promotion",
            "needed_for": "claim q normal form as MTS theorem",
            "current_evidence": "the exact QAP-to-normal-form theorem is now written, but parent ownership gates fail",
            "passed": "False",
            "if_failed": "no local-GR/Newton/PPN/R10/WEP/clock claim",
            "valid_for_claim": "False",
        },
    ]


def status_rows() -> list[dict[str, Any]]:
    return [
        {
            "status_id": "STAT3520_0_qap_to_normal_form",
            "quantity": "QAP_derives_3519_normal_form",
            "value": "conditional_true",
            "meaning": "if physical actions descend to quotient classes, nonbasic q_private source operators are gauge-variant/ill-typed",
            "claim_effect": "real derivation progress, not a public MTS theorem yet",
            "valid_for_claim": "False",
        },
        {
            "status_id": "STAT3520_1_CqT",
            "quantity": "Z_CqT_under_QAP",
            "value": "conditional_true_parent_unsigned",
            "meaning": "C_qT=0 follows from QAP plus q_private representative status plus q-basic source stress",
            "claim_effect": "C_qT remains finite-bound until QAP and qmap kernel are parent signed",
            "valid_for_claim": "False",
        },
        {
            "status_id": "STAT3520_2_BqWeyl",
            "quantity": "Z_BqWeyl_under_QAP",
            "value": "conditional_true_with_no_spurion",
            "meaning": "QAP kills q_private dependence; the linear Weyl index theorem kills metric/epsilon-only one-Weyl terms",
            "claim_effect": "B_qWeyl remains finite-bound if physical P_W spurion/readout is allowed",
            "valid_for_claim": "False",
        },
        {
            "status_id": "STAT3520_3_prefactor",
            "quantity": "source_prefactor_status",
            "value": "partial_only",
            "meaning": "QAP kills vertical dependence w_A(q_private), but not every q-independent species/common-mode ambiguity",
            "claim_effect": "WEP/source-normalization still needs common action-density owner or finite bounds",
            "valid_for_claim": "False",
        },
        {
            "status_id": "STAT3520_4_local_GR",
            "quantity": "local_GR_reduction_status",
            "value": "not_derived",
            "meaning": "QAP-to-normal-form helps source coupling but does not exclude q-basic hidden towers or prove EH operator selection",
            "claim_effect": "GR/Newton route is closer but still incomplete",
            "valid_for_claim": "False",
        },
    ]


def finite_bound_rows() -> list[dict[str, Any]]:
    return [
        {
            "bound_id": "QAPB3520_0_Dq_vq",
            "source_channel": "failed_qmap_kernel",
            "bound_formula": "||Dq[v_q]|| <= eps_qmap + eps_Qvis + eps_boundary + eps_readout",
            "required_inputs": "parent qmap field chart; Dq matrix norms; source/readout/boundary derivative norms",
            "prediction_value": "MISSING_DQ_VQ_BOUND",
            "status": "NONCLAIM_IF_QAP_UNSIGNED",
            "valid_for_claim": "False",
        },
        {
            "bound_id": "QAPB3520_1_CqT",
            "source_channel": "direct_qprivate_matter",
            "bound_formula": "E_T <= |C_qT| ||P_T T||",
            "required_inputs": "C_qT source coefficient; stress projection; source support normalization",
            "prediction_value": "MISSING_CQT_COEFFICIENT",
            "status": "NONCLAIM_IF_QAP_UNSIGNED",
            "valid_for_claim": "False",
        },
        {
            "bound_id": "QAPB3520_2_BqWeyl",
            "source_channel": "linear_weyl_spurion",
            "bound_formula": "E_W <= |B_qWeyl| ||P_W W||",
            "required_inputs": "B_qWeyl coefficient; Weyl/profile projection; no-spurion verdict",
            "prediction_value": "MISSING_BQWEYL_COEFFICIENT",
            "status": "NONCLAIM_IF_QAP_UNSIGNED",
            "valid_for_claim": "False",
        },
        {
            "bound_id": "QAPB3520_3_prefactor",
            "source_channel": "source_prefactor_common_mode",
            "bound_formula": "E_weight <= sup_A |partial_q ln w_A| ||T_A|| + Delta_w_species_common_owner",
            "required_inputs": "vertical source-weight derivative; common-mode owner; material/source basis",
            "prediction_value": "MISSING_SOURCE_WEIGHT_INPUTS",
            "status": "NONCLAIM_IF_QAP_UNSIGNED",
            "valid_for_claim": "False",
        },
        {
            "bound_id": "QAPB3520_4_nonEH_tower",
            "source_channel": "qbasic_hidden_sector_after_elimination",
            "bound_formula": "E_nonEH <= |a_R2| ||R2|| + |a_fR| ||Delta f_R|| + |a_W2| ||W2|| + ||K_nonlocal||",
            "required_inputs": "EH/no-tower theorem or finite higher-curvature/nonlocal coefficients",
            "prediction_value": "MISSING_NON_EH_TOWER_BOUND",
            "status": "NONCLAIM_SEPARATE_FROM_QPRIVATE_SOURCE_SILENCE",
            "valid_for_claim": "False",
        },
    ]


def decision_rows() -> list[dict[str, Any]]:
    return [
        {
            "decision_id": "DEC3520_0_derivation_success_conditional",
            "decision": "the 3519 normal form is derivable from QAP, conditionally",
            "rationale": "direct q_private source operators are not invariant under representative changes unless their coefficients vanish or q_private is physical.",
            "effect": "C_qT has a genuine derivation route, not just an object-language preference.",
            "claim_allowed": "False",
        },
        {
            "decision_id": "DEC3520_1_parent_signature_not_acquired",
            "decision": "do not promote QAP as current MTS theorem",
            "rationale": "the equivalence relation, qmap kernel, boundary properness and no-hidden-tower gates are not signed from primitives.",
            "effect": "finite bounds remain mandatory and local-GR/Newton is not claimed.",
            "claim_allowed": "False",
        },
        {
            "decision_id": "DEC3520_2_next_primitives",
            "decision": "next attack is deriving QAP from MTS primitives",
            "rationale": "the only thing between this derivation and a real theorem is parent ownership of the quotient principle.",
            "effect": "3521 should try motion/time/space indistinguishability -> equivalence relation -> quotient action, or explicitly mark QAP adoption.",
            "claim_allowed": "False",
        },
    ]


def next_target_rows() -> list[dict[str, Any]]:
    return [
        {
            "next_doc": "3521-Y5-R2FR-MTS-primitives-to-quotient-action-principle-or-explicit-adoption-gate.md",
            "next_script": "scripts/Y5_R2FR_3521_MTS_primitives_to_quotient_action_principle_or_explicit_adoption_gate.py",
            "objective": "Try to derive the quotient action principle from MTS primitives: motion/time/space indistinguishability, representative-cell relabelling, and first-class Noether identity before local source variation.",
            "success_gate": "Either parent-own the equivalence relation and quotient action descent, or label QAP as an explicit adoption/closure principle and keep finite source bounds.",
            "why_next": "3520 proves QAP would kill the coupling route; 3521 must decide if QAP is actually derivable from MTS rather than imported as taste.",
            "claim_allowed": "False",
        }
    ]


def validate(
    outputs: dict[str, Path],
    sources: list[dict[str, Any]],
    theorem: list[dict[str, Any]],
    derivation: list[dict[str, Any]],
    operators: list[dict[str, Any]],
    gates: list[dict[str, Any]],
    status: list[dict[str, Any]],
    bounds: list[dict[str, Any]],
    next_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    checks: list[dict[str, Any]] = []
    checks.append(
        {
            "check_id": "VAL3520_0_sources_exist",
            "passed": bool_text(all(row["exists"] == "True" for row in sources)),
            "detail": "all cited local source paths exist",
            "valid_for_claim": "False",
        }
    )
    theorem_text = " ".join(row["claim"] + " " + row["what_it_proves"] for row in theorem)
    checks.append(
        {
            "check_id": "VAL3520_1_qap_theorem_present",
            "passed": bool_text("Physical parent actions are functionals on equivalence classes" in theorem_text and "q_private source operators" in theorem_text),
            "detail": "quotient action principle and q_private normal-form consequence are stated",
            "valid_for_claim": "False",
        }
    )
    derivation_rules = {row["rule_id"] for row in derivation}
    checks.append(
        {
            "check_id": "VAL3520_2_normal_form_matrix_complete",
            "passed": bool_text({"DER3520_0_parent_domain", "DER3520_2_matter_functor", "DER3520_3_curvature_language", "DER3520_5_readout_firewall"}.issubset(derivation_rules)),
            "detail": "; ".join(sorted(derivation_rules)),
            "valid_for_claim": "False",
        }
    )
    operator_names = {row["operator"] for row in operators}
    checks.append(
        {
            "check_id": "VAL3520_3_operator_variation_tests_present",
            "passed": bool_text(any("C_qT" in name for name in operator_names) and any("B_qWeyl" in name for name in operator_names) and any("w_A" in name for name in operator_names)),
            "detail": "; ".join(sorted(operator_names)),
            "valid_for_claim": "False",
        }
    )
    checks.append(
        {
            "check_id": "VAL3520_4_parent_gates_block_claim",
            "passed": bool_text(all(row["passed"] == "False" and row["valid_for_claim"] == "False" for row in gates)),
            "detail": "parent signature gates remain false, so no claim is promoted",
            "valid_for_claim": "False",
        }
    )
    checks.append(
        {
            "check_id": "VAL3520_5_no_claim_flags_true",
            "passed": bool_text(
                all(row["fires_now"] == "False" and row["valid_for_claim"] == "False" for row in theorem + operators)
                and all(row["valid_for_claim"] == "False" for row in derivation + status + bounds)
            ),
            "detail": "all theorem-zero rows remain conditional/nonclaim",
            "valid_for_claim": "False",
        }
    )
    checks.append(
        {
            "check_id": "VAL3520_6_bounds_nonclaim",
            "passed": bool_text(all(row["prediction_value"].startswith("MISSING_") and row["valid_for_claim"] == "False" for row in bounds)),
            "detail": "finite bounds are placeholders until source-backed inputs exist",
            "valid_for_claim": "False",
        }
    )
    checks.append(
        {
            "check_id": "VAL3520_7_next_target_primitives",
            "passed": bool_text(any("MTS-primitives" in row["next_doc"] or "MTS_primitives" in row["next_script"] for row in next_rows)),
            "detail": "3521 MTS primitives to QAP target selected",
            "valid_for_claim": "False",
        }
    )
    csvs_parse = True
    parse_details: list[str] = []
    for name, path in outputs.items():
        if path.suffix.lower() != ".csv":
            continue
        if name == "validation" and not path.exists():
            parse_details.append("validation:deferred_until_written")
            continue
        try:
            read_csv_rows(path)
            parse_details.append(name)
        except Exception as exc:
            csvs_parse = False
            parse_details.append(f"{name}:{exc}")
    checks.append(
        {
            "check_id": "VAL3520_8_csvs_parse",
            "passed": bool_text(csvs_parse),
            "detail": "; ".join(parse_details),
            "valid_for_claim": "False",
        }
    )
    output_paths_in_root = all(str(path).startswith(str(ROOT)) for path in outputs.values()) and str(DOC).startswith(str(ROOT))
    checks.append(
        {
            "check_id": "VAL3520_9_outputs_stay_in_post_checkpoint_work",
            "passed": bool_text(output_paths_in_root),
            "detail": f"root={ROOT}",
            "valid_for_claim": "False",
        }
    )
    checks.append(
        {
            "check_id": "VAL3520_10_formalization_workbench_not_targeted",
            "passed": "True",
            "detail": str(FORMALIZATION),
            "valid_for_claim": "False",
        }
    )
    passed = all(row["passed"] == "True" for row in checks)
    checks.append(
        {
            "check_id": "VAL3520_SUMMARY",
            "passed": bool_text(passed),
            "detail": "PASS" if passed else "FAIL",
            "valid_for_claim": "False",
        }
    )
    return checks


def markdown_table(rows: list[dict[str, Any]], fields: list[str]) -> str:
    lines = [
        "| " + " | ".join(fields) + " |",
        "| " + " | ".join("---" for _ in fields) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(row.get(field, "")).replace("\n", " ") for field in fields) + " |")
    return "\n".join(lines)


def write_doc(
    sources: list[dict[str, Any]],
    theorem: list[dict[str, Any]],
    derivation: list[dict[str, Any]],
    operators: list[dict[str, Any]],
    gates: list[dict[str, Any]],
    status: list[dict[str, Any]],
    bounds: list[dict[str, Any]],
    decisions: list[dict[str, Any]],
    next_rows: list[dict[str, Any]],
    validation_rows: list[dict[str, Any]],
) -> None:
    doc = f"""# 3520 - Quotient Action Principle Derives q Normal Form Or Finite Source Bounds

## Summary
- **Derivation win:** the 3519 q normal form is derivable from a quotient action principle.
- **Coupling lock:** a direct term like `Integral mu C_qT q_private T` is not invariant under representative changes, so `C_qT=0` follows if `q_private` is truly representative-only and the source stress is q-basic.
- **Weyl lock:** `q_private` dependence is killed by quotient invariance; a one-Weyl scalar also needs a forbidden spurion/readout object unless it is a separate physical operator.
- **Honest limit:** QAP does not by itself prove full local GR, because q-basic hidden sectors can still induce `R2`, `f(R)`, `Weyl2`, or nonlocal operators after elimination.
- **Current status:** exact conditional theorem built; parent ownership of the equivalence relation/qmap/action descent is not signed, so finite bounds remain active.

## Core Proof
Let `pi: Conf_parent -> Conf_phys` quotient representative changes generated by `v_q`. The quotient action principle is

`S_parent = pi^* S_phys + dB_basic + S_constraint`,

with the constraint and boundary pieces first-class/proper on the local branch. For a vertical `v_q`, `Dpi[v_q]=0`, so every pulled-back physical bulk term has zero vertical variation.

For any direct source operator

`S_direct = Integral mu f(q_private) O_basic`,

where `mu` and `O_basic` are quotient-basic,

`L_vq S_direct = Integral mu f'(q_private) L_vq(q_private) O_basic`.

For arbitrary local `O_basic` and nonzero representative motion `L_vq(q_private)`, quotient invariance forces `f'=0`. For `f=C q_private`, this gives `C=0`. The only escape is to promote `q_private` to a physical scalar, which immediately removes the vertical theorem route and requires finite bounds.

## Source Register
{markdown_table(sources, ["source_id", "path", "exists", "role", "valid_for_claim"])}

## Quotient Action Theorem
{markdown_table(theorem, ["theorem_id", "claim", "formal_statement", "derivation", "what_it_proves", "current_status", "fires_now", "valid_for_claim"])}

## Normal-Form Derivation Matrix
{markdown_table(derivation, ["rule_id", "normal_form_rule", "derived_from_qap", "derivation_result", "remaining_parent_signature_gap", "status", "valid_for_claim"])}

## Direct Operator Variation Tests
{markdown_table(operators, ["test_id", "operator", "vertical_variation", "qap_verdict", "escape_route", "zero_if_signed", "fires_now", "valid_for_claim"])}

## Parent Signature Gate
{markdown_table(gates, ["gate_id", "gate", "needed_for", "current_evidence", "passed", "if_failed", "valid_for_claim"])}

## Canonical Status
{markdown_table(status, ["status_id", "quantity", "value", "meaning", "claim_effect", "valid_for_claim"])}

## Finite Bounds If Not Signed
{markdown_table(bounds, ["bound_id", "source_channel", "bound_formula", "required_inputs", "prediction_value", "status", "valid_for_claim"])}

## Decisions
{markdown_table(decisions, ["decision_id", "decision", "rationale", "effect", "claim_allowed"])}

## Next Target
{markdown_table(next_rows, ["next_doc", "next_script", "objective", "success_gate", "why_next", "claim_allowed"])}

## Validation
{markdown_table(validation_rows, ["check_id", "passed", "detail", "valid_for_claim"])}

Generated: {now_utc()}
"""
    DOC.write_text(doc, encoding="utf-8")


def main() -> None:
    sources = source_register_rows()
    theorem = quotient_action_theorem_rows()
    derivation = normal_form_derivation_rows()
    operators = operator_test_rows()
    gates = parent_signature_gate_rows()
    status = status_rows()
    bounds = finite_bound_rows()
    decisions = decision_rows()
    next_rows = next_target_rows()

    outputs = {
        "source_register": OUT / "P8_Y5_R2FR_3520_SOURCE_REGISTER.csv",
        "theorem": OUT / "P8_Y5_R2FR_3520_QUOTIENT_ACTION_PRINCIPLE_THEOREM.csv",
        "derivation": OUT / "P8_Y5_R2FR_3520_NORMAL_FORM_DERIVATION_MATRIX.csv",
        "operators": OUT / "P8_Y5_R2FR_3520_DIRECT_OPERATOR_VARIATION_TESTS.csv",
        "gates": OUT / "P8_Y5_R2FR_3520_PARENT_SIGNATURE_GATE.csv",
        "status": OUT / "P8_Y5_R2FR_3520_QAP_NORMAL_FORM_STATUS.csv",
        "canonical_status": CANONICAL_STATUS,
        "bounds": OUT / "P8_Y5_R2FR_3520_FINITE_SOURCE_BOUNDS_IF_NOT_SIGNED.csv",
        "decision_ledger": OUT / "P8_Y5_R2FR_3520_DECISION_LEDGER.csv",
        "next_target": OUT / "P8_Y5_R2FR_3520_NEXT_TARGET.csv",
        "validation": OUT / "P8_Y5_BRR545_3520_VALIDATION.csv",
    }

    write_csv(outputs["source_register"], sources, ["source_id", "path", "exists", "role", "valid_for_claim"])
    write_csv(outputs["theorem"], theorem, ["theorem_id", "claim", "formal_statement", "derivation", "what_it_proves", "current_status", "fires_now", "source_path", "valid_for_claim"])
    write_csv(outputs["derivation"], derivation, ["rule_id", "normal_form_rule", "derived_from_qap", "derivation_result", "remaining_parent_signature_gap", "status", "valid_for_claim"])
    write_csv(outputs["operators"], operators, ["test_id", "operator", "vertical_variation", "qap_verdict", "escape_route", "zero_if_signed", "fires_now", "valid_for_claim"])
    write_csv(outputs["gates"], gates, ["gate_id", "gate", "needed_for", "current_evidence", "passed", "if_failed", "valid_for_claim"])
    status_fields = ["status_id", "quantity", "value", "meaning", "claim_effect", "valid_for_claim"]
    write_csv(outputs["status"], status, status_fields)
    write_csv(outputs["canonical_status"], status, status_fields)
    write_csv(outputs["bounds"], bounds, ["bound_id", "source_channel", "bound_formula", "required_inputs", "prediction_value", "status", "valid_for_claim"])
    write_csv(outputs["decision_ledger"], decisions, ["decision_id", "decision", "rationale", "effect", "claim_allowed"])
    write_csv(outputs["next_target"], next_rows, ["next_doc", "next_script", "objective", "success_gate", "why_next", "claim_allowed"])

    validation_rows = validate(outputs, sources, theorem, derivation, operators, gates, status, bounds, next_rows)
    write_csv(outputs["validation"], validation_rows, ["check_id", "passed", "detail", "valid_for_claim"])
    write_doc(sources, theorem, derivation, operators, gates, status, bounds, decisions, next_rows, validation_rows)

    print(f"wrote {DOC}")
    print(f"validation {outputs['validation']}")


if __name__ == "__main__":
    main()
