from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "source-intake" / "mts_residuals"
FORMALIZATION = ROOT.parent / "formalization-workbench"
DOC = ROOT / "3509-Y5-R2FR-no-source-only-matter-functor-signature-or-zg-bound.md"
CANONICAL_SOURCE_SLOT_RESIDUAL = OUT / "P8_EM_no_source_only_matter_functor_residual.csv"

SOURCES: dict[str, dict[str, Any]] = {
    "script_3509": {"path": Path(__file__).resolve(), "role": "generator"},
    "doc_3508": {
        "path": ROOT / "3508-Y5-R2FR-current-source-normalization-Ward-identity-or-alpha-source-bound.md",
        "role": "3508 Ward identity handoff",
    },
    "reduction_3508": {
        "path": OUT / "P8_Y5_R2FR_3508_ZG_BETA_SOURCE_REDUCTION.csv",
        "role": "3508 z_g/beta source reduction",
    },
    "ward_identity_3508": {
        "path": OUT / "P8_Y5_R2FR_3508_CURRENT_SOURCE_WARD_IDENTITY.csv",
        "role": "3508 Ward identity table",
    },
    "matter_functor_1045": {
        "path": OUT / "P8_Y5_R10_1045_PARENT_MATTER_FUNCTOR_SIGNATURE_AUDIT.csv",
        "role": "parent matter functor signature audit",
    },
    "matter_source_3235": {
        "path": OUT / "P8_Y5_R2FR_3235_MATTER_SOURCE_FUNCTOR_DERIVATION.csv",
        "role": "matter source functor derivation",
    },
    "no_source_2508": {
        "path": OUT / "P8_Y5_NO_SHADOW_2508_NO_SOURCE_ONLY_SLOT_PROOF_ATTEMPT.csv",
        "role": "no source-only slot proof attempt",
    },
    "countermodels_2508": {
        "path": OUT / "P8_Y5_NO_SHADOW_2508_SOURCE_ONLY_COUNTERMODELS.csv",
        "role": "source-only countermodels",
    },
    "no_prefactor_2645": {
        "path": OUT / "P8_Y5_NO_SOURCE_PREFACTOR_2645_PARENT_ACTION_CLAUSE_ATTEMPT.csv",
        "role": "parent no-source-prefactor action clause attempt",
    },
    "operator_grammar_1451": {
        "path": OUT / "P8_Y5_R10_1451_NO_SOURCE_ONLY_SLOT_OPERATOR_GRAMMAR_THEOREM_ATTEMPT.csv",
        "role": "operator grammar no-source-slot theorem attempt",
    },
    "typing_1479": {
        "path": OUT / "P8_Y5_R10_1479_NO_SOURCE_ONLY_ACTION_PREFACTOR_TYPING_THEOREM_ATTEMPT.csv",
        "role": "typing theorem for no source-only prefactor",
    },
    "conditional_3488": {
        "path": OUT / "P8_Y5_R2FR_3488_CONDITIONAL_NO_SOURCE_PROOF.csv",
        "role": "conditional no-source proof",
    },
}


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat()


def bool_text(value: bool) -> str:
    return "True" if value else "False"


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def source_register_rows() -> list[dict[str, Any]]:
    return [
        {
            "source_id": source_id,
            "path": str(metadata["path"]),
            "exists": bool_text(Path(metadata["path"]).exists()),
            "role": metadata["role"],
            "valid_for_claim": "False",
        }
        for source_id, metadata in SOURCES.items()
    ]


def source_slot_theorem_rows() -> list[dict[str, Any]]:
    return [
        {
            "theorem_id": "NSF3509_0_typed_domain_target",
            "claim_piece": "no source-only matter coefficient slot",
            "statement": "If the parent matter constructor accepts only observed geometry, dynamical matter fields, observed gauge/current data, fixed representation data, and universal constants, then inert source-only coefficients are not action arguments.",
            "mathematical_form": "Arg(S_A) subset {Psi_A,e_obs(q),omega_obs,A_Q,theta_A,constants}; Arg(S_A) cap {w_A(X),kappa_A(X),hidden_marker,source_label_coeff}=empty",
            "derivation": "Euler/source terms cannot be generated by variables absent from the typed parent action domain; this is syntax/domain exclusion, not small coupling.",
            "payoff": "z_g, beta_source_alpha and species-source charge become theorem-zero modulo universal common-scale residuals",
            "gap": "the parent object-language/domain exhaustion itself is still conditional",
            "status": "EXACT_IF_PARENT_DOMAIN_SIGNED",
            "source_path": str(SOURCES["typing_1479"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_1_connected_density_line_collapse",
            "claim_piece": "species weights collapse to common scalar",
            "statement": "If ordinary matter species are connected by parent-owned nonzero morphisms on one action-density line, naturality forces source weights to agree across connected components.",
            "mathematical_form": "w_B(q) F(f)=F(f) w_A(q), F(f) != 0 => w_A(q)=w_B(q)",
            "derivation": "A scalar automorphism of the common density line must commute with the matter functor. On connected nonzero morphisms this collapses species-indexed weights to one common scalar.",
            "payoff": "composition/WEP source-weight poison is removed conditionally even before the universal scalar is fixed",
            "gap": "ordinary matter category connectedness and single density-line ownership are not parent-signed",
            "status": "CONDITIONAL_EXACT_COLLAPSE",
            "source_path": str(SOURCES["conditional_3488"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_2_common_scalar_not_composition_source",
            "claim_piece": "common source scale reclassified",
            "statement": "A single common multiplier w(q) is not a species/WEP source charge; it is a universal action/G/source normalization residual unless the parent action scale fixes it.",
            "mathematical_form": "w_A(q)=w(q) for all A => partial_A ln w_A - partial_A ln w_B=0, but D_X ln w may remain",
            "derivation": "Common scaling cannot distinguish materials, so it cannot be beta_source_alpha by itself. It can still shift absolute source calibration, G_eff, or clock/action normalization.",
            "payoff": "separates composition source failure from universal calibration failure",
            "gap": "common action-scale owner remains unsigned",
            "status": "RECLASSIFICATION_THEOREM_CONDITIONAL",
            "source_path": str(SOURCES["no_prefactor_2645"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_3_no_Hom_source_coefficient",
            "claim_piece": "hidden/species marker cannot feed source coefficient",
            "statement": "If Hom_parent(SpeciesLabel or HiddenMarker, Coeff_active_source) is empty except universal constants, source-only kappa_A and hidden material markers are untypeable.",
            "mathematical_form": "Hom_parent(SpeciesLabel,C_source)=Hom_parent(HiddenMarker,C_source)=empty_or_common_constant",
            "derivation": "A coefficient map requires a typed morphism into the active-source coefficient target. If the source coefficient target is not in the image of hidden/species data, the map cannot be formed.",
            "payoff": "kappa_A(X), source-label spurions and hidden marker source charges are excluded by type",
            "gap": "no-Hom/no-hidden-visible theorem is still a parent grammar contract",
            "status": "EXACT_IF_NO_HOM_SIGNED",
            "source_path": str(SOURCES["operator_grammar_1451"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_4_Ward_support_limit",
            "claim_piece": "Ward support but not proof",
            "statement": "Ward identities police a signed common action, but they do not ban source-only coefficients by themselves.",
            "mathematical_form": "S_matter=sum_A w_A S_A still yields conserved weighted Ward currents",
            "derivation": "A symmetry identity differentiates the action supplied to it. If the grammar allowed w_A before variation, Ward conservation conserves w_A T_A rather than proving w_A absent.",
            "payoff": "prevents a fake closure of local GR source universality",
            "gap": "source-only slot theorem must be independent of Ward conservation",
            "status": "NO_GO_GUARD",
            "source_path": str(SOURCES["ward_identity_3508"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_5_nonHilbert_bypass_limit",
            "claim_piece": "non-Hilbert source bypass",
            "statement": "Even if source-only matter prefactors are absent, independent non-Hilbert active source currents must be exact owner divergences with zero exterior flux or retained as residuals.",
            "mathematical_form": "J_src=kappa T_H + sum_A zeta_A J_NH,A; need J_NH,A=nabla K_A and int_boundary K_A=0",
            "derivation": "The matter-functor domain controls ordinary matter action weights; it does not automatically silence boundary/domain/improvement currents outside the Hilbert source unless the owner-flux theorem is signed.",
            "payoff": "keeps local GR source route honest beyond ordinary matter",
            "gap": "owner divergence/flux theorem still separate",
            "status": "PARALLEL_GATE_RETAINED",
            "source_path": str(SOURCES["reduction_3508"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "theorem_id": "NSF3509_6_verdict",
            "claim_piece": "3509 theorem status",
            "statement": "The no-source-only route is mathematically sharp: source weights collapse or vanish if the typed matter constructor, connected density line and no-Hom clauses are parent-signed.",
            "mathematical_form": "parent domain + connected density line + no-Hom => delta_w_species=0, beta_source_alpha=0, z_g source-spurion part=0",
            "derivation": "Combine typed absence, naturality collapse, common-scale reclassification, and Ward support limits.",
            "payoff": "turns the source coupling issue from vague missing coupling into three named parent signatures",
            "gap": "no live claim until those signatures are derived from MTS primitives",
            "status": "THEOREM_STACK_CONSTRUCTED_NOT_PARENT_SIGNED",
            "source_path": str(SOURCES["conditional_3488"]["path"]),
            "valid_for_claim": "False",
        },
    ]


def residual_rows() -> list[dict[str, Any]]:
    return [
        {
            "row_id": "NSSR3509_0_delta_w_species",
            "residual": "delta_w_species",
            "definition": "D_X ln w_A - D_X ln w_B",
            "3509_result": "conditional zero by connected density-line naturality",
            "zero_condition": "single parent action-density line and connected ordinary matter category",
            "remaining_owner": "parent action-density line/matter-category connectedness",
            "observable_links": "WEP; composition_source; beta_source_alpha",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_1_w_common",
            "residual": "w_common",
            "definition": "D_X ln w(q) common to all ordinary matter",
            "3509_result": "not a composition source charge; reclassified as universal source/G/action normalization",
            "zero_condition": "single common action normalization fixed by parent",
            "remaining_owner": "common action-scale or G_ref/source calibration owner",
            "observable_links": "Gdot; Newton_G; clocks; source_calibration",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_2_kappa_A_source",
            "residual": "kappa_A_source",
            "definition": "source-only active coupling F((T_A,A))->kappa_A T_A",
            "3509_result": "conditional zero if source functor sees only total Hilbert source object",
            "zero_condition": "source-label forgetting before active source coupling",
            "remaining_owner": "parent source functor object-language",
            "observable_links": "WEP; R10; source_composition",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_3_hidden_marker_source",
            "residual": "hidden_marker_source",
            "definition": "hidden/domain/material marker feeding active source coefficient",
            "3509_result": "conditional zero if no Hom from hidden marker to source coefficient target",
            "zero_condition": "Hom_parent(HiddenMarker,C_source)=empty_or_common_constant",
            "remaining_owner": "no-hidden-visible Hom theorem",
            "observable_links": "preferred_frame; PPN; source_composition",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_4_z_g",
            "residual": "z_g",
            "definition": "D_X ln current/charge normalization",
            "3509_result": "source-spurion part conditionally zero; universal current/action scale part remains if common owner unsigned",
            "zero_condition": "fixed representation data plus no current/source-only scalar slot",
            "remaining_owner": "current normalization and common action-scale owner",
            "observable_links": "alpha_EM; clocks; WEP; R10",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_5_beta_source_alpha",
            "residual": "beta_source_alpha",
            "definition": "alpha/material marker contribution to active source composition",
            "3509_result": "conditional zero under no-source-only slot and connected density line",
            "zero_condition": "no species/hidden marker source coefficient and common density-line collapse",
            "remaining_owner": "typed matter constructor and no-Hom signature",
            "observable_links": "WEP; R10; material_composition",
            "claim_allowed": "False",
        },
        {
            "row_id": "NSSR3509_6_nonHilbert_source_bypass",
            "residual": "nonHilbert_source_bypass",
            "definition": "active source not generated by Hilbert variation of ordinary matter",
            "3509_result": "retained parallel gate",
            "zero_condition": "non-Hilbert currents are exact improvements with zero exterior flux",
            "remaining_owner": "owner divergence/flux theorem",
            "observable_links": "PPN; source_normalization; boundary_flux",
            "claim_allowed": "False",
        },
    ]


def bound_input_rows() -> list[dict[str, Any]]:
    return [
        {
            "row_id": "NSBIN3509_0_delta_w_species",
            "arena": "WEP/composition",
            "residual": "delta_w_species",
            "predicted_value": "MISSING_DELTA_W_SPECIES",
            "predicted_units": "dimensionless",
            "bound_value": "MISSING_WEP_BOUND",
            "bound_units": "dimensionless",
            "source_path": str(SOURCES["countermodels_2508"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "row_id": "NSBIN3509_1_w_common",
            "arena": "universal source/G calibration",
            "residual": "w_common",
            "predicted_value": "MISSING_DX_LN_W_COMMON",
            "predicted_units": "dimensionless_derivative_or_declared_scale",
            "bound_value": "MISSING_GDOT_OR_SOURCE_CALIBRATION_BOUND",
            "bound_units": "same_as_prediction",
            "source_path": str(SOURCES["no_prefactor_2645"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "row_id": "NSBIN3509_2_kappa_A_source",
            "arena": "source-label coupling",
            "residual": "kappa_A_source",
            "predicted_value": "MISSING_KAPPA_A_SOURCE",
            "predicted_units": "dimensionless",
            "bound_value": "MISSING_SOURCE_LABEL_BOUND",
            "bound_units": "dimensionless",
            "source_path": str(SOURCES["operator_grammar_1451"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "row_id": "NSBIN3509_3_hidden_marker_source",
            "arena": "hidden/source marker",
            "residual": "hidden_marker_source",
            "predicted_value": "MISSING_HIDDEN_MARKER_COEFF",
            "predicted_units": "dimensionless_or_declared_projection",
            "bound_value": "MISSING_PPN_OR_WEP_BOUND",
            "bound_units": "same_as_prediction",
            "source_path": str(SOURCES["typing_1479"]["path"]),
            "valid_for_claim": "False",
        },
        {
            "row_id": "NSBIN3509_4_nonHilbert_source_bypass",
            "arena": "PPN/boundary source bypass",
            "residual": "nonHilbert_source_bypass",
            "predicted_value": "MISSING_NONHILBERT_FLUX",
            "predicted_units": "dimensionless_or_flux",
            "bound_value": "MISSING_BYPASS_BOUND",
            "bound_units": "same_as_prediction",
            "source_path": str(SOURCES["reduction_3508"]["path"]),
            "valid_for_claim": "False",
        },
    ]


def parse_float(value: str) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def run_bound_rows(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    results: list[dict[str, Any]] = []
    for row in rows:
        predicted = parse_float(str(row["predicted_value"]))
        bound = parse_float(str(row["bound_value"]))
        if row["valid_for_claim"] != "True":
            verdict = "BLOCKED_INPUT_NOT_VALID_FOR_CLAIM"
            passes = "False"
        elif predicted is None or bound is None or bound <= 0:
            verdict = "BLOCKED_MISSING_NUMERIC_PREDICTION_OR_BOUND"
            passes = "False"
        else:
            passes = bool_text(abs(predicted) <= bound)
            verdict = "PASS_NUMERIC_SOURCE_SLOT_BOUND" if passes == "True" else "FAIL_NUMERIC_SOURCE_SLOT_BOUND"
        results.append(
            {
                "row_id": row["row_id"].replace("NSBIN", "NSRUN"),
                "arena": row["arena"],
                "residual": row["residual"],
                "predicted_value": row["predicted_value"],
                "bound_value": row["bound_value"],
                "pass_condition": "abs(predicted_value) <= bound_value with sourced numeric rows",
                "runner_verdict": verdict,
                "passes_bound": passes,
                "claim_allowed": "False",
                "valid_for_claim": "False",
            }
        )
    return results


def decision_rows() -> list[dict[str, Any]]:
    return [
        {
            "decision_id": "DEC3509_0_real_derivation_gain",
            "decision": "Source weights are not all equally bad now: species-dependent weights can collapse to a common scalar under connected density-line naturality.",
            "rationale": "This separates WEP/composition failure from universal action/G/source calibration.",
            "effect": "The source branch is narrower and better aimed: kill or bound the common action-scale owner next.",
            "claim_allowed": "False",
            "valid_for_claim": "False",
        },
        {
            "decision_id": "DEC3509_1_no_live_claim",
            "decision": "Do not claim beta_source_alpha=0 or z_g=0 yet.",
            "rationale": "The typing/no-Hom/common-density premises are exact but still parent-signature clauses, not derived MTS primitives.",
            "effect": "All source-slot and alpha-source rows remain non-claim.",
            "claim_allowed": "False",
            "valid_for_claim": "False",
        },
        {
            "decision_id": "DEC3509_2_best_next_target",
            "decision": "Attack the common action-density line and universal source-scale owner.",
            "rationale": "If the common scalar is fixed, the matter-source half of alpha/source coupling can collapse; if not, it maps to Gdot/source-calibration rather than WEP composition.",
            "effect": "Next step should target common action-scale ownership, not repeat Ward/source-slot audits.",
            "claim_allowed": "False",
            "valid_for_claim": "False",
        },
    ]


def next_target_rows() -> list[dict[str, Any]]:
    return [
        {
            "next_doc": "3510-Y5-R2FR-common-action-density-line-owner-or-universal-source-scale-bound.md",
            "next_script": "scripts/Y5_R2FR_3510_common_action_density_line_owner_or_universal_source_scale_bound.py",
            "objective": "Derive whether the parent supplies one fixed ordinary-matter action-density line/common normalization; if not, map the common source scale to Gdot, Newton calibration, clock, and source-normalization bound rows.",
            "success_gate": "Either D_X ln w_common=0 is parent-signed, or w_common is treated as a universal source/G calibration residual with numeric-ready non-claim bound inputs.",
            "forbidden_shortcuts": "Do not call a common scalar harmless if it shifts G_ref, clocks, or absolute source calibration.",
            "claim_allowed": "False",
            "valid_for_claim": "False",
        }
    ]


def validate(
    sources: list[dict[str, Any]],
    theorem_rows: list[dict[str, Any]],
    residuals: list[dict[str, Any]],
    bound_inputs: list[dict[str, Any]],
    runner_results: list[dict[str, Any]],
    decisions: list[dict[str, Any]],
    next_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    theorem_ids = {row["theorem_id"] for row in theorem_rows}
    residual_names = {row["residual"] for row in residuals}
    all_claim_false = all(
        row.get("valid_for_claim") == "False"
        for table in [sources, theorem_rows, bound_inputs, runner_results, decisions, next_rows]
        for row in table
    ) and all(row.get("claim_allowed") == "False" for row in residuals)
    all_blocked = all("BLOCKED" in row["runner_verdict"] for row in runner_results)
    validation = [
        {
            "check_id": "VAL3509_0_sources_exist",
            "passed": bool_text(all(row["exists"] == "True" for row in sources)),
            "detail": "all cited local source paths exist",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_1_theorem_stack_present",
            "passed": bool_text({"NSF3509_0_typed_domain_target", "NSF3509_1_connected_density_line_collapse", "NSF3509_3_no_Hom_source_coefficient"}.issubset(theorem_ids)),
            "detail": "typed domain, connected-density, and no-Hom clauses written",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_2_common_scalar_reclassification",
            "passed": bool_text("w_common" in residual_names and any(row["residual"] == "w_common" and "universal" in row["3509_result"] for row in residuals)),
            "detail": "common source scalar separated from composition source charge",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_3_required_residuals_present",
            "passed": bool_text({"delta_w_species", "w_common", "kappa_A_source", "hidden_marker_source", "z_g", "beta_source_alpha", "nonHilbert_source_bypass"}.issubset(residual_names)),
            "detail": "source-slot residual vector complete",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_4_bound_runner_blocks_placeholders",
            "passed": bool_text(all_blocked),
            "detail": "all source-slot bound rows remain blocked until numeric sourced inputs exist",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_5_no_claim_flags",
            "passed": bool_text(all_claim_false),
            "detail": "no 3509 output row is valid_for_claim=True or claim_allowed=True",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_6_next_target_common_action_scale",
            "passed": bool_text(next_rows[0]["next_doc"].startswith("3510") and "common" in next_rows[0]["objective"]),
            "detail": "common action-density/source-scale owner selected next",
            "valid_for_claim": "False",
        },
        {
            "check_id": "VAL3509_7_formalization_workbench_not_targeted",
            "passed": bool_text(FORMALIZATION.exists() and str(DOC).startswith(str(ROOT))),
            "detail": str(FORMALIZATION),
            "valid_for_claim": "False",
        },
    ]
    validation.append(
        {
            "check_id": "VAL3509_SUMMARY",
            "passed": bool_text(all(row["passed"] == "True" for row in validation)),
            "detail": "PASS" if all(row["passed"] == "True" for row in validation) else "FAIL",
            "valid_for_claim": "False",
        }
    )
    return validation


def markdown_table(rows: list[dict[str, Any]], fields: list[str]) -> str:
    header = "| " + " | ".join(fields) + " |"
    separator = "| " + " | ".join("---" for _ in fields) + " |"
    body = ["| " + " | ".join(str(row.get(field, "")).replace("\n", " ") for field in fields) + " |" for row in rows]
    return "\n".join([header, separator, *body])


def write_doc(
    theorem_rows: list[dict[str, Any]],
    residuals: list[dict[str, Any]],
    bound_inputs: list[dict[str, Any]],
    runner_results: list[dict[str, Any]],
    decisions: list[dict[str, Any]],
    next_rows: list[dict[str, Any]],
    validation_rows: list[dict[str, Any]],
) -> None:
    DOC.write_text(
        "\n".join(
            [
                "# 3509 - No Source-Only Matter Functor Signature Or z_g Bound",
                "",
                "## Summary",
                "- **Derived gain:** connected density-line naturality can collapse species-dependent source weights `w_A` to one common scalar `w(q)` if the parent matter category/density line is signed.",
                "- **Important split:** species/composition source poison is then conditionally removed, while a universal common scalar remains a `G_ref`/clock/source-calibration problem.",
                "- **Typing theorem:** source-only `w_A(X)`, `kappa_A(X)`, and hidden/source markers are absent by type if the parent matter constructor has no source-only coefficient target and no Hom from species/hidden markers.",
                "- **Still not claim-grade:** the typed object-language, connected density line, no-Hom, and common action-scale owner are not yet derived from deeper MTS primitives.",
                "",
                "## Source-Slot Theorem Stack",
                markdown_table(
                    theorem_rows,
                    ["theorem_id", "claim_piece", "statement", "mathematical_form", "payoff", "gap", "status"],
                ),
                "",
                "## Residual Vector",
                markdown_table(
                    residuals,
                    ["row_id", "residual", "definition", "3509_result", "zero_condition", "remaining_owner", "claim_allowed"],
                ),
                "",
                "## Bound Input Template",
                markdown_table(
                    bound_inputs,
                    ["row_id", "arena", "residual", "predicted_value", "bound_value", "source_path", "valid_for_claim"],
                ),
                "",
                "## Runner Results",
                markdown_table(
                    runner_results,
                    ["row_id", "arena", "residual", "pass_condition", "runner_verdict", "passes_bound", "claim_allowed"],
                ),
                "",
                "## Decisions",
                markdown_table(decisions, ["decision_id", "decision", "rationale", "effect", "claim_allowed"]),
                "",
                "## Next Target",
                markdown_table(
                    next_rows,
                    ["next_doc", "next_script", "objective", "success_gate", "forbidden_shortcuts", "claim_allowed"],
                ),
                "",
                "## Validation",
                markdown_table(validation_rows, ["check_id", "passed", "detail", "valid_for_claim"]),
                "",
                f"Generated: {now_utc()}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    sources = source_register_rows()
    theorem_rows = source_slot_theorem_rows()
    residuals = residual_rows()
    bound_inputs = bound_input_rows()
    runner_results = run_bound_rows(bound_inputs)
    decisions = decision_rows()
    next_rows = next_target_rows()
    validation_rows = validate(sources, theorem_rows, residuals, bound_inputs, runner_results, decisions, next_rows)

    write_csv(OUT / "P8_Y5_R2FR_3509_SOURCE_REGISTER.csv", sources, ["source_id", "path", "exists", "role", "valid_for_claim"])
    write_csv(
        OUT / "P8_Y5_R2FR_3509_NO_SOURCE_ONLY_MATTER_FUNCTOR_THEOREM.csv",
        theorem_rows,
        ["theorem_id", "claim_piece", "statement", "mathematical_form", "derivation", "payoff", "gap", "status", "source_path", "valid_for_claim"],
    )
    residual_fields = [
        "row_id",
        "residual",
        "definition",
        "3509_result",
        "zero_condition",
        "remaining_owner",
        "observable_links",
        "claim_allowed",
    ]
    write_csv(OUT / "P8_Y5_R2FR_3509_SOURCE_SLOT_RESIDUAL_VECTOR.csv", residuals, residual_fields)
    write_csv(CANONICAL_SOURCE_SLOT_RESIDUAL, residuals, residual_fields)
    write_csv(
        OUT / "P8_Y5_R2FR_3509_SOURCE_SLOT_BOUND_INPUT_TEMPLATE.csv",
        bound_inputs,
        ["row_id", "arena", "residual", "predicted_value", "predicted_units", "bound_value", "bound_units", "source_path", "valid_for_claim"],
    )
    runner_fields = [
        "row_id",
        "arena",
        "residual",
        "predicted_value",
        "bound_value",
        "pass_condition",
        "runner_verdict",
        "passes_bound",
        "claim_allowed",
        "valid_for_claim",
    ]
    write_csv(OUT / "P8_Y5_R2FR_3509_SOURCE_SLOT_BOUND_RUNNER_RESULTS.csv", runner_results, runner_fields)
    write_csv(OUT / "P8_EM_no_source_only_bound_runner_results.csv", runner_results, runner_fields)
    write_csv(
        OUT / "P8_Y5_R2FR_3509_DECISION_LEDGER.csv",
        decisions,
        ["decision_id", "decision", "rationale", "effect", "claim_allowed", "valid_for_claim"],
    )
    write_csv(
        OUT / "P8_Y5_R2FR_3509_NEXT_TARGET.csv",
        next_rows,
        ["next_doc", "next_script", "objective", "success_gate", "forbidden_shortcuts", "claim_allowed", "valid_for_claim"],
    )
    write_csv(OUT / "P8_Y5_BRR545_3509_VALIDATION.csv", validation_rows, ["check_id", "passed", "detail", "valid_for_claim"])
    write_doc(theorem_rows, residuals, bound_inputs, runner_results, decisions, next_rows, validation_rows)


if __name__ == "__main__":
    main()
