from __future__ import annotations

import csv
from pathlib import Path
from typing import Dict, Iterable, List


def write_csv(path: Path, rows: Iterable[Dict[str, object]]) -> None:
    row_list = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not row_list:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(row_list[0].keys()))
        writer.writeheader()
        writer.writerows(row_list)


def read_csv(path: Path) -> List[Dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def parent_selector_signature_audit_rows() -> List[Dict[str, object]]:
    return [
        {
            "clause_id": "SIG4470_0_local_object_language",
            "selector_clause": "local geometry object language is only e^A, omega^AB, R^AB, T^A, orientation/volume and fixed/topological boundary data",
            "derivation_attempt": "The Palatini selector supplies this language at leading IR order, but the corpus still labels it as a selector rather than a parent theorem.",
            "if_signed": "bulk local gravity grammar is restricted to EC/EH plus Lambda, torsion algebraic terms, topological/boundary terms and explicitly bounded residuals",
            "current_evidence": "PRESENT_AS_SELECTOR_NOT_GLOBAL_PARENT_SIGNATURE",
            "parent_signed": False,
            "blocker": "selector_assumptions_parent_derived=false",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_1_first_order_flux_linearity",
            "selector_clause": "one physical oriented curvature flux has a cylindrical first-moment action S_h=kappa A_h delta_h",
            "derivation_attempt": "Refinement invariance gives S_n(delta)=n Phi(delta/n)=Phi(delta), forcing Phi''(0)=0 for the same channel.",
            "if_signed": "same-channel c2_visible=0; same physical signed-deficit branch cannot generate c_R2_eff",
            "current_evidence": "EXACT_CONDITIONAL_REFINEMENT_THEOREM",
            "parent_signed": False,
            "blocker": "quotient/projective refinement equivalence and cylindrical action are unsigned parent premises",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_2_no_local_length_scale_or_grain",
            "selector_clause": "no physical cell, grain, cutoff, lattice remnant or local transition length survives in the tested vacuum branch",
            "derivation_attempt": "Without a local length scale, a non-topological c_R2_eff term cannot be built as ell_cell^2 times a dimensionless quadratic response. With such a scale, R^2 is dimensionally legal.",
            "if_signed": "ell_cell and c2_visible routes close, so c_R2_eff=0 unless generated by a separate heavy/auxiliary sector",
            "current_evidence": "NOT_PARENT_SIGNED_DECISIVE_OPEN_CLAUSE",
            "parent_signed": False,
            "blocker": "no parent no-grain/no-cutoff theorem in current corpus",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_3_no_auxiliary_integration",
            "selector_clause": "no auxiliary scalar, tower, marker field, local memory kernel or nonlocal field can be integrated out into f(R), Yukawa or curvature-square response",
            "derivation_attempt": "A second field may be absent from the explicit A(chi) matter frame and still reappear as a metric pole or hidden source channel.",
            "if_signed": "C_metric_pole=0 and C_hidden_source=0; the common-mode scalar fifth-force branch is inactive",
            "current_evidence": "NOT_PARENT_SIGNED_COUNTERCHANNELS_RETAINED",
            "parent_signed": False,
            "blocker": "hidden scalar/marker/memory inventory is not closed by parent theorem",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_4_connection_resolution",
            "selector_clause": "independent connection, torsion and nonmetricity are absent, Levi-Civita functorial, or algebraically eliminated without source/projective/boundary leakage",
            "derivation_attempt": "EC/Palatini reduces to EH only when torsion/nonmetricity equations are algebraic and zero or bounded in the spinless compact branch.",
            "if_signed": "connection sector cannot regenerate c_T, D2, projective hair, boundary charge or local PPN residuals",
            "current_evidence": "CONDITIONAL_OWNER_UNSIGNED",
            "parent_signed": False,
            "blocker": "connection elimination and boundary/projective silence are not globally parent-signed",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_5_no_extra_unscreened_modes",
            "selector_clause": "no extra scalar, spin-2, vector, disformal, source-memory or boundary mode remains unscreened through R10/PPN/clock/orbital scales",
            "derivation_attempt": "This is the physical content of the strict local-GR selector: every non-EH local mode is topological, boundary-routed, heavy, screened or coefficient-zero.",
            "if_signed": "D0=0, D2=0, C_total=0 for local fifth-force scoring, or all finite branches are moved to sourced bound rows",
            "current_evidence": "SELECTOR_PREMISE_NOT_PARENT_THEOREM",
            "parent_signed": False,
            "blocker": "finite residual coefficient map remains active",
            "valid_for_claim": False,
        },
        {
            "clause_id": "SIG4470_6_signature_verdict",
            "selector_clause": "all selector clauses above are parent-owned simultaneously",
            "derivation_attempt": "The contract is now compact: local-GR follows exactly if the parent owns object language, refinement linearity, no grain, no auxiliary integration, connection resolution and no extra modes.",
            "if_signed": "S_parent|loc -> S_EH + Lambda + Gauss-Bonnet/topological + routed boundary; finite R10 scalar branch becomes inactive",
            "current_evidence": "CONTRACT_COMPACTED_NOT_SIGNED",
            "parent_signed": False,
            "blocker": "SIG4470_2 and SIG4470_3 are the sharpest missing parent-owned clauses",
            "valid_for_claim": False,
        },
    ]


def derived_implication_rows() -> List[Dict[str, object]]:
    return [
        {
            "implication_id": "IMP4470_0_EH_normal_form",
            "condition": "all SIG4470 clauses parent_signed=true",
            "derived_law": "S_parent|loc = S_EH[g_obs;kappa_eff] + Lambda_eff + constant Gauss-Bonnet/topological + routed boundary",
            "proof_sketch": "The local two-derivative object language leaves the EC/EH volume and cosmological terms; second-order/no-extra-mode and boundary clauses remove non-topological curvature-square, torsion and nonlocal channels.",
            "current_status": "CONDITIONAL_ONLY",
            "claim_allowed": False,
            "valid_for_claim": False,
        },
        {
            "implication_id": "IMP4470_1_scalar_basis_zero",
            "condition": "all SIG4470 clauses parent_signed=true",
            "derived_law": "D0=0 and D2=0",
            "proof_sketch": "The non-topological R^2/Ricci^2/Weyl^2/Riemann^2 basis is either absent, topological in the GB combination, or boundary-routed.",
            "current_status": "CONDITIONAL_ONLY",
            "claim_allowed": False,
            "valid_for_claim": False,
        },
        {
            "implication_id": "IMP4470_2_cR2_eff_zero",
            "condition": "all SIG4470 clauses parent_signed=true",
            "derived_law": "c_R2_eff=0 and lambda_R2 is not a finite local scalar range",
            "proof_sketch": "First-order signed-flux refinement kills same-channel quadratic response; no local grain/length and no auxiliary integration kill independent finite R^2 generation.",
            "current_status": "CONDITIONAL_ONLY",
            "claim_allowed": False,
            "valid_for_claim": False,
        },
        {
            "implication_id": "IMP4470_3_common_mode_scalar_silence",
            "condition": "all SIG4470 clauses parent_signed=true plus source silence from 4467/4468",
            "derived_law": "C_metric_pole=0, C_hidden_source=0 and alpha_eff=0",
            "proof_sketch": "No metric pole exists without finite c_R2_eff or hidden auxiliary channel; no explicit A(chi) source factor removes the independent matter-frame route.",
            "current_status": "CONDITIONAL_ONLY",
            "claim_allowed": False,
            "valid_for_claim": False,
        },
        {
            "implication_id": "IMP4470_4_finite_branch_fallback",
            "condition": "any SIG4470 clause remains unsigned",
            "derived_law": "finite D0/D2/c_R2_eff/C_total intake remains mandatory before R10/PPN/local-GR scoring",
            "proof_sketch": "An unsigned no-grain or no-auxiliary clause is enough for a legal counterchannel, so a bound route must stay open.",
            "current_status": "ACTIVE_TODAY",
            "claim_allowed": False,
            "valid_for_claim": False,
        },
    ]


def finite_coefficient_intake_request_rows() -> List[Dict[str, object]]:
    return [
        {
            "request_id": "REQ4470_0_D0_scalar_basis",
            "quantity": "D0",
            "required_parent_input": "c_R2, c_Ric, c_W, c_Riem in one normalized local action basis",
            "formula_or_bound_interface": "D0 = 12*c_R2 + c_Ric - 6*c_W - 8*c_Riem",
            "source_request": "MISSING_PARENT_BASIS_COEFFICIENTS_OR_ZERO_THEOREM",
            "units": "m^2_or_action_normalized_length_squared",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_1_D2_spin2_basis",
            "quantity": "D2",
            "required_parent_input": "same coefficient basis plus proof non-R2 channels are zero/topological/boundary-silent",
            "formula_or_bound_interface": "D2 = -c_Ric - 2*c_W - 4*c_Riem",
            "source_request": "MISSING_PARENT_SPIN2_BASIS_OR_TOPOLOGICAL_PROOF",
            "units": "m^2_or_action_normalized_length_squared",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_2_cR2_eff_from_grain",
            "quantity": "c_R2_eff",
            "required_parent_input": "c2_visible, ell_cell, xi_shape and N_EH, or exact no-grain/no-quadratic theorem",
            "formula_or_bound_interface": "c_R2_eff = xi_shape*c2_visible*ell_cell^2/N_EH",
            "source_request": "MISSING_c2_VISIBLE_ELL_CELL_SHAPE_FACTOR_N_EH",
            "units": "m^2",
            "status": "BLOCKED_DECISIVE_NEXT_CLAUSE",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_3_C_total",
            "quantity": "C_total",
            "required_parent_input": "C_explicit_Achi, C_metric_pole, C_hidden_source with source paths",
            "formula_or_bound_interface": "C_total = C_explicit_Achi + C_metric_pole + C_hidden_source; alpha_eff=C_total^2/3",
            "source_request": "C_explicit_Achi_PRIVATE_ZERO_BUT_C_METRIC_POLE_AND_C_HIDDEN_SOURCE_MISSING",
            "units": "dimensionless",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_4_R10_alpha_curve",
            "quantity": "alpha_bound(lambda)",
            "required_parent_input": "live source-backed R10 alpha(lambda) curve plus lambda_R2 from D0/c_R2_eff",
            "formula_or_bound_interface": "pass iff abs(C_total^2/3) <= alpha_bound(lambda_R2)",
            "source_request": "MISSING_LIVE_CLAIM_CURVE_AND_PARENT_LAMBDA",
            "units": "dimensionless_vs_m",
            "status": "BLOCKED_NONCLAIM",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_5_PPN_lightcone_projection",
            "quantity": "gamma(r)-1",
            "required_parent_input": "C_total, lambda_R2 and screened/unscreened local solution branch",
            "formula_or_bound_interface": "gamma(r)-1 = -2*alpha_eff*exp(-r/lambda_R2)/(1+alpha_eff*exp(-r/lambda_R2))",
            "source_request": "MISSING_LIGHTCONE_AND_SCREENING_PROJECTION",
            "units": "dimensionless",
            "status": "BLOCKED_SOURCE_READY",
            "valid_for_claim": False,
        },
        {
            "request_id": "REQ4470_6_pressure_guard",
            "quantity": "current universal scalar pressure",
            "required_parent_input": "if C_total=1 and lambda_R2=7.63929980956e-05 m, compare alpha=1/3 to review-candidate alpha_bound",
            "formula_or_bound_interface": "ratio = 2.44225859996; |C_total| must be <= 0.63988831003 for that pressure row",
            "source_request": "NONCLAIM_GUARD_FROM_4469_NOT_A_LIVE_PASS",
            "units": "dimensionless",
            "status": "GUARD_ONLY",
            "valid_for_claim": False,
        },
    ]


def decision_rows(next_target: str) -> List[Dict[str, object]]:
    return [
        {
            "decision_id": "DEC4470_0_contract_compacted",
            "finding": "the local-GR theorem route is now a compact parent-selector signature contract rather than a vague missing derivation",
            "consequence": "future work can attack specific clauses instead of circling the whole local-GR problem",
            "next_action": next_target,
            "valid_for_claim": False,
        },
        {
            "decision_id": "DEC4470_1_no_grain_is_decisive",
            "finding": "the sharpest unresolved clause is no physical local length/grain/cutoff in the tested vacuum branch",
            "consequence": "if no local length exists, c_R2_eff cannot be built from a grain quadratic response; if it exists, source c_R2_eff numerically",
            "next_action": next_target,
            "valid_for_claim": False,
        },
        {
            "decision_id": "DEC4470_2_no_auxiliary_is_next_risk",
            "finding": "hidden scalar/marker/memory/tower integration can reintroduce f(R) or Yukawa behavior even when explicit A(chi) is absent",
            "consequence": "source-coupling silence and no-second-channel must be signed together before local-GR can be claimed",
            "next_action": next_target,
            "valid_for_claim": False,
        },
        {
            "decision_id": "DEC4470_3_finite_fallback_staged",
            "finding": "D0, D2, c_R2_eff, C_total, alpha(lambda) and PPN projection rows are now source-request rows, not vibes",
            "consequence": "if derivation fails, the local branch can still be tested honestly with finite coefficients",
            "next_action": next_target,
            "valid_for_claim": False,
        },
    ]


def claim_gate_rows(
    source_rows: List[Dict[str, object]],
    signature_rows: List[Dict[str, object]],
    implication_rows: List[Dict[str, object]],
    intake_rows: List[Dict[str, object]],
) -> List[Dict[str, object]]:
    sources_ok = all(row.get("local_path_exists") is True and row.get("needle_found") is True for row in source_rows)
    contract_written = any(row.get("clause_id") == "SIG4470_6_signature_verdict" for row in signature_rows)
    all_signature_signed = all(row.get("parent_signed") is True for row in signature_rows)
    no_grain_signed = any(
        row.get("clause_id") == "SIG4470_2_no_local_length_scale_or_grain" and row.get("parent_signed") is True
        for row in signature_rows
    )
    finite_intake_ready = all(
        "MISSING" not in str(row.get("source_request"))
        and str(row.get("status")).upper() not in {"BLOCKED_SOURCE_READY", "BLOCKED_DECISIVE_NEXT_CLAUSE", "BLOCKED_NONCLAIM"}
        for row in intake_rows
    )
    no_claims = all(
        str(row.get("valid_for_claim")).lower() == "false"
        for group in [source_rows, signature_rows, implication_rows, intake_rows]
        for row in group
    )
    return [
        {
            "gate_id": "CG4470_0_sources",
            "claim": "all cited local sources exist and needles are found",
            "gate_pass": sources_ok,
            "claim_allowed": False,
            "detail": "source register validates selector, residual, refinement, scalaron and pressure inputs",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4470_1_selector_contract_written",
            "claim": "parent selector signature contract is compact and explicit",
            "gate_pass": contract_written,
            "claim_allowed": False,
            "detail": "4470 reduces local-GR closure to object-language, refinement, no-grain, no-auxiliary, connection and no-extra-mode clauses",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4470_2_all_signature_clauses_parent_signed",
            "claim": "MTS parent derives strict two-derivative/no-extra-mode local selector",
            "gate_pass": all_signature_signed,
            "claim_allowed": False,
            "detail": "not signed; at least no-grain/no-auxiliary clauses remain open",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4470_3_no_grain_parent_signed",
            "claim": "physical local length/grain route to c_R2_eff is closed",
            "gate_pass": no_grain_signed,
            "claim_allowed": False,
            "detail": "no-grain is the next decisive theorem target, not currently a parent-owned result",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4470_4_finite_intake_ready",
            "claim": "finite c_R2/C_total branch is numerically score-ready",
            "gate_pass": finite_intake_ready,
            "claim_allowed": False,
            "detail": "source-request rows are staged but still contain MISSING parent/source inputs",
            "valid_for_claim": False,
        },
        {
            "gate_id": "CG4470_5_no_generated_claim_rows",
            "claim": "no generated row is promoted to public/local-GR evidence",
            "gate_pass": no_claims,
            "claim_allowed": False,
            "detail": "4470 is a derivation contract and finite-intake staging checkpoint only",
            "valid_for_claim": False,
        },
    ]
