from __future__ import annotations

import csv
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(r"D:\Users\ollet\Desktop\Turn an intuitive research programme into a formal field-theoretic framework\Motion-TimeSpace--main")
POST_CHECKPOINT = ROOT / "post-checkpoint-work"
FORMALIZATION = ROOT / "formalization-workbench"
RESIDUALS = POST_CHECKPOINT / "source-intake" / "mts_residuals"

OUTPUT_DOC = POST_CHECKPOINT / "796-Y5-R10-KL-amplitude-PPN-budget-or-parent-relaxation-source.md"
NEXT_TARGET = "797-Y5-R10-parent-relaxation-source-action-contract-and-Gammaeff-screening-gate.md"

SOURCE_REGISTER_PATH = RESIDUALS / "P8_Y5_R10_796_SOURCE_REGISTER.csv"
AMPLITUDE_BUDGET_PATH = RESIDUALS / "P8_Y5_R10_796_KL_AMPLITUDE_PPN_BUDGET.csv"
RELAXATION_SOURCE_PATH = RESIDUALS / "P8_Y5_R10_796_PARENT_RELAXATION_SOURCE_TEST.csv"
RESIDUAL_VECTOR_PATH = RESIDUALS / "P8_Y5_R10_796_LOCAL_RESIDUAL_BUDGET_VECTOR.csv"
DECISION_PATH = RESIDUALS / "P8_Y5_R10_796_DERIVATION_DECISION.csv"
NONCLAIM_SUMMARY_PATH = RESIDUALS / "P8_Y5_R10_796_NONCLAIM_SUMMARY.csv"
VALIDATION_PATH = RESIDUALS / "P8_Y5_BRR545_796_VALIDATION.csv"

STATUS = "Y5_R10_796_KL_amplitude_no_free_lunch_parent_relaxation_route_defined_nonclaim"
CLAIM_CEILING = "amplitude_budget_and_relaxation_source_contract_only_no_PPN_pass_no_local_GR_claim"
FORMALIZATION_CUTOFF = datetime(2026, 5, 31, 14, 42, 0)


OUTPUT_PATHS = [
    OUTPUT_DOC,
    SOURCE_REGISTER_PATH,
    AMPLITUDE_BUDGET_PATH,
    RELAXATION_SOURCE_PATH,
    RESIDUAL_VECTOR_PATH,
    DECISION_PATH,
    NONCLAIM_SUMMARY_PATH,
    VALIDATION_PATH,
]


SOURCE_SPECS = [
    {
        "source_id": "795_doc",
        "path": POST_CHECKPOINT / "795-Y5-R10-parent-origin-of-tracefree-Khat-solver-or-amplitude-bound.md",
        "needles": ["Current result", "carrier `K_L` is generally of order `Gamma_eff`", "D795_1_amplitude_gate_primary"],
        "role": "immediate parent-origin and amplitude obstruction",
    },
    {
        "source_id": "795_validation",
        "path": RESIDUALS / "P8_Y5_BRR545_795_VALIDATION.csv",
        "needles": ["V795_8_scale_law_present,pass", "V795_12_no_claim,pass"],
        "role": "prior checkpoint validation",
    },
    {
        "source_id": "794_solver",
        "path": POST_CHECKPOINT / "794-Y5-R10-tracefree-longitudinal-Khat-solver-or-PPN-bound.md",
        "needles": ["TLS794_2_flat_cancellation", "TLS794_4_amplitude_warning", "PBR794_0_PPN_metric"],
        "role": "formal trace-free solver and PPN bound requirements",
    },
    {
        "source_id": "793_balance",
        "path": POST_CHECKPOINT / "793-Y5-R10-Gamma-Khat-balance-source-equation-or-local-bound-inputs.md",
        "needles": ["GBS793_1_tracefree_longitudinal_solver", "GBS793_3_relaxation_fixed_point"],
        "role": "trace-free divergence balance and relaxation candidate",
    },
    {
        "source_id": "790_residual_gates",
        "path": POST_CHECKPOINT / "790-Y5-R10-MTS-exchange-stress-decomposition-and-local-suppression-gates.md",
        "needles": ["LSG790_3_anisotropic_PPN_suppression", "LSG790_7_Newton_limit_gate"],
        "role": "local GR suppression gate map",
    },
    {
        "source_id": "789_newton_contract",
        "path": POST_CHECKPOINT / "789-Y5-R10-palatini-tetrad-GR-limit-with-MTS-exchange-contract.md",
        "needles": ["PTG789_5_Newton_recovery", "Newton PPN Residual Vector"],
        "role": "conditional GR to Newton contract",
    },
    {
        "source_id": "formal_eq_old_A",
        "path": FORMALIZATION / "05-equation-register.md",
        "needles": ["Local longitudinal PPN tensor ansatz", "Box A_loc^nu = q_loc^nu"],
        "role": "existing A_loc Green-function repair route",
    },
    {
        "source_id": "formal_red_team_ppn",
        "path": FORMALIZATION / "06-consistency-red-team.md",
        "needles": ["Green-function solution for `A_loc^nu`", "full PPN residual vector"],
        "role": "older red-team warning that PPN vector is unfilled",
    },
    {
        "source_id": "formal_spine_q",
        "path": FORMALIZATION / "07-unification-spine.md",
        "needles": ["q_loc^nu can be owned algebraically", "full PPN residual vector"],
        "role": "spine record of algebraic ownership without amplitude closure",
    },
    {
        "source_id": "ppn_bound_requirements",
        "path": RESIDUALS / "P8_Y5_R10_794_PPN_BOUND_REQUIREMENTS.csv",
        "needles": ["PBR794_0_PPN_metric", "PBR794_1_Newton_source"],
        "role": "specific PPN/Newton requirements generated by 794",
    },
    {
        "source_id": "ppn_residual_vector",
        "path": RESIDUALS / "P8_Y5_PPN_RESIDUAL_VECTOR.csv",
        "needles": ["PPN524_7_q_loc_second_order_force", "PPN524_8_readout_metric_mismatch"],
        "role": "global PPN residual vector template",
    },
]


def utc_stamp() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def needle_status(path: Path, needles: list[str]) -> str:
    if not path.exists():
        return "missing_file"
    text = read_text(path)
    missing = [needle for needle in needles if needle not in text]
    if missing:
        return "missing_needles:" + ";".join(missing)
    return "pass"


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def markdown_table(rows: list[dict[str, object]], columns: list[str]) -> str:
    if not rows:
        return "_No rows._"
    header = "| " + " | ".join(columns) + " |"
    separator = "| " + " | ".join(["---"] * len(columns)) + " |"
    lines = [header, separator]
    for row in rows:
        values = [str(row.get(column, "")).replace("\n", " ").replace("|", "\\|") for column in columns]
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines)


def parse_validation_clean(start: int = 665, end: int = 795) -> tuple[bool, str]:
    if not RESIDUALS.exists():
        return False, "residual directory missing"
    failures: list[str] = []
    found = 0
    for path in RESIDUALS.glob("P8_Y5_BRR545_*_VALIDATION.csv"):
        number_text = path.name.replace("P8_Y5_BRR545_", "").replace("_VALIDATION.csv", "")
        if not number_text.isdigit():
            continue
        number = int(number_text)
        if start <= number <= end:
            found += 1
            with path.open("r", encoding="utf-8", newline="") as handle:
                for row in csv.DictReader(handle):
                    if row.get("result") != "pass":
                        failures.append(f"{path.name}:{row.get('check_id')}={row.get('result')}")
    if failures:
        return False, ";".join(failures[:20])
    return found > 0, f"{found} prior validation files clean"


def formalization_change_count() -> int:
    if not FORMALIZATION.exists():
        return -1
    return sum(1 for path in FORMALIZATION.rglob("*") if path.is_file() and datetime.fromtimestamp(path.stat().st_mtime) > FORMALIZATION_CUTOFF)


def source_register_rows(generated_utc: str) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for spec in SOURCE_SPECS:
        path = spec["path"]
        rows.append(
            {
                "source_id": spec["source_id"],
                "path": str(path),
                "exists": str(path.exists()).lower(),
                "needle_check": needle_status(path, spec["needles"]),
                "role": spec["role"],
                "valid_for_claim": "false",
                "generated_utc": generated_utc,
            }
        )
    return rows


def amplitude_budget_rows(generated_utc: str) -> list[dict[str, object]]:
    return [
        {
            "budget_id": "KLB796_0_divergence_zero_not_metric_zero",
            "object": "q_loc cancellation versus K_L amplitude",
            "derived_statement": "partial_mu K_L^{mu nu}=partial^nu Gamma_eff can cancel q_loc in the flat local patch, but K_L^{mu nu} itself remains in the metric/source equation unless separately projected out or bounded.",
            "local_requirement": "K_L must be theorem-zero, metric-invisible, or below Newton/PPN/local-arena residual tolerances.",
            "status": "no_free_lunch_lemma_recorded",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "budget_id": "KLB796_1_elliptic_scale_estimate",
            "object": "Box phi=(2/3)Gamma_eff",
            "derived_statement": "For a local patch of scale L, elliptic scaling gives phi~Gamma_eff L^2 and second derivatives D^2 phi~Gamma_eff, so K_L~Gamma_eff up to boundary and curvature constants.",
            "local_requirement": "A local amplitude suppression theorem must act on Gamma_eff, on the K_L projection, or on the observable response coefficients.",
            "status": "formal_scaling_no_suppression_parameter",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "budget_id": "KLB796_2_Newton_source_fraction",
            "object": "epsilon_K",
            "derived_statement": "epsilon_K = |c^2 Kbar_L,loc,00| / |4 pi G rho| is the direct Newton-source budget used by the prior local branch.",
            "local_requirement": "epsilon_K must be below the adopted local Newton residual tolerance after measured-GM calibration and source normalization are fixed.",
            "status": "missing_numeric_Kbar_and_source_model",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "budget_id": "KLB796_3_PPN_response_matrix",
            "object": "delta_gamma, delta_beta, alpha_i, xi",
            "derived_statement": "K_L can shift weak-field metric coefficients even when its divergence is tuned; q_loc=0 does not set the PPN residual vector to zero.",
            "local_requirement": "Need response coefficients R_PPN[K_L] and comparison to gamma, beta, preferred-frame, and preferred-location limits.",
            "status": "missing_response_matrix",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "budget_id": "KLB796_4_Kperp_boundary_guard",
            "object": "K_perp and boundary data",
            "derived_statement": "The longitudinal solver controls only the chosen trace-free longitudinal component; transverse K_perp and boundary/source-measure pieces can still source local observables.",
            "local_requirement": "K_perp=0, higher-order suppressed, or bounded in the same PPN/orbital/clock/R10 vector.",
            "status": "open_guard_from_794_795",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "budget_id": "KLB796_5_acceptance_condition",
            "object": "local GR/Newton pass",
            "derived_statement": "Local recovery needs q_loc cancellation plus small metric amplitude plus clean PPN/readout/source-normalization gates; cancellation alone is not enough.",
            "local_requirement": "parent-signed source equation, amplitude budget, PPN vector, Kperp guard, and frame/readout theorem or bounds.",
            "status": "not_satisfied",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
    ]


def relaxation_source_rows(generated_utc: str) -> list[dict[str, object]]:
    return [
        {
            "test_id": "PRS796_0_candidate_functional",
            "candidate": "trace-free relaxation functional",
            "equation_or_contract": "J[K_hat]=1/2 ||P_loc(nabla Gamma_eff-div K_hat)||^2 + 1/2 mu_K^2 ||K_hat||^2 + boundary/stability terms, with trace-free projection on K_hat.",
            "what_it_would_buy": "trades exact q_loc cancellation against amplitude control instead of hiding a large K_L counterterm.",
            "failure_or_open_input": "mu_K, inner product, locality, covariance, stress variation, and boundary terms are not parent-derived.",
            "status": "candidate_not_adopted",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "test_id": "PRS796_1_stationary_equation",
            "candidate": "Euler equation for K_hat",
            "equation_or_contract": "Pi_TF L^dagger P_loc(nabla Gamma_eff-div K_hat) + mu_K^2 K_hat = 0, where L maps K_hat to div K_hat and Pi_TF projects trace-free components.",
            "what_it_would_buy": "makes the old balance equation a variational stationary condition rather than a hand-imposed equality.",
            "failure_or_open_input": "With mu_K>0 the residual generally remains nonzero; with mu_K=0 amplitude is uncontrolled.",
            "status": "formal_tradeoff_only",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "test_id": "PRS796_2_dissipative_flow",
            "candidate": "local relaxation dynamics",
            "equation_or_contract": "D_tau K_hat^{mu nu}=-eta_K Pi_TF delta J/delta K_hat_{mu nu}, with eta_K>0 and total stress/exchange accounted by the parent Ward identity.",
            "what_it_would_buy": "could make q_loc small an attractor rather than an axiom, while the mass penalty controls carrier amplitude.",
            "failure_or_open_input": "dissipation must be compatible with covariance, positivity, hyperbolicity/causality, and no PPN transient leakage.",
            "status": "best_next_derivation_route",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "test_id": "PRS796_3_Gammaeff_screening_need",
            "candidate": "local source suppression",
            "equation_or_contract": "If Gamma_eff is locally constant/small or projected outside P_loc, K_L~Gamma_eff may become harmless; if Gamma_eff is order local curvature/source, amplitude remains dangerous.",
            "what_it_would_buy": "turns local GR recovery into a source-screening theorem instead of a pure cancellation theorem.",
            "failure_or_open_input": "No parent-signed Gamma_eff local-screening law is currently available for this route.",
            "status": "required_parallel_gate",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "test_id": "PRS796_4_parent_action_contract",
            "candidate": "promotion requirements",
            "equation_or_contract": "A future parent action must produce J or its conservative equivalent, define P_loc and Pi_TF covariantly, include stress variation, and prove boundary/source/readout silence.",
            "what_it_would_buy": "would connect the trace-free solver to the fundamental field theory rather than a closure repair.",
            "failure_or_open_input": "Not yet in corpus; should be the 797 target.",
            "status": "promotion_contract_written",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
    ]


def residual_vector_rows(generated_utc: str) -> list[dict[str, object]]:
    return [
        {
            "residual_id": "RBV796_0_Newton_source",
            "arena": "Newton/local source",
            "quantity": "epsilon_K = |c^2 Kbar_L,loc,00| / |4 pi G rho|",
            "needed_input": "Kbar_L,loc,00 from the parent source equation and calibrated matter density rho.",
            "current_status": "missing_numeric_source_model",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_1_PPN_gamma_beta",
            "arena": "PPN metric",
            "quantity": "delta_gamma_K, delta_beta_K",
            "needed_input": "weak-field metric response of K_L and K_perp after measured-GM calibration.",
            "current_status": "missing_response_matrix",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_2_PPN_preferred_frame",
            "arena": "PPN preferred-frame/location",
            "quantity": "alpha1_K, alpha2_K, alpha3_K, xi_K",
            "needed_input": "anisotropic/time-dependent parts of K_L, K_perp, boundary terms, and frame/readout leakage.",
            "current_status": "missing_frame_projection",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_3_clock",
            "arena": "clocks/redshift",
            "quantity": "delta_clock_K",
            "needed_input": "clock metric/readout map and K_L contribution to g_00 along lab/Solar trajectories.",
            "current_status": "missing_clock_projection",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_4_orbital",
            "arena": "orbital/ephemeris",
            "quantity": "a_K or perihelion/range residual",
            "needed_input": "spatial gradient of K_L-induced potential or direct non-geodesic response coefficient.",
            "current_status": "missing_orbital_projection",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_5_R10_short_range",
            "arena": "R10/lab fifth-force",
            "quantity": "alpha_K(lambda)",
            "needed_input": "canonical range/mass, source charges, and coupling normalization for the K_L carrier or associated parent mode.",
            "current_status": "missing_alpha_lambda_map",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "residual_id": "RBV796_6_WEP_readout",
            "arena": "WEP/readout",
            "quantity": "eta_AB and frame mismatch",
            "needed_input": "proof that ordinary matter sees only e, omega[e], and owned gauge fields, or species-dependent charges below limits.",
            "current_status": "missing_no_spurion_or_charge_vector",
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
    ]


def decision_rows(generated_utc: str) -> list[dict[str, object]]:
    return [
        {
            "decision_id": "D796_0_no_amplitude_pass",
            "decision": "Does q_loc cancellation by K_L prove local GR/Newton?",
            "reason": "No. The carrier can be order Gamma_eff and can still contribute to local metric/source observables.",
            "result": "no_local_GR_claim",
            "next_target": NEXT_TARGET,
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "decision_id": "D796_1_relaxation_route_selected",
            "decision": "Best next derivation route",
            "reason": "Pure amplitude pass is impossible without either Gamma_eff screening or parent response coefficients; the relaxation functional gives the cleanest action contract to test.",
            "result": "build_parent_relaxation_source_action_contract",
            "next_target": NEXT_TARGET,
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
        {
            "decision_id": "D796_2_budget_vector_required",
            "decision": "Empirical/local safety route",
            "reason": "Every local arena needs a response coefficient or theorem-zero; existing rows are schemas, not sourced numeric passes.",
            "result": "retain_budget_vector_as_blocker",
            "next_target": NEXT_TARGET,
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        },
    ]


def summary_rows(generated_utc: str) -> list[dict[str, object]]:
    return [
        {
            "status": STATUS,
            "claim_ceiling": CLAIM_CEILING,
            "main_result": "The trace-free K_L solver has a no-free-lunch amplitude problem: cancelling q_loc does not make K_L small. A parent relaxation/source action with amplitude penalty is the least-cheaty next route, but it is not yet derived.",
            "hard_blocker": "Need parent-signed Gamma_eff/K_hat relaxation or screening plus K_L/Kperp response coefficients for Newton, PPN, clocks, orbital, R10, and WEP/readout.",
            "next_target": NEXT_TARGET,
            "valid_for_claim": "false",
            "generated_utc": generated_utc,
        }
    ]


def all_outputs_scoped() -> bool:
    root = POST_CHECKPOINT.resolve()
    for path in OUTPUT_PATHS:
        resolved_parent = path.parent.resolve()
        if root != resolved_parent and root not in resolved_parent.parents:
            return False
    return True


def validation_rows(
    sources: list[dict[str, object]],
    amplitude: list[dict[str, object]],
    relaxation: list[dict[str, object]],
    residuals: list[dict[str, object]],
    decisions: list[dict[str, object]],
    summary: list[dict[str, object]],
) -> list[dict[str, object]]:
    prior_clean, prior_detail = parse_validation_clean()
    source_ok = all(row["exists"] == "true" and row["needle_check"] == "pass" for row in sources)
    all_nonclaim = all(
        row.get("valid_for_claim") == "false"
        for group in [sources, amplitude, relaxation, residuals, decisions, summary]
        for row in group
    )
    no_amplitude_pass = any(row["budget_id"] == "KLB796_5_acceptance_condition" and row["status"] == "not_satisfied" for row in amplitude)
    scale_law = any(row["budget_id"] == "KLB796_1_elliptic_scale_estimate" and "K_L~Gamma_eff" in row["derived_statement"] for row in amplitude)
    relaxation_contract = any(row["test_id"] == "PRS796_4_parent_action_contract" for row in relaxation)
    relaxation_not_adopted = all(row["valid_for_claim"] == "false" for row in relaxation) and any(row["status"] == "best_next_derivation_route" for row in relaxation)
    budget_vector_complete = {row["residual_id"] for row in residuals} == {
        "RBV796_0_Newton_source",
        "RBV796_1_PPN_gamma_beta",
        "RBV796_2_PPN_preferred_frame",
        "RBV796_3_clock",
        "RBV796_4_orbital",
        "RBV796_5_R10_short_range",
        "RBV796_6_WEP_readout",
    }
    ppn_missing = any(row["residual_id"] == "RBV796_1_PPN_gamma_beta" and row["current_status"] == "missing_response_matrix" for row in residuals)
    next_target_selected = summary[0]["next_target"] == NEXT_TARGET and any(row["decision_id"] == "D796_1_relaxation_route_selected" for row in decisions)
    formalization_count = formalization_change_count()

    checks = [
        ("V796_0_sources_exist_and_needles", source_ok, "all source paths exist and needles are present"),
        ("V796_1_prior_665_795_clean", prior_clean, prior_detail),
        ("V796_2_outputs_scoped", all_outputs_scoped(), str(POST_CHECKPOINT)),
        ("V796_3_all_rows_nonclaim", all_nonclaim, "all generated rows valid_for_claim=false"),
        ("V796_4_no_amplitude_pass", no_amplitude_pass, "K_L cancellation is not enough for local GR/Newton"),
        ("V796_5_scale_law_present", scale_law, "K_L~Gamma_eff no-free-lunch scaling recorded"),
        ("V796_6_relaxation_contract_written", relaxation_contract, "parent relaxation source/action contract row present"),
        ("V796_7_relaxation_not_adopted", relaxation_not_adopted, "relaxation route selected but not claimed"),
        ("V796_8_budget_vector_complete", budget_vector_complete, "Newton/PPN/clock/orbital/R10/WEP rows present"),
        ("V796_9_ppn_response_missing", ppn_missing, "PPN response matrix remains missing"),
        ("V796_10_next_target_selected", next_target_selected, NEXT_TARGET),
        ("V796_11_no_local_GR_claim", all_nonclaim and no_amplitude_pass, "local GR/Newton remains blocked"),
        ("V796_12_claim_artifacts_absent", not (POST_CHECKPOINT / "LOCAL_GR_CLAIM.md").exists(), "no local-GR claim artifact present"),
        ("V796_13_formalization_workbench_untouched", formalization_count == 0, f"formalization_changed_after_cutoff={formalization_count}"),
        ("V796_14_validation_rows_ready", True, "validation table constructed"),
    ]
    return [{"check_id": check_id, "result": "pass" if passed else "fail", "detail": detail} for check_id, passed, detail in checks]


def build_doc(
    sources: list[dict[str, object]],
    amplitude: list[dict[str, object]],
    relaxation: list[dict[str, object]],
    residuals: list[dict[str, object]],
    decisions: list[dict[str, object]],
    summary: list[dict[str, object]],
    validation: list[dict[str, object]],
) -> None:
    text = f"""# 796 - Y5 R10 KL Amplitude PPN Budget Or Parent Relaxation Source

Current result: **the trace-free `K_L` route has a no-free-lunch amplitude problem**. The flat-patch solver can cancel `q_loc`, but elliptic scaling says the carrier itself is generically `K_L~Gamma_eff`. That means `q_loc=0` is not local GR unless the carrier is parent-suppressed, metric-invisible, or below Newton/PPN/clock/orbital/R10/WEP bounds.

## Nonclaim Summary

{markdown_table(summary, ["status", "claim_ceiling", "main_result", "hard_blocker", "next_target", "valid_for_claim"])}

## KL Amplitude And PPN Budget

{markdown_table(amplitude, ["budget_id", "object", "derived_statement", "local_requirement", "status", "valid_for_claim"])}

## Parent Relaxation Source Test

{markdown_table(relaxation, ["test_id", "candidate", "equation_or_contract", "what_it_would_buy", "failure_or_open_input", "status", "valid_for_claim"])}

## Local Residual Budget Vector

{markdown_table(residuals, ["residual_id", "arena", "quantity", "needed_input", "current_status", "valid_for_claim"])}

## Decision

{markdown_table(decisions, ["decision_id", "decision", "reason", "result", "next_target", "valid_for_claim"])}

## Source Register

{markdown_table(sources, ["source_id", "path", "exists", "needle_check", "role", "valid_for_claim"])}

## Validation

{markdown_table(validation, ["check_id", "result", "detail"])}

## Verdict

`K_L` is still useful, but it is not a local-GR proof. The exact trap is now named: divergence cancellation does not suppress the tensor amplitude. The next honest route is a parent relaxation/source-action contract that either screens `Gamma_eff`, penalizes `K_L` amplitude while preserving covariance and Ward identities, or supplies response coefficients proving the residuals are below local bounds.

## Next Target

`{NEXT_TARGET}`
"""
    OUTPUT_DOC.write_text(text, encoding="utf-8")


def main() -> None:
    generated_utc = utc_stamp()
    sources = source_register_rows(generated_utc)
    amplitude = amplitude_budget_rows(generated_utc)
    relaxation = relaxation_source_rows(generated_utc)
    residuals = residual_vector_rows(generated_utc)
    decisions = decision_rows(generated_utc)
    summary = summary_rows(generated_utc)
    validation = validation_rows(sources, amplitude, relaxation, residuals, decisions, summary)

    write_csv(SOURCE_REGISTER_PATH, sources, ["source_id", "path", "exists", "needle_check", "role", "valid_for_claim", "generated_utc"])
    write_csv(AMPLITUDE_BUDGET_PATH, amplitude, ["budget_id", "object", "derived_statement", "local_requirement", "status", "valid_for_claim", "generated_utc"])
    write_csv(RELAXATION_SOURCE_PATH, relaxation, ["test_id", "candidate", "equation_or_contract", "what_it_would_buy", "failure_or_open_input", "status", "valid_for_claim", "generated_utc"])
    write_csv(RESIDUAL_VECTOR_PATH, residuals, ["residual_id", "arena", "quantity", "needed_input", "current_status", "valid_for_claim", "generated_utc"])
    write_csv(DECISION_PATH, decisions, ["decision_id", "decision", "reason", "result", "next_target", "valid_for_claim", "generated_utc"])
    write_csv(NONCLAIM_SUMMARY_PATH, summary, ["status", "claim_ceiling", "main_result", "hard_blocker", "next_target", "valid_for_claim", "generated_utc"])
    write_csv(VALIDATION_PATH, validation, ["check_id", "result", "detail"])
    build_doc(sources, amplitude, relaxation, residuals, decisions, summary, validation)

    failures = [row for row in validation if row["result"] != "pass"]
    if failures:
        failure_text = "; ".join(f"{row['check_id']}={row['detail']}" for row in failures)
        raise SystemExit(f"796 validation failed: {failure_text}")

    print(f"wrote {OUTPUT_DOC}")
    print(f"wrote {VALIDATION_PATH}")
    print(f"status={STATUS}")
    print(f"next={NEXT_TARGET}")


if __name__ == "__main__":
    main()
